[network]
# list of peers
peer.1=http://localhost:4481
#peer.2=http://localhost:5481
#peer.3=http://localhost:6481
# raft node ID
peerId = 1
# raft cluster ID
clusterId = 1
# optional peerName
peerName=first

[server]
# serve UI, REST, metrics, static, raft
httpAddress=localhost:4481
# serve gRPC client requests
grpcAddress=localhost:4482

[database]

# create dirs is not exist
createIfNotExist=true

rootDir=/tmp/bigbagger

#dataDir=/tmp/bigbagger/data
#walDir=/tmp/bigbagger/WAL
#snapDir=/tmp/bigbagger/snap

[compression]
# supported compressors:  NO, FLATE, GZIP, LZW, ZLIB, BZIP2, LZ4
compressor=LZ4
# supported levels: 0, 1, 6, 9 (whereas 6 is default)
level=6

[encryption]
# supported ciphers: NO, AES
cipher=AES
# supported modes:  NO, GCM, CFB
mode=CFB
# supported key size in bits:  0, 128, 192, 256
keySize=256
# key will be retrieved from security context
topo=password


[security]
password=De6*u1tPassw0rd!


