// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cserverpb.proto

package cserverpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_SUCCESS             StatusCode = 0
	StatusCode_SUCCESS_NOT_UPDATED StatusCode = 1
	StatusCode_ERROR_NO_REGION     StatusCode = 10
	StatusCode_ERROR_BAD_REQUEST   StatusCode = 11
	StatusCode_ERROR_POLICY        StatusCode = 12
	StatusCode_ERROR_MIGRATION     StatusCode = 13
	StatusCode_ERROR_NETWORK       StatusCode = 14
	StatusCode_ERROR_AUTH          StatusCode = 15
	StatusCode_ERROR_FORBIDDEN     StatusCode = 16
	StatusCode_ERROR_TIMEOUT       StatusCode = 17
	StatusCode_ERROR_OVERLOAD      StatusCode = 18
	StatusCode_ERROR_OVERFLOW      StatusCode = 19
	StatusCode_ERROR_LOCKED        StatusCode = 20
	StatusCode_ERROR_ABORTED       StatusCode = 21
	StatusCode_ERROR_INTERRUPTED   StatusCode = 22
	StatusCode_ERROR_UNSUPPORTED   StatusCode = 23
	StatusCode_ERROR_DRIVER        StatusCode = 24
	StatusCode_ERROR_IO            StatusCode = 25
	StatusCode_ERROR_INTERNAL      StatusCode = 26
)

var StatusCode_name = map[int32]string{
	0:  "SUCCESS",
	1:  "SUCCESS_NOT_UPDATED",
	10: "ERROR_NO_REGION",
	11: "ERROR_BAD_REQUEST",
	12: "ERROR_POLICY",
	13: "ERROR_MIGRATION",
	14: "ERROR_NETWORK",
	15: "ERROR_AUTH",
	16: "ERROR_FORBIDDEN",
	17: "ERROR_TIMEOUT",
	18: "ERROR_OVERLOAD",
	19: "ERROR_OVERFLOW",
	20: "ERROR_LOCKED",
	21: "ERROR_ABORTED",
	22: "ERROR_INTERRUPTED",
	23: "ERROR_UNSUPPORTED",
	24: "ERROR_DRIVER",
	25: "ERROR_IO",
	26: "ERROR_INTERNAL",
}

var StatusCode_value = map[string]int32{
	"SUCCESS":             0,
	"SUCCESS_NOT_UPDATED": 1,
	"ERROR_NO_REGION":     10,
	"ERROR_BAD_REQUEST":   11,
	"ERROR_POLICY":        12,
	"ERROR_MIGRATION":     13,
	"ERROR_NETWORK":       14,
	"ERROR_AUTH":          15,
	"ERROR_FORBIDDEN":     16,
	"ERROR_TIMEOUT":       17,
	"ERROR_OVERLOAD":      18,
	"ERROR_OVERFLOW":      19,
	"ERROR_LOCKED":        20,
	"ERROR_ABORTED":       21,
	"ERROR_INTERRUPTED":   22,
	"ERROR_UNSUPPORTED":   23,
	"ERROR_DRIVER":        24,
	"ERROR_IO":            25,
	"ERROR_INTERNAL":      26,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{0}
}

type Key struct {
	MajorKey             []byte   `protobuf:"bytes,1,opt,name=majorKey,proto3" json:"majorKey,omitempty"`
	RegionName           string   `protobuf:"bytes,2,opt,name=regionName,proto3" json:"regionName,omitempty"`
	MinorKey             []byte   `protobuf:"bytes,3,opt,name=minorKey,proto3" json:"minorKey,omitempty"`
	Timestamp            uint64   `protobuf:"fixed64,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetMajorKey() []byte {
	if m != nil {
		return m.MajorKey
	}
	return nil
}

func (m *Key) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

func (m *Key) GetMinorKey() []byte {
	if m != nil {
		return m.MinorKey
	}
	return nil
}

func (m *Key) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type TxOperation struct {
	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Operation:
	//	*TxOperation_Get
	//	*TxOperation_Range
	//	*TxOperation_Touch
	//	*TxOperation_Put
	//	*TxOperation_Remove
	Operation            isTxOperation_Operation `protobuf_oneof:"operation"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TxOperation) Reset()         { *m = TxOperation{} }
func (m *TxOperation) String() string { return proto.CompactTextString(m) }
func (*TxOperation) ProtoMessage()    {}
func (*TxOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{1}
}

func (m *TxOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOperation.Unmarshal(m, b)
}
func (m *TxOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOperation.Marshal(b, m, deterministic)
}
func (m *TxOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOperation.Merge(m, src)
}
func (m *TxOperation) XXX_Size() int {
	return xxx_messageInfo_TxOperation.Size(m)
}
func (m *TxOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TxOperation proto.InternalMessageInfo

func (m *TxOperation) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type isTxOperation_Operation interface {
	isTxOperation_Operation()
}

type TxOperation_Get struct {
	Get *GetOperation `protobuf:"bytes,11,opt,name=get,proto3,oneof"`
}

type TxOperation_Range struct {
	Range *RangeOperation `protobuf:"bytes,12,opt,name=range,proto3,oneof"`
}

type TxOperation_Touch struct {
	Touch *TouchOperation `protobuf:"bytes,13,opt,name=touch,proto3,oneof"`
}

type TxOperation_Put struct {
	Put *PutOperation `protobuf:"bytes,14,opt,name=put,proto3,oneof"`
}

type TxOperation_Remove struct {
	Remove *RemoveOperation `protobuf:"bytes,15,opt,name=remove,proto3,oneof"`
}

func (*TxOperation_Get) isTxOperation_Operation() {}

func (*TxOperation_Range) isTxOperation_Operation() {}

func (*TxOperation_Touch) isTxOperation_Operation() {}

func (*TxOperation_Put) isTxOperation_Operation() {}

func (*TxOperation_Remove) isTxOperation_Operation() {}

func (m *TxOperation) GetOperation() isTxOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *TxOperation) GetGet() *GetOperation {
	if x, ok := m.GetOperation().(*TxOperation_Get); ok {
		return x.Get
	}
	return nil
}

func (m *TxOperation) GetRange() *RangeOperation {
	if x, ok := m.GetOperation().(*TxOperation_Range); ok {
		return x.Range
	}
	return nil
}

func (m *TxOperation) GetTouch() *TouchOperation {
	if x, ok := m.GetOperation().(*TxOperation_Touch); ok {
		return x.Touch
	}
	return nil
}

func (m *TxOperation) GetPut() *PutOperation {
	if x, ok := m.GetOperation().(*TxOperation_Put); ok {
		return x.Put
	}
	return nil
}

func (m *TxOperation) GetRemove() *RemoveOperation {
	if x, ok := m.GetOperation().(*TxOperation_Remove); ok {
		return x.Remove
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TxOperation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TxOperation_OneofMarshaler, _TxOperation_OneofUnmarshaler, _TxOperation_OneofSizer, []interface{}{
		(*TxOperation_Get)(nil),
		(*TxOperation_Range)(nil),
		(*TxOperation_Touch)(nil),
		(*TxOperation_Put)(nil),
		(*TxOperation_Remove)(nil),
	}
}

func _TxOperation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TxOperation)
	// operation
	switch x := m.Operation.(type) {
	case *TxOperation_Get:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *TxOperation_Range:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Range); err != nil {
			return err
		}
	case *TxOperation_Touch:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Touch); err != nil {
			return err
		}
	case *TxOperation_Put:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case *TxOperation_Remove:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Remove); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TxOperation.Operation has unexpected type %T", x)
	}
	return nil
}

func _TxOperation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TxOperation)
	switch tag {
	case 11: // operation.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &TxOperation_Get{msg}
		return true, err
	case 12: // operation.range
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RangeOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &TxOperation_Range{msg}
		return true, err
	case 13: // operation.touch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TouchOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &TxOperation_Touch{msg}
		return true, err
	case 14: // operation.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &TxOperation_Put{msg}
		return true, err
	case 15: // operation.remove
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &TxOperation_Remove{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TxOperation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TxOperation)
	// operation
	switch x := m.Operation.(type) {
	case *TxOperation_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TxOperation_Range:
		s := proto.Size(x.Range)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TxOperation_Touch:
		s := proto.Size(x.Touch)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TxOperation_Put:
		s := proto.Size(x.Put)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TxOperation_Remove:
		s := proto.Size(x.Remove)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetOperation struct {
	HeadOnly             bool     `protobuf:"varint,1,opt,name=headOnly,proto3" json:"headOnly,omitempty"`
	LessOrEqualRecords   uint32   `protobuf:"varint,2,opt,name=lessOrEqualRecords,proto3" json:"lessOrEqualRecords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOperation) Reset()         { *m = GetOperation{} }
func (m *GetOperation) String() string { return proto.CompactTextString(m) }
func (*GetOperation) ProtoMessage()    {}
func (*GetOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{2}
}

func (m *GetOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOperation.Unmarshal(m, b)
}
func (m *GetOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOperation.Marshal(b, m, deterministic)
}
func (m *GetOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOperation.Merge(m, src)
}
func (m *GetOperation) XXX_Size() int {
	return xxx_messageInfo_GetOperation.Size(m)
}
func (m *GetOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOperation.DiscardUnknown(m)
}

var xxx_messageInfo_GetOperation proto.InternalMessageInfo

func (m *GetOperation) GetHeadOnly() bool {
	if m != nil {
		return m.HeadOnly
	}
	return false
}

func (m *GetOperation) GetLessOrEqualRecords() uint32 {
	if m != nil {
		return m.LessOrEqualRecords
	}
	return 0
}

type RangeOperation struct {
	HeadOnly             bool     `protobuf:"varint,1,opt,name=headOnly,proto3" json:"headOnly,omitempty"`
	EndMinorKey          []byte   `protobuf:"bytes,2,opt,name=endMinorKey,proto3" json:"endMinorKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeOperation) Reset()         { *m = RangeOperation{} }
func (m *RangeOperation) String() string { return proto.CompactTextString(m) }
func (*RangeOperation) ProtoMessage()    {}
func (*RangeOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{3}
}

func (m *RangeOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeOperation.Unmarshal(m, b)
}
func (m *RangeOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeOperation.Marshal(b, m, deterministic)
}
func (m *RangeOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeOperation.Merge(m, src)
}
func (m *RangeOperation) XXX_Size() int {
	return xxx_messageInfo_RangeOperation.Size(m)
}
func (m *RangeOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeOperation.DiscardUnknown(m)
}

var xxx_messageInfo_RangeOperation proto.InternalMessageInfo

func (m *RangeOperation) GetHeadOnly() bool {
	if m != nil {
		return m.HeadOnly
	}
	return false
}

func (m *RangeOperation) GetEndMinorKey() []byte {
	if m != nil {
		return m.EndMinorKey
	}
	return nil
}

type TouchOperation struct {
	TtlSeconds           uint32   `protobuf:"varint,1,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchOperation) Reset()         { *m = TouchOperation{} }
func (m *TouchOperation) String() string { return proto.CompactTextString(m) }
func (*TouchOperation) ProtoMessage()    {}
func (*TouchOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{4}
}

func (m *TouchOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchOperation.Unmarshal(m, b)
}
func (m *TouchOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchOperation.Marshal(b, m, deterministic)
}
func (m *TouchOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchOperation.Merge(m, src)
}
func (m *TouchOperation) XXX_Size() int {
	return xxx_messageInfo_TouchOperation.Size(m)
}
func (m *TouchOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TouchOperation proto.InternalMessageInfo

func (m *TouchOperation) GetTtlSeconds() uint32 {
	if m != nil {
		return m.TtlSeconds
	}
	return 0
}

type PutOperation struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	CompressOnServer     bool     `protobuf:"varint,2,opt,name=compressOnServer,proto3" json:"compressOnServer,omitempty"`
	EncryptOnServer      bool     `protobuf:"varint,3,opt,name=encryptOnServer,proto3" json:"encryptOnServer,omitempty"`
	TtlSeconds           uint32   `protobuf:"varint,5,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	CompareAndSet        bool     `protobuf:"varint,7,opt,name=compareAndSet,proto3" json:"compareAndSet,omitempty"`
	Version              uint64   `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutOperation) Reset()         { *m = PutOperation{} }
func (m *PutOperation) String() string { return proto.CompactTextString(m) }
func (*PutOperation) ProtoMessage()    {}
func (*PutOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{5}
}

func (m *PutOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutOperation.Unmarshal(m, b)
}
func (m *PutOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutOperation.Marshal(b, m, deterministic)
}
func (m *PutOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutOperation.Merge(m, src)
}
func (m *PutOperation) XXX_Size() int {
	return xxx_messageInfo_PutOperation.Size(m)
}
func (m *PutOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_PutOperation.DiscardUnknown(m)
}

var xxx_messageInfo_PutOperation proto.InternalMessageInfo

func (m *PutOperation) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutOperation) GetCompressOnServer() bool {
	if m != nil {
		return m.CompressOnServer
	}
	return false
}

func (m *PutOperation) GetEncryptOnServer() bool {
	if m != nil {
		return m.EncryptOnServer
	}
	return false
}

func (m *PutOperation) GetTtlSeconds() uint32 {
	if m != nil {
		return m.TtlSeconds
	}
	return 0
}

func (m *PutOperation) GetCompareAndSet() bool {
	if m != nil {
		return m.CompareAndSet
	}
	return false
}

func (m *PutOperation) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RemoveOperation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOperation) Reset()         { *m = RemoveOperation{} }
func (m *RemoveOperation) String() string { return proto.CompactTextString(m) }
func (*RemoveOperation) ProtoMessage()    {}
func (*RemoveOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{6}
}

func (m *RemoveOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOperation.Unmarshal(m, b)
}
func (m *RemoveOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOperation.Marshal(b, m, deterministic)
}
func (m *RemoveOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOperation.Merge(m, src)
}
func (m *RemoveOperation) XXX_Size() int {
	return xxx_messageInfo_RemoveOperation.Size(m)
}
func (m *RemoveOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOperation.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOperation proto.InternalMessageInfo

type TxOperationResult struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=cdb.StatusCode" json:"status,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Records              []*Record  `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TxOperationResult) Reset()         { *m = TxOperationResult{} }
func (m *TxOperationResult) String() string { return proto.CompactTextString(m) }
func (*TxOperationResult) ProtoMessage()    {}
func (*TxOperationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{7}
}

func (m *TxOperationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOperationResult.Unmarshal(m, b)
}
func (m *TxOperationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOperationResult.Marshal(b, m, deterministic)
}
func (m *TxOperationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOperationResult.Merge(m, src)
}
func (m *TxOperationResult) XXX_Size() int {
	return xxx_messageInfo_TxOperationResult.Size(m)
}
func (m *TxOperationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOperationResult.DiscardUnknown(m)
}

var xxx_messageInfo_TxOperationResult proto.InternalMessageInfo

func (m *TxOperationResult) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

func (m *TxOperationResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TxOperationResult) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Head struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ExpiresAt            uint64   `protobuf:"fixed64,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	Timestamp            uint64   `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DiskSize             int64    `protobuf:"varint,4,opt,name=diskSize,proto3" json:"diskSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{8}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Head) GetExpiresAt() uint64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *Head) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Head) GetDiskSize() int64 {
	if m != nil {
		return m.DiskSize
	}
	return 0
}

type Record struct {
	Head                 *Head    `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{9}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Record) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type RawRecord struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Head                 *Head    `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Deleted              bool     `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	UserMeta             []byte   `protobuf:"bytes,5,opt,name=userMeta,proto3" json:"userMeta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawRecord) Reset()         { *m = RawRecord{} }
func (m *RawRecord) String() string { return proto.CompactTextString(m) }
func (*RawRecord) ProtoMessage()    {}
func (*RawRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{10}
}

func (m *RawRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawRecord.Unmarshal(m, b)
}
func (m *RawRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawRecord.Marshal(b, m, deterministic)
}
func (m *RawRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawRecord.Merge(m, src)
}
func (m *RawRecord) XXX_Size() int {
	return xxx_messageInfo_RawRecord.Size(m)
}
func (m *RawRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RawRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RawRecord proto.InternalMessageInfo

func (m *RawRecord) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawRecord) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *RawRecord) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RawRecord) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *RawRecord) GetUserMeta() []byte {
	if m != nil {
		return m.UserMeta
	}
	return nil
}

type Transaction struct {
	Operations           []*TxOperation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{11}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetOperations() []*TxOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type TransactionResult struct {
	Results              []*TxOperationResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransactionResult) Reset()         { *m = TransactionResult{} }
func (m *TransactionResult) String() string { return proto.CompactTextString(m) }
func (*TransactionResult) ProtoMessage()    {}
func (*TransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e213cc6e4c2fe5a, []int{12}
}

func (m *TransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResult.Unmarshal(m, b)
}
func (m *TransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResult.Marshal(b, m, deterministic)
}
func (m *TransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResult.Merge(m, src)
}
func (m *TransactionResult) XXX_Size() int {
	return xxx_messageInfo_TransactionResult.Size(m)
}
func (m *TransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResult proto.InternalMessageInfo

func (m *TransactionResult) GetResults() []*TxOperationResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterEnum("cdb.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Key)(nil), "cdb.Key")
	proto.RegisterType((*TxOperation)(nil), "cdb.TxOperation")
	proto.RegisterType((*GetOperation)(nil), "cdb.GetOperation")
	proto.RegisterType((*RangeOperation)(nil), "cdb.RangeOperation")
	proto.RegisterType((*TouchOperation)(nil), "cdb.TouchOperation")
	proto.RegisterType((*PutOperation)(nil), "cdb.PutOperation")
	proto.RegisterType((*RemoveOperation)(nil), "cdb.RemoveOperation")
	proto.RegisterType((*TxOperationResult)(nil), "cdb.TxOperationResult")
	proto.RegisterType((*Head)(nil), "cdb.Head")
	proto.RegisterType((*Record)(nil), "cdb.Record")
	proto.RegisterType((*RawRecord)(nil), "cdb.RawRecord")
	proto.RegisterType((*Transaction)(nil), "cdb.Transaction")
	proto.RegisterType((*TransactionResult)(nil), "cdb.TransactionResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatabaseServiceClient is the client API for DatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatabaseServiceClient interface {
	Execute(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResult, error)
}

type databaseServiceClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseServiceClient(cc *grpc.ClientConn) DatabaseServiceClient {
	return &databaseServiceClient{cc}
}

func (c *databaseServiceClient) Execute(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionResult, error) {
	out := new(TransactionResult)
	err := c.cc.Invoke(ctx, "/cdb.DatabaseService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseServiceServer is the server API for DatabaseService service.
type DatabaseServiceServer interface {
	Execute(context.Context, *Transaction) (*TransactionResult, error)
}

func RegisterDatabaseServiceServer(s *grpc.Server, srv DatabaseServiceServer) {
	s.RegisterService(&_DatabaseService_serviceDesc, srv)
}

func _DatabaseService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdb.DatabaseService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).Execute(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatabaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cdb.DatabaseService",
	HandlerType: (*DatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _DatabaseService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cserverpb.proto",
}

func init() { proto.RegisterFile("cserverpb.proto", fileDescriptor_0e213cc6e4c2fe5a) }

var fileDescriptor_0e213cc6e4c2fe5a = []byte{
	// 1136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0x45, 0xc7, 0x96, 0x47, 0xb2, 0x44, 0xad, 0x9d, 0x84, 0x15, 0xd2, 0xc2, 0x20, 0x1a,
	0xd4, 0x70, 0x1b, 0xc9, 0x51, 0x6f, 0x06, 0x8a, 0x56, 0x3f, 0x4c, 0x22, 0xd8, 0x16, 0xd5, 0x15,
	0x95, 0xa0, 0x01, 0x0a, 0x63, 0x45, 0x2e, 0x64, 0x26, 0x12, 0xc9, 0x72, 0x97, 0x8a, 0xdd, 0xa2,
	0x97, 0x3e, 0x40, 0x0f, 0xe9, 0x1b, 0xf4, 0x35, 0xfa, 0x18, 0xbd, 0xf5, 0xdc, 0xc7, 0x28, 0xd0,
	0x62, 0x97, 0x94, 0x48, 0xc9, 0x6d, 0x7a, 0x92, 0xe6, 0x9b, 0x6f, 0x86, 0xdf, 0xee, 0x7c, 0x43,
	0x10, 0xaa, 0x0e, 0xa3, 0xd1, 0x82, 0x46, 0xe1, 0xa4, 0x11, 0x46, 0x01, 0x0f, 0x90, 0xea, 0xb8,
	0x93, 0xfa, 0xc3, 0x69, 0x10, 0x4c, 0x67, 0xb4, 0x49, 0x42, 0xaf, 0x49, 0x7c, 0x3f, 0xe0, 0x84,
	0x7b, 0x81, 0xcf, 0x12, 0x4a, 0xfd, 0x33, 0xf9, 0xe3, 0x3c, 0x9e, 0x52, 0xff, 0x31, 0x7b, 0x4b,
	0xa6, 0x53, 0x1a, 0x35, 0x83, 0x50, 0x32, 0x6e, 0xb3, 0x8d, 0x1f, 0x40, 0x3d, 0xa3, 0x37, 0xa8,
	0x0e, 0xc5, 0x39, 0x79, 0x1d, 0x44, 0x67, 0xf4, 0x46, 0x57, 0x0e, 0x95, 0xa3, 0x32, 0x5e, 0xc5,
	0xe8, 0x23, 0x80, 0x88, 0x4e, 0xbd, 0xc0, 0x1f, 0x90, 0x39, 0xd5, 0x0b, 0x87, 0xca, 0xd1, 0x2e,
	0xce, 0x21, 0xb2, 0xd6, 0xf3, 0x93, 0x5a, 0x35, 0xad, 0x4d, 0x63, 0xf4, 0x10, 0x76, 0xb9, 0x37,
	0xa7, 0x8c, 0x93, 0x79, 0xa8, 0x6f, 0x1d, 0x2a, 0x47, 0xdb, 0x38, 0x03, 0x8c, 0x9f, 0x0b, 0x50,
	0xb2, 0xaf, 0xad, 0x90, 0x46, 0x52, 0x13, 0xaa, 0x83, 0xfa, 0x26, 0x15, 0x50, 0x6a, 0x15, 0x1b,
	0x8e, 0x3b, 0x69, 0x9c, 0xd1, 0x1b, 0x2c, 0x40, 0xf4, 0x08, 0xd4, 0x29, 0xe5, 0x7a, 0x49, 0xe6,
	0x6a, 0x32, 0xf7, 0x8c, 0xf2, 0x55, 0xed, 0xf3, 0x3b, 0x58, 0xe4, 0xd1, 0xa7, 0x70, 0x37, 0x22,
	0xfe, 0x94, 0xea, 0x65, 0x49, 0xdc, 0x97, 0x44, 0x2c, 0x90, 0x3c, 0x35, 0xe1, 0x08, 0x32, 0x0f,
	0x62, 0xe7, 0x4a, 0xdf, 0xcb, 0x91, 0x6d, 0x81, 0xac, 0x91, 0x25, 0x47, 0x08, 0x08, 0x63, 0xae,
	0x57, 0x72, 0x02, 0x86, 0xf1, 0xba, 0x80, 0x30, 0xe6, 0xa8, 0x01, 0xdb, 0x11, 0x9d, 0x07, 0x0b,
	0xaa, 0x57, 0x25, 0xf3, 0x20, 0x51, 0x20, 0xa1, 0x3c, 0x39, 0x65, 0x75, 0x4a, 0xb0, 0x1b, 0x2c,
	0x61, 0xe3, 0x15, 0x94, 0xf3, 0x87, 0x12, 0x57, 0x7b, 0x45, 0x89, 0x6b, 0xf9, 0xb3, 0xe4, 0x56,
	0x8a, 0x78, 0x15, 0xa3, 0x06, 0xa0, 0x19, 0x65, 0xcc, 0x8a, 0xcc, 0xef, 0x62, 0x32, 0xc3, 0xd4,
	0x09, 0x22, 0x97, 0xc9, 0xf1, 0xec, 0xe1, 0x7f, 0xc9, 0x18, 0x03, 0xa8, 0xac, 0xdf, 0xc3, 0x7b,
	0xbb, 0x1f, 0x42, 0x89, 0xfa, 0xee, 0xc5, 0x72, 0xae, 0x05, 0x39, 0xd7, 0x3c, 0x64, 0x9c, 0x40,
	0x65, 0xfd, 0xaa, 0x84, 0x51, 0x38, 0x9f, 0x8d, 0xa8, 0x13, 0xf8, 0x2e, 0x93, 0x1d, 0xf7, 0x70,
	0x0e, 0x31, 0xfe, 0x50, 0xa0, 0x9c, 0xbf, 0x32, 0x74, 0x00, 0x77, 0x17, 0x64, 0x16, 0xd3, 0xd4,
	0x72, 0x49, 0x80, 0x8e, 0x41, 0x73, 0x82, 0x79, 0x18, 0x89, 0x23, 0xf8, 0x23, 0xe9, 0x7f, 0xf9,
	0xfc, 0x22, 0xbe, 0x85, 0xa3, 0x23, 0xa8, 0x52, 0xdf, 0x89, 0x6e, 0x42, 0xbe, 0xa2, 0xaa, 0x92,
	0xba, 0x09, 0x6f, 0x88, 0xbb, 0xbb, 0x29, 0x0e, 0x7d, 0x0c, 0x7b, 0xa2, 0x3b, 0x89, 0x68, 0xdb,
	0x77, 0x47, 0x94, 0xeb, 0x3b, 0xb2, 0xcf, 0x3a, 0x88, 0x74, 0xd8, 0x59, 0xd0, 0x88, 0x79, 0x81,
	0xaf, 0x17, 0x0f, 0x95, 0xa3, 0x2d, 0xbc, 0x0c, 0x8d, 0x1a, 0x54, 0x37, 0x86, 0x6c, 0xfc, 0x08,
	0xb5, 0x9c, 0xbb, 0x31, 0x65, 0xf1, 0x8c, 0xa3, 0x4f, 0x60, 0x9b, 0x71, 0xc2, 0xe3, 0xe4, 0x82,
	0x2a, 0xad, 0xaa, 0xf4, 0xc7, 0x48, 0x42, 0xdd, 0xc0, 0xa5, 0x38, 0x4d, 0x8b, 0x47, 0xcd, 0x29,
	0x63, 0x64, 0xba, 0xdc, 0xb9, 0x65, 0x88, 0x1e, 0xc1, 0x4e, 0x94, 0x8e, 0x5b, 0x3d, 0x54, 0x8f,
	0x4a, 0xad, 0x52, 0xea, 0x31, 0x81, 0xe1, 0x65, 0xce, 0xb8, 0x86, 0xad, 0xe7, 0x94, 0xb8, 0x79,
	0xcd, 0xca, 0x9a, 0x66, 0xb1, 0x9d, 0xf4, 0x3a, 0xf4, 0x22, 0xca, 0xda, 0x5c, 0x3e, 0x64, 0x1b,
	0x67, 0xc0, 0xfa, 0xee, 0xaa, 0x1b, 0xbb, 0x2b, 0xcc, 0xe3, 0x7a, 0xec, 0xcd, 0xc8, 0xfb, 0x9e,
	0xca, 0xc5, 0x56, 0xf1, 0x2a, 0x36, 0xbe, 0x80, 0xed, 0x44, 0x0c, 0xfa, 0x10, 0xb6, 0x84, 0xa5,
	0xd2, 0x95, 0xde, 0x95, 0x3a, 0x85, 0x28, 0x2c, 0xe1, 0xcc, 0x00, 0x85, 0x9c, 0x01, 0x8c, 0x77,
	0x0a, 0xec, 0x62, 0xf2, 0x36, 0x6d, 0xf1, 0xbe, 0x97, 0xc2, 0xb2, 0x7d, 0xe1, 0x7f, 0xda, 0xab,
	0x79, 0x7f, 0xe9, 0xb0, 0xe3, 0xd2, 0x19, 0xe5, 0xd4, 0x95, 0xc2, 0x8b, 0x78, 0x19, 0x8a, 0x33,
	0xc5, 0x8c, 0x46, 0x17, 0x94, 0x13, 0xe9, 0x90, 0x32, 0x5e, 0xc5, 0xc6, 0x97, 0x50, 0xb2, 0x23,
	0xe2, 0x33, 0xe2, 0x48, 0xeb, 0x9e, 0x00, 0xac, 0xd6, 0x56, 0x8c, 0x52, 0x8c, 0x41, 0x4b, 0xde,
	0x1f, 0xb9, 0x91, 0xe7, 0x38, 0x86, 0x09, 0xb5, 0x5c, 0x83, 0xd4, 0x0d, 0x27, 0x62, 0x94, 0xe2,
	0xdf, 0xb2, 0xc7, 0xfd, 0x5b, 0x3d, 0x64, 0x1a, 0x2f, 0x69, 0xc7, 0x7f, 0x17, 0x00, 0x32, 0xb7,
	0xa0, 0x12, 0xec, 0x8c, 0xc6, 0xdd, 0xae, 0x39, 0x1a, 0x69, 0x77, 0xd0, 0x03, 0xd8, 0x4f, 0x83,
	0xcb, 0x81, 0x65, 0x5f, 0x8e, 0x87, 0xbd, 0xb6, 0x6d, 0xf6, 0x34, 0x05, 0xed, 0x43, 0xd5, 0xc4,
	0xd8, 0xc2, 0x97, 0x03, 0xeb, 0x12, 0x9b, 0xcf, 0xfa, 0xd6, 0x40, 0x03, 0x74, 0x0f, 0x6a, 0x09,
	0xd8, 0x69, 0xf7, 0x2e, 0xb1, 0xf9, 0xf5, 0xd8, 0x1c, 0xd9, 0x5a, 0x09, 0x69, 0x50, 0x4e, 0xe0,
	0xa1, 0x75, 0xde, 0xef, 0x7e, 0xa3, 0x95, 0xb3, 0xea, 0x8b, 0xfe, 0x33, 0xdc, 0xb6, 0x45, 0xf5,
	0x1e, 0xaa, 0xc1, 0x5e, 0xda, 0xd2, 0xb4, 0x5f, 0x5a, 0xf8, 0x4c, 0xab, 0xa0, 0x0a, 0x40, 0x02,
	0xb5, 0xc7, 0xf6, 0x73, 0xad, 0x9a, 0xd5, 0x3d, 0xb5, 0x70, 0xa7, 0xdf, 0xeb, 0x99, 0x03, 0x4d,
	0xcb, 0xea, 0xec, 0xfe, 0x85, 0x69, 0x8d, 0x6d, 0xad, 0x86, 0x10, 0x54, 0x12, 0xc8, 0x7a, 0x61,
	0xe2, 0x73, 0xab, 0xdd, 0xd3, 0xd0, 0x3a, 0xf6, 0xf4, 0xdc, 0x7a, 0xa9, 0xed, 0x67, 0xca, 0xce,
	0xad, 0xee, 0x99, 0xd9, 0xd3, 0x0e, 0xb2, 0x66, 0xed, 0x8e, 0x85, 0xc5, 0x51, 0xef, 0x65, 0xa7,
	0xea, 0x0f, 0x6c, 0x13, 0xe3, 0xf1, 0x50, 0xc0, 0xf7, 0x33, 0x78, 0x3c, 0x18, 0x8d, 0x87, 0xc3,
	0x84, 0xfd, 0x20, 0x6b, 0xd9, 0xc3, 0xfd, 0x17, 0x26, 0xd6, 0x74, 0x54, 0x86, 0x62, 0x5a, 0x6f,
	0x69, 0x1f, 0x64, 0x32, 0x64, 0xb7, 0x41, 0xfb, 0x5c, 0xab, 0xb7, 0x26, 0x50, 0xed, 0x11, 0x4e,
	0x26, 0x84, 0x51, 0xf1, 0x6e, 0xf1, 0x1c, 0x8a, 0x2c, 0xd8, 0x31, 0xaf, 0xa9, 0x13, 0x73, 0x8a,
	0x52, 0x13, 0x64, 0x93, 0xae, 0xdf, 0xdf, 0x44, 0x92, 0x91, 0x1a, 0xf5, 0x9f, 0x7e, 0xff, 0xf3,
	0x97, 0xc2, 0x41, 0xbd, 0xda, 0x5c, 0x3c, 0x69, 0xf2, 0x2c, 0x7d, 0xaa, 0x1c, 0x77, 0xfe, 0x52,
	0xde, 0xb5, 0x7f, 0x53, 0xd0, 0xb7, 0x50, 0xea, 0x06, 0x3e, 0xa3, 0x3e, 0x8b, 0x59, 0xaf, 0x63,
	0xf4, 0xd7, 0x42, 0x74, 0x7c, 0xc5, 0x79, 0xc8, 0x4e, 0x9b, 0xcd, 0xa9, 0xc7, 0xaf, 0xe2, 0x49,
	0xc3, 0x09, 0xe6, 0x4d, 0x67, 0x99, 0x77, 0x27, 0xf9, 0xff, 0xf5, 0x0a, 0x99, 0xd1, 0xeb, 0xaf,
	0xd8, 0xd5, 0xc2, 0x73, 0x05, 0xaf, 0xa5, 0x3e, 0x69, 0x9c, 0x1c, 0x17, 0x94, 0x42, 0x4b, 0x23,
	0x61, 0x38, 0xf3, 0x1c, 0xe9, 0xb5, 0xe6, 0x6b, 0x16, 0xf8, 0x2d, 0x3d, 0x8f, 0x04, 0x0e, 0xa7,
	0xfc, 0x31, 0xe3, 0x11, 0x25, 0xf3, 0xd3, 0x5b, 0xdc, 0xd3, 0xff, 0xe4, 0xc2, 0x3d, 0x2f, 0x68,
	0xac, 0x74, 0xad, 0x74, 0x74, 0x76, 0xbb, 0xee, 0x64, 0x28, 0xbe, 0x3c, 0xd8, 0x50, 0x79, 0x55,
	0x4b, 0x3f, 0x6f, 0x9a, 0xab, 0xcf, 0x9c, 0x5f, 0x0b, 0x6a, 0xb7, 0xd7, 0x99, 0x6c, 0xcb, 0x8f,
	0x93, 0xcf, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x34, 0x44, 0xca, 0x34, 0x00, 0x09, 0x00, 0x00,
}
