//
// Copyright (c) 2025 Karagatan LLC.
// SPDX-License-Identifier: BUSL-1.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: cdb.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeType int32

const (
	ChangeType_WATCH_SET    ChangeType = 0 // key created or updated
	ChangeType_WATCH_DELETE ChangeType = 1 // key removed (or reclaimed after expiry)
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "WATCH_SET",
		1: "WATCH_DELETE",
	}
	ChangeType_value = map[string]int32{
		"WATCH_SET":    0,
		"WATCH_DELETE": 1,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_cdb_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_cdb_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{0}
}

type RangeType int32

const (
	RangeType_LESS_OR_EQUAL RangeType = 0
)

// Enum value maps for RangeType.
var (
	RangeType_name = map[int32]string{
		0: "LESS_OR_EQUAL",
	}
	RangeType_value = map[string]int32{
		"LESS_OR_EQUAL": 0,
	}
)

func (x RangeType) Enum() *RangeType {
	p := new(RangeType)
	*p = x
	return p
}

func (x RangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_cdb_proto_enumTypes[1].Descriptor()
}

func (RangeType) Type() protoreflect.EnumType {
	return &file_cdb_proto_enumTypes[1]
}

func (x RangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeType.Descriptor instead.
func (RangeType) EnumDescriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{1}
}

// Java compatible
type TimeUUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MostSigBits   int64                  `protobuf:"varint,1,opt,name=mostSigBits,proto3" json:"mostSigBits,omitempty"`
	LeastSigBits  int64                  `protobuf:"varint,2,opt,name=leastSigBits,proto3" json:"leastSigBits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeUUID) Reset() {
	*x = TimeUUID{}
	mi := &file_cdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeUUID) ProtoMessage() {}

func (x *TimeUUID) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeUUID.ProtoReflect.Descriptor instead.
func (*TimeUUID) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{0}
}

func (x *TimeUUID) GetMostSigBits() int64 {
	if x != nil {
		return x.MostSigBits
	}
	return 0
}

func (x *TimeUUID) GetLeastSigBits() int64 {
	if x != nil {
		return x.LeastSigBits
	}
	return 0
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MajorKey      []byte                 `protobuf:"bytes,1,opt,name=majorKey,proto3" json:"majorKey,omitempty"` // used as a partition key, good candidate is accountId, if empty - data replicated in all partitions
	RegionName    []byte                 `protobuf:"bytes,2,opt,name=regionName,proto3" json:"regionName,omitempty"`
	MinorKey      []byte                 `protobuf:"bytes,3,opt,name=minorKey,proto3" json:"minorKey,omitempty"`   // used as a record key in the partition
	Timestamp     *TimeUUID              `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // timestamp in TimeUUID if present
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_cdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetMajorKey() []byte {
	if x != nil {
		return x.MajorKey
	}
	return nil
}

func (x *Key) GetRegionName() []byte {
	if x != nil {
		return x.RegionName
	}
	return nil
}

func (x *Key) GetMinorKey() []byte {
	if x != nil {
		return x.MinorKey
	}
	return nil
}

func (x *Key) GetTimestamp() *TimeUUID {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type KeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HeadOnly      bool                   `protobuf:"varint,2,opt,name=headOnly,proto3" json:"headOnly,omitempty"`
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // SLA of the operation if not 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRequest) Reset() {
	*x = KeyRequest{}
	mi := &file_cdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRequest) ProtoMessage() {}

func (x *KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRequest.ProtoReflect.Descriptor instead.
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{2}
}

func (x *KeyRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyRequest) GetHeadOnly() bool {
	if x != nil {
		return x.HeadOnly
	}
	return false
}

func (x *KeyRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      int32                  `protobuf:"varint,3,opt,name=metadata,proto3" json:"metadata,omitempty"`     // for user 8 bits only, 9 bit deletedBit
	TtlSeconds    int64                  `protobuf:"varint,4,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"` // client input: relative TTL in seconds, 0 means no TTL
	CompareAndSet bool                   `protobuf:"varint,6,opt,name=compareAndSet,proto3" json:"compareAndSet,omitempty"`
	Version       uint64                 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"` // if 0 then putIfAbsent
	Timeout       int32                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"` // SLA of the operation if not 0
	// Absolute expiry (unix seconds) computed once on the leader from ttlSeconds
	// before the write enters the raft log, so every replica stores the same
	// expiry. Clients leave it 0 and set ttlSeconds; the server fills it in.
	ExpiresAt     int64 `protobuf:"varint,9,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_cdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{3}
}

func (x *RecordRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RecordRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RecordRequest) GetMetadata() int32 {
	if x != nil {
		return x.Metadata
	}
	return 0
}

func (x *RecordRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *RecordRequest) GetCompareAndSet() bool {
	if x != nil {
		return x.CompareAndSet
	}
	return false
}

func (x *RecordRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RecordRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *RecordRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type IncrementRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Key        *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Initial    int64                  `protobuf:"varint,2,opt,name=initial,proto3" json:"initial,omitempty"`       // counter start value when the key is absent
	Delta      int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`           // amount to add (may be negative)
	TtlSeconds int64                  `protobuf:"varint,4,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"` // client input: relative TTL in seconds, 0 means no TTL
	Timeout    int32                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`       // SLA of the operation if not 0
	// Absolute expiry (unix seconds) computed once on the leader; see RecordRequest.
	ExpiresAt     int64 `protobuf:"varint,6,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementRequest) Reset() {
	*x = IncrementRequest{}
	mi := &file_cdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementRequest) ProtoMessage() {}

func (x *IncrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementRequest.ProtoReflect.Descriptor instead.
func (*IncrementRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{4}
}

func (x *IncrementRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *IncrementRequest) GetInitial() int64 {
	if x != nil {
		return x.Initial
	}
	return 0
}

func (x *IncrementRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *IncrementRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *IncrementRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *IncrementRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type IncrementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Previous      int64                  `protobuf:"varint,1,opt,name=previous,proto3" json:"previous,omitempty"` // counter value before delta was applied
	Current       int64                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`   // counter value after delta was applied
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`   // envelope version (raft log index on the replicated path)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementResponse) Reset() {
	*x = IncrementResponse{}
	mi := &file_cdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementResponse) ProtoMessage() {}

func (x *IncrementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementResponse.ProtoReflect.Descriptor instead.
func (*IncrementResponse) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{5}
}

func (x *IncrementResponse) GetPrevious() int64 {
	if x != nil {
		return x.Previous
	}
	return 0
}

func (x *IncrementResponse) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *IncrementResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*RecordRequest       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`  // written all-or-nothing in one engine txn
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // SLA of the operation if not 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_cdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{6}
}

func (x *BatchRequest) GetRecords() []*RecordRequest {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *BatchRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// Internal raft command (no RPC): the leader discovers expired entries by a
// wall-clock scan and proposes their reclamation; the FSM deletes each key only
// if its stored envelope version still matches, so the removal is deterministic
// across replicas (never re-evaluating wall-clock expiry at apply time).
type ReclaimEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryKey      []byte                 `protobuf:"bytes,1,opt,name=entryKey,proto3" json:"entryKey,omitempty"` // encoded storage key observed as expired
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`  // envelope version the leader saw; delete only if unchanged
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReclaimEntry) Reset() {
	*x = ReclaimEntry{}
	mi := &file_cdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReclaimEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReclaimEntry) ProtoMessage() {}

func (x *ReclaimEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReclaimEntry.ProtoReflect.Descriptor instead.
func (*ReclaimEntry) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{7}
}

func (x *ReclaimEntry) GetEntryKey() []byte {
	if x != nil {
		return x.EntryKey
	}
	return nil
}

func (x *ReclaimEntry) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReclaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ReclaimEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReclaimRequest) Reset() {
	*x = ReclaimRequest{}
	mi := &file_cdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReclaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReclaimRequest) ProtoMessage() {}

func (x *ReclaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReclaimRequest.ProtoReflect.Descriptor instead.
func (*ReclaimRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{8}
}

func (x *ReclaimRequest) GetEntries() []*ReclaimEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *Key                   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`    // watch keys under this prefix; empty prefix watches everything
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // SLA of the operation if not 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_cdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{9}
}

func (x *WatchRequest) GetPrefix() *Key {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *WatchRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`      // empty for WATCH_DELETE
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // envelope version (raft log index) of the change
	Type          ChangeType             `protobuf:"varint,4,opt,name=type,proto3,enum=cdb.ChangeType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_cdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{10}
}

func (x *WatchEvent) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WatchEvent) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WatchEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WatchEvent) GetType() ChangeType {
	if x != nil {
		return x.Type
	}
	return ChangeType_WATCH_SET
}

type RangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HeadOnly      bool                   `protobuf:"varint,2,opt,name=headOnly,proto3" json:"headOnly,omitempty"`
	Type          RangeType              `protobuf:"varint,4,opt,name=type,proto3,enum=cdb.RangeType" json:"type,omitempty"`
	NumRecords    int32                  `protobuf:"varint,5,opt,name=numRecords,proto3" json:"numRecords,omitempty"`
	Timeout       int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"` // SLA of the operation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_cdb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{11}
}

func (x *RangeRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RangeRequest) GetHeadOnly() bool {
	if x != nil {
		return x.HeadOnly
	}
	return false
}

func (x *RangeRequest) GetType() RangeType {
	if x != nil {
		return x.Type
	}
	return RangeType_LESS_OR_EQUAL
}

func (x *RangeRequest) GetNumRecords() int32 {
	if x != nil {
		return x.NumRecords
	}
	return 0
}

func (x *RangeRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeadOnly      bool                   `protobuf:"varint,1,opt,name=headOnly,proto3" json:"headOnly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_cdb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{12}
}

func (x *ScanRequest) GetHeadOnly() bool {
	if x != nil {
		return x.HeadOnly
	}
	return false
}

type EnumerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *Key                   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`    // region/prefix to scan; empty scans everything
	Ordered       bool                   `protobuf:"varint,2,opt,name=ordered,proto3" json:"ordered,omitempty"` // server sorts results by the decoded minor key (lexical)
	Reverse       bool                   `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse,omitempty"` // with ordered, stream in descending order
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // SLA of the operation if not 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateRequest) Reset() {
	*x = EnumerateRequest{}
	mi := &file_cdb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateRequest) ProtoMessage() {}

func (x *EnumerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateRequest.ProtoReflect.Descriptor instead.
func (*EnumerateRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{13}
}

func (x *EnumerateRequest) GetPrefix() *Key {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *EnumerateRequest) GetOrdered() bool {
	if x != nil {
		return x.Ordered
	}
	return false
}

func (x *EnumerateRequest) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

func (x *EnumerateRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_cdb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{14}
}

func (x *Status) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type Head struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ExpiresAt     uint64                 `protobuf:"varint,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	DiskSize      int64                  `protobuf:"varint,3,opt,name=diskSize,proto3" json:"diskSize,omitempty"`
	Metadata      int32                  `protobuf:"varint,4,opt,name=metadata,proto3" json:"metadata,omitempty"` // for user 8 bits only, 9 bit deletedBit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Head) Reset() {
	*x = Head{}
	mi := &file_cdb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{15}
}

func (x *Head) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Head) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Head) GetDiskSize() int64 {
	if x != nil {
		return x.DiskSize
	}
	return 0
}

func (x *Head) GetMetadata() int32 {
	if x != nil {
		return x.Metadata
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Head          *Head                  `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"` // if exists, then record was found
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_cdb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{16}
}

func (x *Record) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Record) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        []*Record              `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_cdb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{17}
}

func (x *Block) GetRecord() []*Record {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_cdb_proto protoreflect.FileDescriptor

const file_cdb_proto_rawDesc = "" +
	"\n" +
	"\tcdb.proto\x12\x03cdb\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"P\n" +
	"\bTimeUUID\x12 \n" +
	"\vmostSigBits\x18\x01 \x01(\x03R\vmostSigBits\x12\"\n" +
	"\fleastSigBits\x18\x02 \x01(\x03R\fleastSigBits\"\x8a\x01\n" +
	"\x03Key\x12\x1a\n" +
	"\bmajorKey\x18\x01 \x01(\fR\bmajorKey\x12\x1e\n" +
	"\n" +
	"regionName\x18\x02 \x01(\fR\n" +
	"regionName\x12\x1a\n" +
	"\bminorKey\x18\x03 \x01(\fR\bminorKey\x12+\n" +
	"\ttimestamp\x18\x04 \x01(\v2\r.cdb.TimeUUIDR\ttimestamp\"^\n" +
	"\n" +
	"KeyRequest\x12\x1a\n" +
	"\x03key\x18\x01 \x01(\v2\b.cdb.KeyR\x03key\x12\x1a\n" +
	"\bheadOnly\x18\x02 \x01(\bR\bheadOnly\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\"\xf5\x01\n" +
	"\rRecordRequest\x12\x1a\n" +
	"\x03key\x18\x01 \x01(\v2\b.cdb.KeyR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\x05R\bmetadata\x12\x1e\n" +
	"\n" +
	"ttlSeconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\x12$\n" +
	"\rcompareAndSet\x18\x06 \x01(\bR\rcompareAndSet\x12\x18\n" +
	"\aversion\x18\a \x01(\x04R\aversion\x12\x18\n" +
	"\atimeout\x18\b \x01(\x05R\atimeout\x12\x1c\n" +
	"\texpiresAt\x18\t \x01(\x03R\texpiresAt\"\xb6\x01\n" +
	"\x10IncrementRequest\x12\x1a\n" +
	"\x03key\x18\x01 \x01(\v2\b.cdb.KeyR\x03key\x12\x18\n" +
	"\ainitial\x18\x02 \x01(\x03R\ainitial\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x1e\n" +
	"\n" +
	"ttlSeconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\x12\x1c\n" +
	"\texpiresAt\x18\x06 \x01(\x03R\texpiresAt\"c\n" +
	"\x11IncrementResponse\x12\x1a\n" +
	"\bprevious\x18\x01 \x01(\x03R\bprevious\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x03R\acurrent\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"V\n" +
	"\fBatchRequest\x12,\n" +
	"\arecords\x18\x01 \x03(\v2\x12.cdb.RecordRequestR\arecords\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"D\n" +
	"\fReclaimEntry\x12\x1a\n" +
	"\bentryKey\x18\x01 \x01(\fR\bentryKey\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"=\n" +
	"\x0eReclaimRequest\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.cdb.ReclaimEntryR\aentries\"J\n" +
	"\fWatchRequest\x12 \n" +
	"\x06prefix\x18\x01 \x01(\v2\b.cdb.KeyR\x06prefix\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"}\n" +
	"\n" +
	"WatchEvent\x12\x1a\n" +
	"\x03key\x18\x01 \x01(\v2\b.cdb.KeyR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12#\n" +
	"\x04type\x18\x04 \x01(\x0e2\x0f.cdb.ChangeTypeR\x04type\"\xa4\x01\n" +
	"\fRangeRequest\x12\x1a\n" +
	"\x03key\x18\x01 \x01(\v2\b.cdb.KeyR\x03key\x12\x1a\n" +
	"\bheadOnly\x18\x02 \x01(\bR\bheadOnly\x12\"\n" +
	"\x04type\x18\x04 \x01(\x0e2\x0e.cdb.RangeTypeR\x04type\x12\x1e\n" +
	"\n" +
	"numRecords\x18\x05 \x01(\x05R\n" +
	"numRecords\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\")\n" +
	"\vScanRequest\x12\x1a\n" +
	"\bheadOnly\x18\x01 \x01(\bR\bheadOnly\"\x82\x01\n" +
	"\x10EnumerateRequest\x12 \n" +
	"\x06prefix\x18\x01 \x01(\v2\b.cdb.KeyR\x06prefix\x12\x18\n" +
	"\aordered\x18\x02 \x01(\bR\aordered\x12\x18\n" +
	"\areverse\x18\x03 \x01(\bR\areverse\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\"\"\n" +
	"\x06Status\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"v\n" +
	"\x04Head\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1c\n" +
	"\texpiresAt\x18\x02 \x01(\x04R\texpiresAt\x12\x1a\n" +
	"\bdiskSize\x18\x03 \x01(\x03R\bdiskSize\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\x05R\bmetadata\"Y\n" +
	"\x06Record\x12\x1a\n" +
	"\x03key\x18\x01 \x01(\v2\b.cdb.KeyR\x03key\x12\x1d\n" +
	"\x04head\x18\x02 \x01(\v2\t.cdb.HeadR\x04head\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\",\n" +
	"\x05Block\x12#\n" +
	"\x06record\x18\x01 \x03(\v2\v.cdb.RecordR\x06record*-\n" +
	"\n" +
	"ChangeType\x12\r\n" +
	"\tWATCH_SET\x10\x00\x12\x10\n" +
	"\fWATCH_DELETE\x10\x01*\x1e\n" +
	"\tRangeType\x12\x11\n" +
	"\rLESS_OR_EQUAL\x10\x002\xd4\x06\n" +
	"\x0fKeyValueService\x124\n" +
	"\x03Get\x12\x0f.cdb.KeyRequest\x1a\v.cdb.Record\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/v1/get\x12@\n" +
	"\tGetRecent\x12\x0f.cdb.KeyRequest\x1a\v.cdb.Record\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/getrecent\x12?\n" +
	"\bGetRange\x12\x11.cdb.RangeRequest\x1a\n" +
	".cdb.Block\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/getrange\x12;\n" +
	"\x06GetRow\x12\x0f.cdb.KeyRequest\x1a\n" +
	".cdb.Block\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/getrow0\x01\x12A\n" +
	"\tGetRegion\x12\x0f.cdb.KeyRequest\x1a\n" +
	".cdb.Block\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/getregion0\x01\x12?\n" +
	"\bGetSpace\x12\x0f.cdb.KeyRequest\x1a\n" +
	".cdb.Block\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/getspace0\x01\x128\n" +
	"\x04Scan\x12\x10.cdb.ScanRequest\x1a\n" +
	".cdb.Block\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/scan0\x01\x12>\n" +
	"\x05Touch\x12\x12.cdb.RecordRequest\x1a\v.cdb.Status\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\t/v1/touch\x12:\n" +
	"\x03Put\x12\x12.cdb.RecordRequest\x1a\v.cdb.Status\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\x1a\a/v1/put\x12:\n" +
	"\x06Remove\x12\x0f.cdb.KeyRequest\x1a\v.cdb.Status\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/v1/remove\x12T\n" +
	"\tIncrement\x12\x15.cdb.IncrementRequest\x1a\x16.cdb.IncrementResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/increment\x12=\n" +
	"\x05Batch\x12\x11.cdb.BatchRequest\x1a\v.cdb.Status\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/batch\x12@\n" +
	"\x05Watch\x12\x11.cdb.WatchRequest\x1a\x0f.cdb.WatchEvent\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/watch0\x01B\x8b\x02\x92A\xbd\x01\x12_\n" +
	"\vConsensusDB\"K\n" +
	"\vConsensusDB\x12&https://github.com/arpabet/consensusdb\x1a\x14alex@consensusdb.com2\x031.0*\x02\x01\x022\x10application/json2\x18application/octet-stream:\x10application/json:\x18application/octet-stream\n" +
	"\x0fcom.consensusdbB\tCdbProtosP\x01Z$go.arpabet.com/consensusdb/pkg/pb;pb\xa2\x02\x03CDBb\x06proto3"

var (
	file_cdb_proto_rawDescOnce sync.Once
	file_cdb_proto_rawDescData []byte
)

func file_cdb_proto_rawDescGZIP() []byte {
	file_cdb_proto_rawDescOnce.Do(func() {
		file_cdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cdb_proto_rawDesc), len(file_cdb_proto_rawDesc)))
	})
	return file_cdb_proto_rawDescData
}

var file_cdb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cdb_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_cdb_proto_goTypes = []any{
	(ChangeType)(0),           // 0: cdb.ChangeType
	(RangeType)(0),            // 1: cdb.RangeType
	(*TimeUUID)(nil),          // 2: cdb.TimeUUID
	(*Key)(nil),               // 3: cdb.Key
	(*KeyRequest)(nil),        // 4: cdb.KeyRequest
	(*RecordRequest)(nil),     // 5: cdb.RecordRequest
	(*IncrementRequest)(nil),  // 6: cdb.IncrementRequest
	(*IncrementResponse)(nil), // 7: cdb.IncrementResponse
	(*BatchRequest)(nil),      // 8: cdb.BatchRequest
	(*ReclaimEntry)(nil),      // 9: cdb.ReclaimEntry
	(*ReclaimRequest)(nil),    // 10: cdb.ReclaimRequest
	(*WatchRequest)(nil),      // 11: cdb.WatchRequest
	(*WatchEvent)(nil),        // 12: cdb.WatchEvent
	(*RangeRequest)(nil),      // 13: cdb.RangeRequest
	(*ScanRequest)(nil),       // 14: cdb.ScanRequest
	(*EnumerateRequest)(nil),  // 15: cdb.EnumerateRequest
	(*Status)(nil),            // 16: cdb.Status
	(*Head)(nil),              // 17: cdb.Head
	(*Record)(nil),            // 18: cdb.Record
	(*Block)(nil),             // 19: cdb.Block
}
var file_cdb_proto_depIdxs = []int32{
	2,  // 0: cdb.Key.timestamp:type_name -> cdb.TimeUUID
	3,  // 1: cdb.KeyRequest.key:type_name -> cdb.Key
	3,  // 2: cdb.RecordRequest.key:type_name -> cdb.Key
	3,  // 3: cdb.IncrementRequest.key:type_name -> cdb.Key
	5,  // 4: cdb.BatchRequest.records:type_name -> cdb.RecordRequest
	9,  // 5: cdb.ReclaimRequest.entries:type_name -> cdb.ReclaimEntry
	3,  // 6: cdb.WatchRequest.prefix:type_name -> cdb.Key
	3,  // 7: cdb.WatchEvent.key:type_name -> cdb.Key
	0,  // 8: cdb.WatchEvent.type:type_name -> cdb.ChangeType
	3,  // 9: cdb.RangeRequest.key:type_name -> cdb.Key
	1,  // 10: cdb.RangeRequest.type:type_name -> cdb.RangeType
	3,  // 11: cdb.EnumerateRequest.prefix:type_name -> cdb.Key
	3,  // 12: cdb.Record.key:type_name -> cdb.Key
	17, // 13: cdb.Record.head:type_name -> cdb.Head
	18, // 14: cdb.Block.record:type_name -> cdb.Record
	4,  // 15: cdb.KeyValueService.Get:input_type -> cdb.KeyRequest
	4,  // 16: cdb.KeyValueService.GetRecent:input_type -> cdb.KeyRequest
	13, // 17: cdb.KeyValueService.GetRange:input_type -> cdb.RangeRequest
	4,  // 18: cdb.KeyValueService.GetRow:input_type -> cdb.KeyRequest
	4,  // 19: cdb.KeyValueService.GetRegion:input_type -> cdb.KeyRequest
	4,  // 20: cdb.KeyValueService.GetSpace:input_type -> cdb.KeyRequest
	14, // 21: cdb.KeyValueService.Scan:input_type -> cdb.ScanRequest
	5,  // 22: cdb.KeyValueService.Touch:input_type -> cdb.RecordRequest
	5,  // 23: cdb.KeyValueService.Put:input_type -> cdb.RecordRequest
	4,  // 24: cdb.KeyValueService.Remove:input_type -> cdb.KeyRequest
	6,  // 25: cdb.KeyValueService.Increment:input_type -> cdb.IncrementRequest
	8,  // 26: cdb.KeyValueService.Batch:input_type -> cdb.BatchRequest
	11, // 27: cdb.KeyValueService.Watch:input_type -> cdb.WatchRequest
	18, // 28: cdb.KeyValueService.Get:output_type -> cdb.Record
	18, // 29: cdb.KeyValueService.GetRecent:output_type -> cdb.Record
	19, // 30: cdb.KeyValueService.GetRange:output_type -> cdb.Block
	19, // 31: cdb.KeyValueService.GetRow:output_type -> cdb.Block
	19, // 32: cdb.KeyValueService.GetRegion:output_type -> cdb.Block
	19, // 33: cdb.KeyValueService.GetSpace:output_type -> cdb.Block
	19, // 34: cdb.KeyValueService.Scan:output_type -> cdb.Block
	16, // 35: cdb.KeyValueService.Touch:output_type -> cdb.Status
	16, // 36: cdb.KeyValueService.Put:output_type -> cdb.Status
	16, // 37: cdb.KeyValueService.Remove:output_type -> cdb.Status
	7,  // 38: cdb.KeyValueService.Increment:output_type -> cdb.IncrementResponse
	16, // 39: cdb.KeyValueService.Batch:output_type -> cdb.Status
	12, // 40: cdb.KeyValueService.Watch:output_type -> cdb.WatchEvent
	28, // [28:41] is the sub-list for method output_type
	15, // [15:28] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cdb_proto_init() }
func file_cdb_proto_init() {
	if File_cdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cdb_proto_rawDesc), len(file_cdb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cdb_proto_goTypes,
		DependencyIndexes: file_cdb_proto_depIdxs,
		EnumInfos:         file_cdb_proto_enumTypes,
		MessageInfos:      file_cdb_proto_msgTypes,
	}.Build()
	File_cdb_proto = out.File
	file_cdb_proto_goTypes = nil
	file_cdb_proto_depIdxs = nil
}
