//
//
// Copyright 2020-present Arpabet Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: cdb.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RangeType int32

const (
	RangeType_LESS_OR_EQUAL RangeType = 0
)

// Enum value maps for RangeType.
var (
	RangeType_name = map[int32]string{
		0: "LESS_OR_EQUAL",
	}
	RangeType_value = map[string]int32{
		"LESS_OR_EQUAL": 0,
	}
)

func (x RangeType) Enum() *RangeType {
	p := new(RangeType)
	*p = x
	return p
}

func (x RangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_cdb_proto_enumTypes[0].Descriptor()
}

func (RangeType) Type() protoreflect.EnumType {
	return &file_cdb_proto_enumTypes[0]
}

func (x RangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeType.Descriptor instead.
func (RangeType) EnumDescriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{0}
}

// Java compatible
type TimeUUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MostSigBits  int64 `protobuf:"varint,1,opt,name=mostSigBits,proto3" json:"mostSigBits,omitempty"`
	LeastSigBits int64 `protobuf:"varint,2,opt,name=leastSigBits,proto3" json:"leastSigBits,omitempty"`
}

func (x *TimeUUID) Reset() {
	*x = TimeUUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeUUID) ProtoMessage() {}

func (x *TimeUUID) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeUUID.ProtoReflect.Descriptor instead.
func (*TimeUUID) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{0}
}

func (x *TimeUUID) GetMostSigBits() int64 {
	if x != nil {
		return x.MostSigBits
	}
	return 0
}

func (x *TimeUUID) GetLeastSigBits() int64 {
	if x != nil {
		return x.LeastSigBits
	}
	return 0
}

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MajorKey   []byte    `protobuf:"bytes,1,opt,name=majorKey,proto3" json:"majorKey,omitempty"` // used as a partition key, good candidate is accountId, if empty - data replicated in all partitions
	RegionName []byte    `protobuf:"bytes,2,opt,name=regionName,proto3" json:"regionName,omitempty"`
	MinorKey   []byte    `protobuf:"bytes,3,opt,name=minorKey,proto3" json:"minorKey,omitempty"`   // used as a record key in the partition
	Timestamp  *TimeUUID `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // timestamp in TimeUUID if present
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetMajorKey() []byte {
	if x != nil {
		return x.MajorKey
	}
	return nil
}

func (x *Key) GetRegionName() []byte {
	if x != nil {
		return x.RegionName
	}
	return nil
}

func (x *Key) GetMinorKey() []byte {
	if x != nil {
		return x.MinorKey
	}
	return nil
}

func (x *Key) GetTimestamp() *TimeUUID {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type KeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      *Key  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HeadOnly bool  `protobuf:"varint,2,opt,name=headOnly,proto3" json:"headOnly,omitempty"`
	Timeout  int32 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // SLA of the operation if not 0
}

func (x *KeyRequest) Reset() {
	*x = KeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRequest) ProtoMessage() {}

func (x *KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRequest.ProtoReflect.Descriptor instead.
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{2}
}

func (x *KeyRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyRequest) GetHeadOnly() bool {
	if x != nil {
		return x.HeadOnly
	}
	return false
}

func (x *KeyRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type RecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key           *Key   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      int32  `protobuf:"varint,3,opt,name=metadata,proto3" json:"metadata,omitempty"`     // for user 8 bits only, 9 bit deletedBit
	TtlSeconds    int64  `protobuf:"varint,4,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"` // add TTL in seconds if not 0, zero means no TTL
	CompareAndSet bool   `protobuf:"varint,6,opt,name=compareAndSet,proto3" json:"compareAndSet,omitempty"`
	Version       uint64 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"` // if 0 then putIfAbsent
	Timeout       int32  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"` // SLA of the operation if not 0
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{3}
}

func (x *RecordRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RecordRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RecordRequest) GetMetadata() int32 {
	if x != nil {
		return x.Metadata
	}
	return 0
}

func (x *RecordRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *RecordRequest) GetCompareAndSet() bool {
	if x != nil {
		return x.CompareAndSet
	}
	return false
}

func (x *RecordRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RecordRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type RangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        *Key      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HeadOnly   bool      `protobuf:"varint,2,opt,name=headOnly,proto3" json:"headOnly,omitempty"`
	Type       RangeType `protobuf:"varint,4,opt,name=type,proto3,enum=cdb.RangeType" json:"type,omitempty"`
	NumRecords int32     `protobuf:"varint,5,opt,name=numRecords,proto3" json:"numRecords,omitempty"`
	Timeout    int32     `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"` // SLA of the operation
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{4}
}

func (x *RangeRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RangeRequest) GetHeadOnly() bool {
	if x != nil {
		return x.HeadOnly
	}
	return false
}

func (x *RangeRequest) GetType() RangeType {
	if x != nil {
		return x.Type
	}
	return RangeType_LESS_OR_EQUAL
}

func (x *RangeRequest) GetNumRecords() int32 {
	if x != nil {
		return x.NumRecords
	}
	return 0
}

func (x *RangeRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type ScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadOnly bool `protobuf:"varint,1,opt,name=headOnly,proto3" json:"headOnly,omitempty"`
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{5}
}

func (x *ScanRequest) GetHeadOnly() bool {
	if x != nil {
		return x.HeadOnly
	}
	return false
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{6}
}

func (x *Status) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type Head struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ExpiresAt uint64 `protobuf:"varint,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	DiskSize  int64  `protobuf:"varint,3,opt,name=diskSize,proto3" json:"diskSize,omitempty"`
	Metadata  int32  `protobuf:"varint,4,opt,name=metadata,proto3" json:"metadata,omitempty"` // for user 8 bits only, 9 bit deletedBit
}

func (x *Head) Reset() {
	*x = Head{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{7}
}

func (x *Head) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Head) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Head) GetDiskSize() int64 {
	if x != nil {
		return x.DiskSize
	}
	return 0
}

func (x *Head) GetMetadata() int32 {
	if x != nil {
		return x.Metadata
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *Key   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Head  *Head  `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"` // if exists, then record was found
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{8}
}

func (x *Record) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Record) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record []*Record `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cdb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_cdb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_cdb_proto_rawDescGZIP(), []int{9}
}

func (x *Block) GetRecord() []*Record {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_cdb_proto protoreflect.FileDescriptor

var file_cdb_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x64, 0x62,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x73, 0x77, 0x61, 0x67, 0x67,
	0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x08,
	0x54, 0x69, 0x6d, 0x65, 0x55, 0x55, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x6f, 0x73, 0x74,
	0x53, 0x69, 0x67, 0x42, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6d,
	0x6f, 0x73, 0x74, 0x53, 0x69, 0x67, 0x42, 0x69, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x65,
	0x61, 0x73, 0x74, 0x53, 0x69, 0x67, 0x42, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x6c, 0x65, 0x61, 0x73, 0x74, 0x53, 0x69, 0x67, 0x42, 0x69, 0x74, 0x73, 0x22, 0x8a,
	0x01, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x4b,
	0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x2b,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x55, 0x49, 0x44,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5e, 0x0a, 0x0a, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x4b, 0x65, 0x79,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0xd7, 0x01, 0x0a, 0x0d,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x64, 0x62,
	0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x74, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x74, 0x74, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x0c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x22,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x63,
	0x64, 0x62, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x29, 0x0a, 0x0b,
	0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68,
	0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x22, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x76, 0x0a, 0x04, 0x48,
	0x65, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x59, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x64, 0x62,
	0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x04, 0x68, 0x65, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c,
	0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x23, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2a, 0x1e, 0x0a, 0x09,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x45, 0x53,
	0x53, 0x5f, 0x4f, 0x52, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x10, 0x00, 0x32, 0xfd, 0x04, 0x0a,
	0x0f, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x34, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x12, 0x07, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x12, 0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63,
	0x65, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x67,
	0x65, 0x74, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x11, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x76, 0x31,
	0x2f, 0x67, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x77, 0x12, 0x0f, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65,
	0x74, 0x72, 0x6f, 0x77, 0x30, 0x01, 0x12, 0x41, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65,
	0x74, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x30, 0x01, 0x12, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0f, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x76, 0x31, 0x2f,
	0x67, 0x65, 0x74, 0x73, 0x70, 0x61, 0x63, 0x65, 0x30, 0x01, 0x12, 0x38, 0x0a, 0x04, 0x53, 0x63,
	0x61, 0x6e, 0x12, 0x10, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x12, 0x08, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63,
	0x61, 0x6e, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x05, 0x54, 0x6f, 0x75, 0x63, 0x68, 0x12, 0x12, 0x2e,
	0x63, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0b, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x14,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x1a, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x6f, 0x75, 0x63,
	0x68, 0x3a, 0x01, 0x2a, 0x12, 0x3a, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x12, 0x2e, 0x63, 0x64,
	0x62, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0b, 0x2e, 0x63, 0x64, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x12, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0c, 0x1a, 0x07, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x74, 0x3a, 0x01, 0x2a,
	0x12, 0x3a, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x0f, 0x2e, 0x63, 0x64, 0x62,
	0x2e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x63, 0x64,
	0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c,
	0x2a, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0xf1, 0x01, 0x0a,
	0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x64, 0x62,
	0x42, 0x09, 0x43, 0x64, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x50, 0x01, 0x5a, 0x06, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x43, 0x44, 0x42, 0x92, 0x41, 0xc1, 0x01, 0x12,
	0x63, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x44, 0x42, 0x22, 0x4f,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x44, 0x42, 0x12, 0x2a, 0x68,
	0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2f, 0x63, 0x6f,
	0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x64, 0x62, 0x1a, 0x14, 0x61, 0x6c, 0x65, 0x78, 0x40,
	0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x32,
	0x03, 0x31, 0x2e, 0x30, 0x2a, 0x02, 0x01, 0x02, 0x32, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x32, 0x18, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6f, 0x63, 0x74, 0x65, 0x74, 0x2d, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x3a, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x18, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x6f, 0x63, 0x74, 0x65, 0x74, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cdb_proto_rawDescOnce sync.Once
	file_cdb_proto_rawDescData = file_cdb_proto_rawDesc
)

func file_cdb_proto_rawDescGZIP() []byte {
	file_cdb_proto_rawDescOnce.Do(func() {
		file_cdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_cdb_proto_rawDescData)
	})
	return file_cdb_proto_rawDescData
}

var file_cdb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cdb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cdb_proto_goTypes = []interface{}{
	(RangeType)(0),        // 0: cdb.RangeType
	(*TimeUUID)(nil),      // 1: cdb.TimeUUID
	(*Key)(nil),           // 2: cdb.Key
	(*KeyRequest)(nil),    // 3: cdb.KeyRequest
	(*RecordRequest)(nil), // 4: cdb.RecordRequest
	(*RangeRequest)(nil),  // 5: cdb.RangeRequest
	(*ScanRequest)(nil),   // 6: cdb.ScanRequest
	(*Status)(nil),        // 7: cdb.Status
	(*Head)(nil),          // 8: cdb.Head
	(*Record)(nil),        // 9: cdb.Record
	(*Block)(nil),         // 10: cdb.Block
}
var file_cdb_proto_depIdxs = []int32{
	1,  // 0: cdb.Key.timestamp:type_name -> cdb.TimeUUID
	2,  // 1: cdb.KeyRequest.key:type_name -> cdb.Key
	2,  // 2: cdb.RecordRequest.key:type_name -> cdb.Key
	2,  // 3: cdb.RangeRequest.key:type_name -> cdb.Key
	0,  // 4: cdb.RangeRequest.type:type_name -> cdb.RangeType
	2,  // 5: cdb.Record.key:type_name -> cdb.Key
	8,  // 6: cdb.Record.head:type_name -> cdb.Head
	9,  // 7: cdb.Block.record:type_name -> cdb.Record
	3,  // 8: cdb.KeyValueService.Get:input_type -> cdb.KeyRequest
	3,  // 9: cdb.KeyValueService.GetRecent:input_type -> cdb.KeyRequest
	5,  // 10: cdb.KeyValueService.GetRange:input_type -> cdb.RangeRequest
	3,  // 11: cdb.KeyValueService.GetRow:input_type -> cdb.KeyRequest
	3,  // 12: cdb.KeyValueService.GetRegion:input_type -> cdb.KeyRequest
	3,  // 13: cdb.KeyValueService.GetSpace:input_type -> cdb.KeyRequest
	6,  // 14: cdb.KeyValueService.Scan:input_type -> cdb.ScanRequest
	4,  // 15: cdb.KeyValueService.Touch:input_type -> cdb.RecordRequest
	4,  // 16: cdb.KeyValueService.Put:input_type -> cdb.RecordRequest
	3,  // 17: cdb.KeyValueService.Remove:input_type -> cdb.KeyRequest
	9,  // 18: cdb.KeyValueService.Get:output_type -> cdb.Record
	9,  // 19: cdb.KeyValueService.GetRecent:output_type -> cdb.Record
	10, // 20: cdb.KeyValueService.GetRange:output_type -> cdb.Block
	10, // 21: cdb.KeyValueService.GetRow:output_type -> cdb.Block
	10, // 22: cdb.KeyValueService.GetRegion:output_type -> cdb.Block
	10, // 23: cdb.KeyValueService.GetSpace:output_type -> cdb.Block
	10, // 24: cdb.KeyValueService.Scan:output_type -> cdb.Block
	7,  // 25: cdb.KeyValueService.Touch:output_type -> cdb.Status
	7,  // 26: cdb.KeyValueService.Put:output_type -> cdb.Status
	7,  // 27: cdb.KeyValueService.Remove:output_type -> cdb.Status
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cdb_proto_init() }
func file_cdb_proto_init() {
	if File_cdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeUUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Head); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cdb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cdb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cdb_proto_goTypes,
		DependencyIndexes: file_cdb_proto_depIdxs,
		EnumInfos:         file_cdb_proto_enumTypes,
		MessageInfos:      file_cdb_proto_msgTypes,
	}.Build()
	File_cdb_proto = out.File
	file_cdb_proto_rawDesc = nil
	file_cdb_proto_goTypes = nil
	file_cdb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KeyValueServiceClient is the client API for KeyValueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyValueServiceClient interface {
	//
	// Gets exact match entry
	//
	Get(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error)
	//
	// Gets early or equal timestamp entry
	//
	GetRecent(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error)
	//
	// Gets range of timestamps inside a row
	//
	GetRange(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*Block, error)
	//
	// Gets the whole raw of records with all available timestamps with latest versions
	//
	GetRow(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (KeyValueService_GetRowClient, error)
	//
	// Gets the whole region of records
	//
	GetRegion(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (KeyValueService_GetRegionClient, error)
	//
	// Gets the whole space of records associated with majorKey
	//
	GetSpace(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (KeyValueService_GetSpaceClient, error)
	//
	// Gets all records
	//
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (KeyValueService_ScanClient, error)
	//
	// Touches the record
	//
	Touch(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Status, error)
	//
	// Puts the record
	//
	Put(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Status, error)
	//
	// Remove the record
	//
	Remove(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Status, error)
}

type keyValueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValueServiceClient(cc grpc.ClientConnInterface) KeyValueServiceClient {
	return &keyValueServiceClient{cc}
}

func (c *keyValueServiceClient) Get(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/cdb.KeyValueService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) GetRecent(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/cdb.KeyValueService/GetRecent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) GetRange(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*Block, error) {
	out := new(Block)
	err := c.cc.Invoke(ctx, "/cdb.KeyValueService/GetRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) GetRow(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (KeyValueService_GetRowClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KeyValueService_serviceDesc.Streams[0], "/cdb.KeyValueService/GetRow", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyValueServiceGetRowClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KeyValueService_GetRowClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type keyValueServiceGetRowClient struct {
	grpc.ClientStream
}

func (x *keyValueServiceGetRowClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *keyValueServiceClient) GetRegion(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (KeyValueService_GetRegionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KeyValueService_serviceDesc.Streams[1], "/cdb.KeyValueService/GetRegion", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyValueServiceGetRegionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KeyValueService_GetRegionClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type keyValueServiceGetRegionClient struct {
	grpc.ClientStream
}

func (x *keyValueServiceGetRegionClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *keyValueServiceClient) GetSpace(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (KeyValueService_GetSpaceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KeyValueService_serviceDesc.Streams[2], "/cdb.KeyValueService/GetSpace", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyValueServiceGetSpaceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KeyValueService_GetSpaceClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type keyValueServiceGetSpaceClient struct {
	grpc.ClientStream
}

func (x *keyValueServiceGetSpaceClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *keyValueServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (KeyValueService_ScanClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KeyValueService_serviceDesc.Streams[3], "/cdb.KeyValueService/Scan", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyValueServiceScanClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KeyValueService_ScanClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type keyValueServiceScanClient struct {
	grpc.ClientStream
}

func (x *keyValueServiceScanClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *keyValueServiceClient) Touch(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/cdb.KeyValueService/Touch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) Put(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/cdb.KeyValueService/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) Remove(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/cdb.KeyValueService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValueServiceServer is the server API for KeyValueService service.
type KeyValueServiceServer interface {
	//
	// Gets exact match entry
	//
	Get(context.Context, *KeyRequest) (*Record, error)
	//
	// Gets early or equal timestamp entry
	//
	GetRecent(context.Context, *KeyRequest) (*Record, error)
	//
	// Gets range of timestamps inside a row
	//
	GetRange(context.Context, *RangeRequest) (*Block, error)
	//
	// Gets the whole raw of records with all available timestamps with latest versions
	//
	GetRow(*KeyRequest, KeyValueService_GetRowServer) error
	//
	// Gets the whole region of records
	//
	GetRegion(*KeyRequest, KeyValueService_GetRegionServer) error
	//
	// Gets the whole space of records associated with majorKey
	//
	GetSpace(*KeyRequest, KeyValueService_GetSpaceServer) error
	//
	// Gets all records
	//
	Scan(*ScanRequest, KeyValueService_ScanServer) error
	//
	// Touches the record
	//
	Touch(context.Context, *RecordRequest) (*Status, error)
	//
	// Puts the record
	//
	Put(context.Context, *RecordRequest) (*Status, error)
	//
	// Remove the record
	//
	Remove(context.Context, *KeyRequest) (*Status, error)
}

// UnimplementedKeyValueServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKeyValueServiceServer struct {
}

func (*UnimplementedKeyValueServiceServer) Get(context.Context, *KeyRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedKeyValueServiceServer) GetRecent(context.Context, *KeyRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecent not implemented")
}
func (*UnimplementedKeyValueServiceServer) GetRange(context.Context, *RangeRequest) (*Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRange not implemented")
}
func (*UnimplementedKeyValueServiceServer) GetRow(*KeyRequest, KeyValueService_GetRowServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRow not implemented")
}
func (*UnimplementedKeyValueServiceServer) GetRegion(*KeyRequest, KeyValueService_GetRegionServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRegion not implemented")
}
func (*UnimplementedKeyValueServiceServer) GetSpace(*KeyRequest, KeyValueService_GetSpaceServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSpace not implemented")
}
func (*UnimplementedKeyValueServiceServer) Scan(*ScanRequest, KeyValueService_ScanServer) error {
	return status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (*UnimplementedKeyValueServiceServer) Touch(context.Context, *RecordRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Touch not implemented")
}
func (*UnimplementedKeyValueServiceServer) Put(context.Context, *RecordRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedKeyValueServiceServer) Remove(context.Context, *KeyRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterKeyValueServiceServer(s *grpc.Server, srv KeyValueServiceServer) {
	s.RegisterService(&_KeyValueService_serviceDesc, srv)
}

func _KeyValueService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdb.KeyValueService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).Get(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_GetRecent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).GetRecent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdb.KeyValueService/GetRecent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).GetRecent(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_GetRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).GetRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdb.KeyValueService/GetRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).GetRange(ctx, req.(*RangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_GetRow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueServiceServer).GetRow(m, &keyValueServiceGetRowServer{stream})
}

type KeyValueService_GetRowServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type keyValueServiceGetRowServer struct {
	grpc.ServerStream
}

func (x *keyValueServiceGetRowServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

func _KeyValueService_GetRegion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueServiceServer).GetRegion(m, &keyValueServiceGetRegionServer{stream})
}

type KeyValueService_GetRegionServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type keyValueServiceGetRegionServer struct {
	grpc.ServerStream
}

func (x *keyValueServiceGetRegionServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

func _KeyValueService_GetSpace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueServiceServer).GetSpace(m, &keyValueServiceGetSpaceServer{stream})
}

type KeyValueService_GetSpaceServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type keyValueServiceGetSpaceServer struct {
	grpc.ServerStream
}

func (x *keyValueServiceGetSpaceServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

func _KeyValueService_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueServiceServer).Scan(m, &keyValueServiceScanServer{stream})
}

type KeyValueService_ScanServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type keyValueServiceScanServer struct {
	grpc.ServerStream
}

func (x *keyValueServiceScanServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

func _KeyValueService_Touch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).Touch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdb.KeyValueService/Touch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).Touch(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdb.KeyValueService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).Put(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdb.KeyValueService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).Remove(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyValueService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cdb.KeyValueService",
	HandlerType: (*KeyValueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KeyValueService_Get_Handler,
		},
		{
			MethodName: "GetRecent",
			Handler:    _KeyValueService_GetRecent_Handler,
		},
		{
			MethodName: "GetRange",
			Handler:    _KeyValueService_GetRange_Handler,
		},
		{
			MethodName: "Touch",
			Handler:    _KeyValueService_Touch_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _KeyValueService_Put_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _KeyValueService_Remove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRow",
			Handler:       _KeyValueService_GetRow_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetRegion",
			Handler:       _KeyValueService_GetRegion_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSpace",
			Handler:       _KeyValueService_GetSpace_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Scan",
			Handler:       _KeyValueService_Scan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cdb.proto",
}
