//
// Copyright (c) 2025 Karagatan LLC.
// SPDX-License-Identifier: BUSL-1.1

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: cdb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyValueService_Get_FullMethodName       = "/cdb.KeyValueService/Get"
	KeyValueService_GetRecent_FullMethodName = "/cdb.KeyValueService/GetRecent"
	KeyValueService_GetRange_FullMethodName  = "/cdb.KeyValueService/GetRange"
	KeyValueService_GetRow_FullMethodName    = "/cdb.KeyValueService/GetRow"
	KeyValueService_GetRegion_FullMethodName = "/cdb.KeyValueService/GetRegion"
	KeyValueService_GetSpace_FullMethodName  = "/cdb.KeyValueService/GetSpace"
	KeyValueService_Scan_FullMethodName      = "/cdb.KeyValueService/Scan"
	KeyValueService_Touch_FullMethodName     = "/cdb.KeyValueService/Touch"
	KeyValueService_Put_FullMethodName       = "/cdb.KeyValueService/Put"
	KeyValueService_Remove_FullMethodName    = "/cdb.KeyValueService/Remove"
)

// KeyValueServiceClient is the client API for KeyValueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyValueServiceClient interface {
	// Gets exact match entry
	Get(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error)
	// Gets early or equal timestamp entry
	GetRecent(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error)
	// Gets range of timestamps inside a row
	GetRange(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*Block, error)
	// Gets the whole raw of records with all available timestamps with latest versions
	GetRow(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error)
	// Gets the whole region of records
	GetRegion(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error)
	// Gets the whole space of records associated with majorKey
	GetSpace(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error)
	// Gets all records
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error)
	// Touches the record
	Touch(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Status, error)
	// Puts the record
	Put(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Status, error)
	// Remove the record
	Remove(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Status, error)
}

type keyValueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValueServiceClient(cc grpc.ClientConnInterface) KeyValueServiceClient {
	return &keyValueServiceClient{cc}
}

func (c *keyValueServiceClient) Get(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, KeyValueService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) GetRecent(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, KeyValueService_GetRecent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) GetRange(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Block)
	err := c.cc.Invoke(ctx, KeyValueService_GetRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) GetRow(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeyValueService_ServiceDesc.Streams[0], KeyValueService_GetRow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KeyRequest, Block]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyValueService_GetRowClient = grpc.ServerStreamingClient[Block]

func (c *keyValueServiceClient) GetRegion(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeyValueService_ServiceDesc.Streams[1], KeyValueService_GetRegion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KeyRequest, Block]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyValueService_GetRegionClient = grpc.ServerStreamingClient[Block]

func (c *keyValueServiceClient) GetSpace(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeyValueService_ServiceDesc.Streams[2], KeyValueService_GetSpace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KeyRequest, Block]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyValueService_GetSpaceClient = grpc.ServerStreamingClient[Block]

func (c *keyValueServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeyValueService_ServiceDesc.Streams[3], KeyValueService_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, Block]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyValueService_ScanClient = grpc.ServerStreamingClient[Block]

func (c *keyValueServiceClient) Touch(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, KeyValueService_Touch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) Put(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, KeyValueService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) Remove(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, KeyValueService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValueServiceServer is the server API for KeyValueService service.
// All implementations must embed UnimplementedKeyValueServiceServer
// for forward compatibility.
type KeyValueServiceServer interface {
	// Gets exact match entry
	Get(context.Context, *KeyRequest) (*Record, error)
	// Gets early or equal timestamp entry
	GetRecent(context.Context, *KeyRequest) (*Record, error)
	// Gets range of timestamps inside a row
	GetRange(context.Context, *RangeRequest) (*Block, error)
	// Gets the whole raw of records with all available timestamps with latest versions
	GetRow(*KeyRequest, grpc.ServerStreamingServer[Block]) error
	// Gets the whole region of records
	GetRegion(*KeyRequest, grpc.ServerStreamingServer[Block]) error
	// Gets the whole space of records associated with majorKey
	GetSpace(*KeyRequest, grpc.ServerStreamingServer[Block]) error
	// Gets all records
	Scan(*ScanRequest, grpc.ServerStreamingServer[Block]) error
	// Touches the record
	Touch(context.Context, *RecordRequest) (*Status, error)
	// Puts the record
	Put(context.Context, *RecordRequest) (*Status, error)
	// Remove the record
	Remove(context.Context, *KeyRequest) (*Status, error)
	mustEmbedUnimplementedKeyValueServiceServer()
}

// UnimplementedKeyValueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyValueServiceServer struct{}

func (UnimplementedKeyValueServiceServer) Get(context.Context, *KeyRequest) (*Record, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKeyValueServiceServer) GetRecent(context.Context, *KeyRequest) (*Record, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecent not implemented")
}
func (UnimplementedKeyValueServiceServer) GetRange(context.Context, *RangeRequest) (*Block, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRange not implemented")
}
func (UnimplementedKeyValueServiceServer) GetRow(*KeyRequest, grpc.ServerStreamingServer[Block]) error {
	return status.Error(codes.Unimplemented, "method GetRow not implemented")
}
func (UnimplementedKeyValueServiceServer) GetRegion(*KeyRequest, grpc.ServerStreamingServer[Block]) error {
	return status.Error(codes.Unimplemented, "method GetRegion not implemented")
}
func (UnimplementedKeyValueServiceServer) GetSpace(*KeyRequest, grpc.ServerStreamingServer[Block]) error {
	return status.Error(codes.Unimplemented, "method GetSpace not implemented")
}
func (UnimplementedKeyValueServiceServer) Scan(*ScanRequest, grpc.ServerStreamingServer[Block]) error {
	return status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedKeyValueServiceServer) Touch(context.Context, *RecordRequest) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Touch not implemented")
}
func (UnimplementedKeyValueServiceServer) Put(context.Context, *RecordRequest) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKeyValueServiceServer) Remove(context.Context, *KeyRequest) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedKeyValueServiceServer) mustEmbedUnimplementedKeyValueServiceServer() {}
func (UnimplementedKeyValueServiceServer) testEmbeddedByValue()                         {}

// UnsafeKeyValueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyValueServiceServer will
// result in compilation errors.
type UnsafeKeyValueServiceServer interface {
	mustEmbedUnimplementedKeyValueServiceServer()
}

func RegisterKeyValueServiceServer(s grpc.ServiceRegistrar, srv KeyValueServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyValueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyValueService_ServiceDesc, srv)
}

func _KeyValueService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).Get(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_GetRecent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).GetRecent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueService_GetRecent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).GetRecent(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_GetRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).GetRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueService_GetRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).GetRange(ctx, req.(*RangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_GetRow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueServiceServer).GetRow(m, &grpc.GenericServerStream[KeyRequest, Block]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyValueService_GetRowServer = grpc.ServerStreamingServer[Block]

func _KeyValueService_GetRegion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueServiceServer).GetRegion(m, &grpc.GenericServerStream[KeyRequest, Block]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyValueService_GetRegionServer = grpc.ServerStreamingServer[Block]

func _KeyValueService_GetSpace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueServiceServer).GetSpace(m, &grpc.GenericServerStream[KeyRequest, Block]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyValueService_GetSpaceServer = grpc.ServerStreamingServer[Block]

func _KeyValueService_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueServiceServer).Scan(m, &grpc.GenericServerStream[ScanRequest, Block]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyValueService_ScanServer = grpc.ServerStreamingServer[Block]

func _KeyValueService_Touch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).Touch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueService_Touch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).Touch(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).Put(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).Remove(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyValueService_ServiceDesc is the grpc.ServiceDesc for KeyValueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyValueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdb.KeyValueService",
	HandlerType: (*KeyValueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KeyValueService_Get_Handler,
		},
		{
			MethodName: "GetRecent",
			Handler:    _KeyValueService_GetRecent_Handler,
		},
		{
			MethodName: "GetRange",
			Handler:    _KeyValueService_GetRange_Handler,
		},
		{
			MethodName: "Touch",
			Handler:    _KeyValueService_Touch_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _KeyValueService_Put_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _KeyValueService_Remove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRow",
			Handler:       _KeyValueService_GetRow_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetRegion",
			Handler:       _KeyValueService_GetRegion_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSpace",
			Handler:       _KeyValueService_GetSpace_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Scan",
			Handler:       _KeyValueService_Scan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cdb.proto",
}
