// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bigbagger.proto

package bbproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataDistribution int32

const (
	DataDistribution_DATA_LOCAL       DataDistribution = 0
	DataDistribution_DATA_REPLICATION DataDistribution = 1
	DataDistribution_DATA_PARTITION   DataDistribution = 2
)

var DataDistribution_name = map[int32]string{
	0: "DATA_LOCAL",
	1: "DATA_REPLICATION",
	2: "DATA_PARTITION",
}

var DataDistribution_value = map[string]int32{
	"DATA_LOCAL":       0,
	"DATA_REPLICATION": 1,
	"DATA_PARTITION":   2,
}

func (x DataDistribution) String() string {
	return proto.EnumName(DataDistribution_name, int32(x))
}

func (DataDistribution) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{0}
}

type PointInTime int32

const (
	PointInTime_PIT_NO                 PointInTime = 0
	PointInTime_PIT_LAST_ONE           PointInTime = 1
	PointInTime_PIT_LAST_FIVE          PointInTime = 5
	PointInTime_PIT_LAST_TEN           PointInTime = 10
	PointInTime_PIT_FIRST_TEN_LAST_TEN PointInTime = 20
	PointInTime_PIT_ALL                PointInTime = 100
)

var PointInTime_name = map[int32]string{
	0:   "PIT_NO",
	1:   "PIT_LAST_ONE",
	5:   "PIT_LAST_FIVE",
	10:  "PIT_LAST_TEN",
	20:  "PIT_FIRST_TEN_LAST_TEN",
	100: "PIT_ALL",
}

var PointInTime_value = map[string]int32{
	"PIT_NO":                 0,
	"PIT_LAST_ONE":           1,
	"PIT_LAST_FIVE":          5,
	"PIT_LAST_TEN":           10,
	"PIT_FIRST_TEN_LAST_TEN": 20,
	"PIT_ALL":                100,
}

func (x PointInTime) String() string {
	return proto.EnumName(PointInTime_name, int32(x))
}

func (PointInTime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{1}
}

type EncryptionAlgorithm int32

const (
	EncryptionAlgorithm_ALG_NO     EncryptionAlgorithm = 0
	EncryptionAlgorithm_ALG_AES256 EncryptionAlgorithm = 1
)

var EncryptionAlgorithm_name = map[int32]string{
	0: "ALG_NO",
	1: "ALG_AES256",
}

var EncryptionAlgorithm_value = map[string]int32{
	"ALG_NO":     0,
	"ALG_AES256": 1,
}

func (x EncryptionAlgorithm) String() string {
	return proto.EnumName(EncryptionAlgorithm_name, int32(x))
}

func (EncryptionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{2}
}

type EncryptionMode int32

const (
	EncryptionMode_MODE_NO  EncryptionMode = 0
	EncryptionMode_MODE_ECB EncryptionMode = 1
	EncryptionMode_MODE_CBC EncryptionMode = 2
	EncryptionMode_MODE_OFB EncryptionMode = 3
	EncryptionMode_MODE_CFB EncryptionMode = 4
	EncryptionMode_MODE_CTR EncryptionMode = 5
	EncryptionMode_MODE_XTS EncryptionMode = 6
)

var EncryptionMode_name = map[int32]string{
	0: "MODE_NO",
	1: "MODE_ECB",
	2: "MODE_CBC",
	3: "MODE_OFB",
	4: "MODE_CFB",
	5: "MODE_CTR",
	6: "MODE_XTS",
}

var EncryptionMode_value = map[string]int32{
	"MODE_NO":  0,
	"MODE_ECB": 1,
	"MODE_CBC": 2,
	"MODE_OFB": 3,
	"MODE_CFB": 4,
	"MODE_CTR": 5,
	"MODE_XTS": 6,
}

func (x EncryptionMode) String() string {
	return proto.EnumName(EncryptionMode_name, int32(x))
}

func (EncryptionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{3}
}

type CompressionAlgorithm int32

const (
	CompressionAlgorithm_COMPRESS_NO    CompressionAlgorithm = 0
	CompressionAlgorithm_COMPRESS_FLATE CompressionAlgorithm = 1
	CompressionAlgorithm_COMPRESS_GZIP  CompressionAlgorithm = 2
	CompressionAlgorithm_COMPRESS_LZW   CompressionAlgorithm = 3
	CompressionAlgorithm_COMPRESS_ZLIB  CompressionAlgorithm = 4
	CompressionAlgorithm_COMPRESS_BZIP2 CompressionAlgorithm = 5
)

var CompressionAlgorithm_name = map[int32]string{
	0: "COMPRESS_NO",
	1: "COMPRESS_FLATE",
	2: "COMPRESS_GZIP",
	3: "COMPRESS_LZW",
	4: "COMPRESS_ZLIB",
	5: "COMPRESS_BZIP2",
}

var CompressionAlgorithm_value = map[string]int32{
	"COMPRESS_NO":    0,
	"COMPRESS_FLATE": 1,
	"COMPRESS_GZIP":  2,
	"COMPRESS_LZW":   3,
	"COMPRESS_ZLIB":  4,
	"COMPRESS_BZIP2": 5,
}

func (x CompressionAlgorithm) String() string {
	return proto.EnumName(CompressionAlgorithm_name, int32(x))
}

func (CompressionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{4}
}

type CompressionLevel int32

const (
	CompressionLevel_DEFAULT_LEVEL    CompressionLevel = 0
	CompressionLevel_BEST_SPEED       CompressionLevel = 1
	CompressionLevel_BEST_COMPRESSION CompressionLevel = 2
)

var CompressionLevel_name = map[int32]string{
	0: "DEFAULT_LEVEL",
	1: "BEST_SPEED",
	2: "BEST_COMPRESSION",
}

var CompressionLevel_value = map[string]int32{
	"DEFAULT_LEVEL":    0,
	"BEST_SPEED":       1,
	"BEST_COMPRESSION": 2,
}

func (x CompressionLevel) String() string {
	return proto.EnumName(CompressionLevel_name, int32(x))
}

func (CompressionLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{5}
}

type StatusCode int32

const (
	StatusCode_SUCCESS             StatusCode = 0
	StatusCode_SUCCESS_NOT_UPDATED StatusCode = 1
	StatusCode_ERROR_NO_DATASET    StatusCode = 10
	StatusCode_ERROR_BAD_REQUEST   StatusCode = 11
	StatusCode_ERROR_POLICY        StatusCode = 12
	StatusCode_ERROR_MIGRATION     StatusCode = 13
	StatusCode_ERROR_NETWORK       StatusCode = 14
	StatusCode_ERROR_AUTH          StatusCode = 15
	StatusCode_ERROR_FORBIDDEN     StatusCode = 16
	StatusCode_ERROR_TIMEOUT       StatusCode = 17
	StatusCode_ERROR_OVERLOAD      StatusCode = 18
	StatusCode_ERROR_OVERFLOW      StatusCode = 19
	StatusCode_ERROR_LOCKED        StatusCode = 20
	StatusCode_ERROR_ABORTED       StatusCode = 21
	StatusCode_ERROR_INTERRUPTED   StatusCode = 22
	StatusCode_ERROR_UNSUPPORTED   StatusCode = 23
	StatusCode_ERROR_DRIVER        StatusCode = 24
	StatusCode_ERROR_IO            StatusCode = 25
	StatusCode_ERROR_INTERNAL      StatusCode = 26
)

var StatusCode_name = map[int32]string{
	0:  "SUCCESS",
	1:  "SUCCESS_NOT_UPDATED",
	10: "ERROR_NO_DATASET",
	11: "ERROR_BAD_REQUEST",
	12: "ERROR_POLICY",
	13: "ERROR_MIGRATION",
	14: "ERROR_NETWORK",
	15: "ERROR_AUTH",
	16: "ERROR_FORBIDDEN",
	17: "ERROR_TIMEOUT",
	18: "ERROR_OVERLOAD",
	19: "ERROR_OVERFLOW",
	20: "ERROR_LOCKED",
	21: "ERROR_ABORTED",
	22: "ERROR_INTERRUPTED",
	23: "ERROR_UNSUPPORTED",
	24: "ERROR_DRIVER",
	25: "ERROR_IO",
	26: "ERROR_INTERNAL",
}

var StatusCode_value = map[string]int32{
	"SUCCESS":             0,
	"SUCCESS_NOT_UPDATED": 1,
	"ERROR_NO_DATASET":    10,
	"ERROR_BAD_REQUEST":   11,
	"ERROR_POLICY":        12,
	"ERROR_MIGRATION":     13,
	"ERROR_NETWORK":       14,
	"ERROR_AUTH":          15,
	"ERROR_FORBIDDEN":     16,
	"ERROR_TIMEOUT":       17,
	"ERROR_OVERLOAD":      18,
	"ERROR_OVERFLOW":      19,
	"ERROR_LOCKED":        20,
	"ERROR_ABORTED":       21,
	"ERROR_INTERRUPTED":   22,
	"ERROR_UNSUPPORTED":   23,
	"ERROR_DRIVER":        24,
	"ERROR_IO":            25,
	"ERROR_INTERNAL":      26,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{6}
}

type Partition struct {
	Total                uint32   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	ReplicationFactor    uint32   `protobuf:"varint,2,opt,name=replicationFactor,proto3" json:"replicationFactor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{0}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Partition) GetReplicationFactor() uint32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

type Encryption struct {
	Alg                  EncryptionAlgorithm `protobuf:"varint,1,opt,name=alg,proto3,enum=bb.EncryptionAlgorithm" json:"alg,omitempty"`
	Mode                 EncryptionMode      `protobuf:"varint,2,opt,name=mode,proto3,enum=bb.EncryptionMode" json:"mode,omitempty"`
	TopoKey              string              `protobuf:"bytes,3,opt,name=topoKey,proto3" json:"topoKey,omitempty"`
	TopoIv               string              `protobuf:"bytes,4,opt,name=topoIv,proto3" json:"topoIv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Encryption) Reset()         { *m = Encryption{} }
func (m *Encryption) String() string { return proto.CompactTextString(m) }
func (*Encryption) ProtoMessage()    {}
func (*Encryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{1}
}

func (m *Encryption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Encryption.Unmarshal(m, b)
}
func (m *Encryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Encryption.Marshal(b, m, deterministic)
}
func (m *Encryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Encryption.Merge(m, src)
}
func (m *Encryption) XXX_Size() int {
	return xxx_messageInfo_Encryption.Size(m)
}
func (m *Encryption) XXX_DiscardUnknown() {
	xxx_messageInfo_Encryption.DiscardUnknown(m)
}

var xxx_messageInfo_Encryption proto.InternalMessageInfo

func (m *Encryption) GetAlg() EncryptionAlgorithm {
	if m != nil {
		return m.Alg
	}
	return EncryptionAlgorithm_ALG_NO
}

func (m *Encryption) GetMode() EncryptionMode {
	if m != nil {
		return m.Mode
	}
	return EncryptionMode_MODE_NO
}

func (m *Encryption) GetTopoKey() string {
	if m != nil {
		return m.TopoKey
	}
	return ""
}

func (m *Encryption) GetTopoIv() string {
	if m != nil {
		return m.TopoIv
	}
	return ""
}

type Compression struct {
	Alg                  CompressionAlgorithm `protobuf:"varint,1,opt,name=alg,proto3,enum=bb.CompressionAlgorithm" json:"alg,omitempty"`
	Level                CompressionLevel     `protobuf:"varint,2,opt,name=level,proto3,enum=bb.CompressionLevel" json:"level,omitempty"`
	Threshold            uint32               `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Compression) Reset()         { *m = Compression{} }
func (m *Compression) String() string { return proto.CompactTextString(m) }
func (*Compression) ProtoMessage()    {}
func (*Compression) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{2}
}

func (m *Compression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Compression.Unmarshal(m, b)
}
func (m *Compression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Compression.Marshal(b, m, deterministic)
}
func (m *Compression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Compression.Merge(m, src)
}
func (m *Compression) XXX_Size() int {
	return xxx_messageInfo_Compression.Size(m)
}
func (m *Compression) XXX_DiscardUnknown() {
	xxx_messageInfo_Compression.DiscardUnknown(m)
}

var xxx_messageInfo_Compression proto.InternalMessageInfo

func (m *Compression) GetAlg() CompressionAlgorithm {
	if m != nil {
		return m.Alg
	}
	return CompressionAlgorithm_COMPRESS_NO
}

func (m *Compression) GetLevel() CompressionLevel {
	if m != nil {
		return m.Level
	}
	return CompressionLevel_DEFAULT_LEVEL
}

func (m *Compression) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

type Dataset struct {
	Version              string           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Distr                DataDistribution `protobuf:"varint,3,opt,name=distr,proto3,enum=bb.DataDistribution" json:"distr,omitempty"`
	Partition            *Partition       `protobuf:"bytes,4,opt,name=partition,proto3" json:"partition,omitempty"`
	Compression          *Compression     `protobuf:"bytes,5,opt,name=compression,proto3" json:"compression,omitempty"`
	Encryption           *Encryption      `protobuf:"bytes,6,opt,name=encryption,proto3" json:"encryption,omitempty"`
	Pit                  PointInTime      `protobuf:"varint,7,opt,name=pit,proto3,enum=bb.PointInTime" json:"pit,omitempty"`
	TtlSeconds           uint32           `protobuf:"varint,8,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Dataset) Reset()         { *m = Dataset{} }
func (m *Dataset) String() string { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()    {}
func (*Dataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{3}
}

func (m *Dataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dataset.Unmarshal(m, b)
}
func (m *Dataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dataset.Marshal(b, m, deterministic)
}
func (m *Dataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dataset.Merge(m, src)
}
func (m *Dataset) XXX_Size() int {
	return xxx_messageInfo_Dataset.Size(m)
}
func (m *Dataset) XXX_DiscardUnknown() {
	xxx_messageInfo_Dataset.DiscardUnknown(m)
}

var xxx_messageInfo_Dataset proto.InternalMessageInfo

func (m *Dataset) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Dataset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dataset) GetDistr() DataDistribution {
	if m != nil {
		return m.Distr
	}
	return DataDistribution_DATA_LOCAL
}

func (m *Dataset) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *Dataset) GetCompression() *Compression {
	if m != nil {
		return m.Compression
	}
	return nil
}

func (m *Dataset) GetEncryption() *Encryption {
	if m != nil {
		return m.Encryption
	}
	return nil
}

func (m *Dataset) GetPit() PointInTime {
	if m != nil {
		return m.Pit
	}
	return PointInTime_PIT_NO
}

func (m *Dataset) GetTtlSeconds() uint32 {
	if m != nil {
		return m.TtlSeconds
	}
	return 0
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{4}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Key struct {
	SetName              string   `protobuf:"bytes,1,opt,name=setName,proto3" json:"setName,omitempty"`
	PartitionKey         []byte   `protobuf:"bytes,2,opt,name=partitionKey,proto3" json:"partitionKey,omitempty"`
	RecordKey            []byte   `protobuf:"bytes,3,opt,name=recordKey,proto3" json:"recordKey,omitempty"`
	Timestamp            uint64   `protobuf:"fixed64,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{5}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetSetName() string {
	if m != nil {
		return m.SetName
	}
	return ""
}

func (m *Key) GetPartitionKey() []byte {
	if m != nil {
		return m.PartitionKey
	}
	return nil
}

func (m *Key) GetRecordKey() []byte {
	if m != nil {
		return m.RecordKey
	}
	return nil
}

func (m *Key) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type RecordOperation struct {
	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Operation:
	//	*RecordOperation_Head
	//	*RecordOperation_Get
	//	*RecordOperation_Touch
	//	*RecordOperation_Put
	//	*RecordOperation_Remove
	Operation            isRecordOperation_Operation `protobuf_oneof:"operation"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *RecordOperation) Reset()         { *m = RecordOperation{} }
func (m *RecordOperation) String() string { return proto.CompactTextString(m) }
func (*RecordOperation) ProtoMessage()    {}
func (*RecordOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{6}
}

func (m *RecordOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordOperation.Unmarshal(m, b)
}
func (m *RecordOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordOperation.Marshal(b, m, deterministic)
}
func (m *RecordOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordOperation.Merge(m, src)
}
func (m *RecordOperation) XXX_Size() int {
	return xxx_messageInfo_RecordOperation.Size(m)
}
func (m *RecordOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordOperation.DiscardUnknown(m)
}

var xxx_messageInfo_RecordOperation proto.InternalMessageInfo

func (m *RecordOperation) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type isRecordOperation_Operation interface {
	isRecordOperation_Operation()
}

type RecordOperation_Head struct {
	Head *HeadOperation `protobuf:"bytes,10,opt,name=head,proto3,oneof"`
}

type RecordOperation_Get struct {
	Get *GetOperation `protobuf:"bytes,11,opt,name=get,proto3,oneof"`
}

type RecordOperation_Touch struct {
	Touch *TouchOperation `protobuf:"bytes,12,opt,name=touch,proto3,oneof"`
}

type RecordOperation_Put struct {
	Put *PutOperation `protobuf:"bytes,13,opt,name=put,proto3,oneof"`
}

type RecordOperation_Remove struct {
	Remove *RemoveOperation `protobuf:"bytes,14,opt,name=remove,proto3,oneof"`
}

func (*RecordOperation_Head) isRecordOperation_Operation() {}

func (*RecordOperation_Get) isRecordOperation_Operation() {}

func (*RecordOperation_Touch) isRecordOperation_Operation() {}

func (*RecordOperation_Put) isRecordOperation_Operation() {}

func (*RecordOperation_Remove) isRecordOperation_Operation() {}

func (m *RecordOperation) GetOperation() isRecordOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *RecordOperation) GetHead() *HeadOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Head); ok {
		return x.Head
	}
	return nil
}

func (m *RecordOperation) GetGet() *GetOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Get); ok {
		return x.Get
	}
	return nil
}

func (m *RecordOperation) GetTouch() *TouchOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Touch); ok {
		return x.Touch
	}
	return nil
}

func (m *RecordOperation) GetPut() *PutOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Put); ok {
		return x.Put
	}
	return nil
}

func (m *RecordOperation) GetRemove() *RemoveOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Remove); ok {
		return x.Remove
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RecordOperation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RecordOperation_OneofMarshaler, _RecordOperation_OneofUnmarshaler, _RecordOperation_OneofSizer, []interface{}{
		(*RecordOperation_Head)(nil),
		(*RecordOperation_Get)(nil),
		(*RecordOperation_Touch)(nil),
		(*RecordOperation_Put)(nil),
		(*RecordOperation_Remove)(nil),
	}
}

func _RecordOperation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RecordOperation)
	// operation
	switch x := m.Operation.(type) {
	case *RecordOperation_Head:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Head); err != nil {
			return err
		}
	case *RecordOperation_Get:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *RecordOperation_Touch:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Touch); err != nil {
			return err
		}
	case *RecordOperation_Put:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case *RecordOperation_Remove:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Remove); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RecordOperation.Operation has unexpected type %T", x)
	}
	return nil
}

func _RecordOperation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RecordOperation)
	switch tag {
	case 10: // operation.head
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HeadOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Head{msg}
		return true, err
	case 11: // operation.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Get{msg}
		return true, err
	case 12: // operation.touch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TouchOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Touch{msg}
		return true, err
	case 13: // operation.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Put{msg}
		return true, err
	case 14: // operation.remove
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Remove{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RecordOperation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RecordOperation)
	// operation
	switch x := m.Operation.(type) {
	case *RecordOperation_Head:
		s := proto.Size(x.Head)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordOperation_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordOperation_Touch:
		s := proto.Size(x.Touch)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordOperation_Put:
		s := proto.Size(x.Put)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordOperation_Remove:
		s := proto.Size(x.Remove)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HeadOperation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeadOperation) Reset()         { *m = HeadOperation{} }
func (m *HeadOperation) String() string { return proto.CompactTextString(m) }
func (*HeadOperation) ProtoMessage()    {}
func (*HeadOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{7}
}

func (m *HeadOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeadOperation.Unmarshal(m, b)
}
func (m *HeadOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeadOperation.Marshal(b, m, deterministic)
}
func (m *HeadOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeadOperation.Merge(m, src)
}
func (m *HeadOperation) XXX_Size() int {
	return xxx_messageInfo_HeadOperation.Size(m)
}
func (m *HeadOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_HeadOperation.DiscardUnknown(m)
}

var xxx_messageInfo_HeadOperation proto.InternalMessageInfo

type GetOperation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOperation) Reset()         { *m = GetOperation{} }
func (m *GetOperation) String() string { return proto.CompactTextString(m) }
func (*GetOperation) ProtoMessage()    {}
func (*GetOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{8}
}

func (m *GetOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOperation.Unmarshal(m, b)
}
func (m *GetOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOperation.Marshal(b, m, deterministic)
}
func (m *GetOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOperation.Merge(m, src)
}
func (m *GetOperation) XXX_Size() int {
	return xxx_messageInfo_GetOperation.Size(m)
}
func (m *GetOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOperation.DiscardUnknown(m)
}

var xxx_messageInfo_GetOperation proto.InternalMessageInfo

type TouchOperation struct {
	OverrideTtl          bool     `protobuf:"varint,1,opt,name=overrideTtl,proto3" json:"overrideTtl,omitempty"`
	TtlSeconds           uint32   `protobuf:"varint,2,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchOperation) Reset()         { *m = TouchOperation{} }
func (m *TouchOperation) String() string { return proto.CompactTextString(m) }
func (*TouchOperation) ProtoMessage()    {}
func (*TouchOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{9}
}

func (m *TouchOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchOperation.Unmarshal(m, b)
}
func (m *TouchOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchOperation.Marshal(b, m, deterministic)
}
func (m *TouchOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchOperation.Merge(m, src)
}
func (m *TouchOperation) XXX_Size() int {
	return xxx_messageInfo_TouchOperation.Size(m)
}
func (m *TouchOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TouchOperation proto.InternalMessageInfo

func (m *TouchOperation) GetOverrideTtl() bool {
	if m != nil {
		return m.OverrideTtl
	}
	return false
}

func (m *TouchOperation) GetTtlSeconds() uint32 {
	if m != nil {
		return m.TtlSeconds
	}
	return 0
}

type PutOperation struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	OverrideTtl          bool     `protobuf:"varint,5,opt,name=overrideTtl,proto3" json:"overrideTtl,omitempty"`
	TtlSeconds           uint32   `protobuf:"varint,6,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	CompareAndSet        bool     `protobuf:"varint,7,opt,name=compareAndSet,proto3" json:"compareAndSet,omitempty"`
	Version              uint64   `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutOperation) Reset()         { *m = PutOperation{} }
func (m *PutOperation) String() string { return proto.CompactTextString(m) }
func (*PutOperation) ProtoMessage()    {}
func (*PutOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{10}
}

func (m *PutOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutOperation.Unmarshal(m, b)
}
func (m *PutOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutOperation.Marshal(b, m, deterministic)
}
func (m *PutOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutOperation.Merge(m, src)
}
func (m *PutOperation) XXX_Size() int {
	return xxx_messageInfo_PutOperation.Size(m)
}
func (m *PutOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_PutOperation.DiscardUnknown(m)
}

var xxx_messageInfo_PutOperation proto.InternalMessageInfo

func (m *PutOperation) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutOperation) GetOverrideTtl() bool {
	if m != nil {
		return m.OverrideTtl
	}
	return false
}

func (m *PutOperation) GetTtlSeconds() uint32 {
	if m != nil {
		return m.TtlSeconds
	}
	return 0
}

func (m *PutOperation) GetCompareAndSet() bool {
	if m != nil {
		return m.CompareAndSet
	}
	return false
}

func (m *PutOperation) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RemoveOperation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOperation) Reset()         { *m = RemoveOperation{} }
func (m *RemoveOperation) String() string { return proto.CompactTextString(m) }
func (*RemoveOperation) ProtoMessage()    {}
func (*RemoveOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{11}
}

func (m *RemoveOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOperation.Unmarshal(m, b)
}
func (m *RemoveOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOperation.Marshal(b, m, deterministic)
}
func (m *RemoveOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOperation.Merge(m, src)
}
func (m *RemoveOperation) XXX_Size() int {
	return xxx_messageInfo_RemoveOperation.Size(m)
}
func (m *RemoveOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOperation.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOperation proto.InternalMessageInfo

type RecordResult struct {
	Status  StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=bb.StatusCode" json:"status,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*RecordResult_Head
	//	*RecordResult_Get
	//	*RecordResult_Touch
	//	*RecordResult_Put
	//	*RecordResult_Remove
	Result               isRecordResult_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RecordResult) Reset()         { *m = RecordResult{} }
func (m *RecordResult) String() string { return proto.CompactTextString(m) }
func (*RecordResult) ProtoMessage()    {}
func (*RecordResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{12}
}

func (m *RecordResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordResult.Unmarshal(m, b)
}
func (m *RecordResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordResult.Marshal(b, m, deterministic)
}
func (m *RecordResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordResult.Merge(m, src)
}
func (m *RecordResult) XXX_Size() int {
	return xxx_messageInfo_RecordResult.Size(m)
}
func (m *RecordResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordResult.DiscardUnknown(m)
}

var xxx_messageInfo_RecordResult proto.InternalMessageInfo

func (m *RecordResult) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

func (m *RecordResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type isRecordResult_Result interface {
	isRecordResult_Result()
}

type RecordResult_Head struct {
	Head *HeadResult `protobuf:"bytes,10,opt,name=head,proto3,oneof"`
}

type RecordResult_Get struct {
	Get *GetResult `protobuf:"bytes,11,opt,name=get,proto3,oneof"`
}

type RecordResult_Touch struct {
	Touch *TouchResult `protobuf:"bytes,12,opt,name=touch,proto3,oneof"`
}

type RecordResult_Put struct {
	Put *PutResult `protobuf:"bytes,13,opt,name=put,proto3,oneof"`
}

type RecordResult_Remove struct {
	Remove *RemoveResult `protobuf:"bytes,14,opt,name=remove,proto3,oneof"`
}

func (*RecordResult_Head) isRecordResult_Result() {}

func (*RecordResult_Get) isRecordResult_Result() {}

func (*RecordResult_Touch) isRecordResult_Result() {}

func (*RecordResult_Put) isRecordResult_Result() {}

func (*RecordResult_Remove) isRecordResult_Result() {}

func (m *RecordResult) GetResult() isRecordResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RecordResult) GetHead() *HeadResult {
	if x, ok := m.GetResult().(*RecordResult_Head); ok {
		return x.Head
	}
	return nil
}

func (m *RecordResult) GetGet() *GetResult {
	if x, ok := m.GetResult().(*RecordResult_Get); ok {
		return x.Get
	}
	return nil
}

func (m *RecordResult) GetTouch() *TouchResult {
	if x, ok := m.GetResult().(*RecordResult_Touch); ok {
		return x.Touch
	}
	return nil
}

func (m *RecordResult) GetPut() *PutResult {
	if x, ok := m.GetResult().(*RecordResult_Put); ok {
		return x.Put
	}
	return nil
}

func (m *RecordResult) GetRemove() *RemoveResult {
	if x, ok := m.GetResult().(*RecordResult_Remove); ok {
		return x.Remove
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RecordResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RecordResult_OneofMarshaler, _RecordResult_OneofUnmarshaler, _RecordResult_OneofSizer, []interface{}{
		(*RecordResult_Head)(nil),
		(*RecordResult_Get)(nil),
		(*RecordResult_Touch)(nil),
		(*RecordResult_Put)(nil),
		(*RecordResult_Remove)(nil),
	}
}

func _RecordResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RecordResult)
	// result
	switch x := m.Result.(type) {
	case *RecordResult_Head:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Head); err != nil {
			return err
		}
	case *RecordResult_Get:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *RecordResult_Touch:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Touch); err != nil {
			return err
		}
	case *RecordResult_Put:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case *RecordResult_Remove:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Remove); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RecordResult.Result has unexpected type %T", x)
	}
	return nil
}

func _RecordResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RecordResult)
	switch tag {
	case 10: // result.head
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HeadResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Head{msg}
		return true, err
	case 11: // result.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Get{msg}
		return true, err
	case 12: // result.touch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TouchResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Touch{msg}
		return true, err
	case 13: // result.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Put{msg}
		return true, err
	case 14: // result.remove
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Remove{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RecordResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RecordResult)
	// result
	switch x := m.Result.(type) {
	case *RecordResult_Head:
		s := proto.Size(x.Head)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordResult_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordResult_Touch:
		s := proto.Size(x.Touch)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordResult_Put:
		s := proto.Size(x.Put)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordResult_Remove:
		s := proto.Size(x.Remove)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Head struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ExpiresAt            uint64   `protobuf:"fixed64,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	Timestamp            uint64   `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DiskSize             int64    `protobuf:"varint,4,opt,name=diskSize,proto3" json:"diskSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{13}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Head) GetExpiresAt() uint64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *Head) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Head) GetDiskSize() int64 {
	if m != nil {
		return m.DiskSize
	}
	return 0
}

type HeadResult struct {
	Head                 *Head    `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeadResult) Reset()         { *m = HeadResult{} }
func (m *HeadResult) String() string { return proto.CompactTextString(m) }
func (*HeadResult) ProtoMessage()    {}
func (*HeadResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{14}
}

func (m *HeadResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeadResult.Unmarshal(m, b)
}
func (m *HeadResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeadResult.Marshal(b, m, deterministic)
}
func (m *HeadResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeadResult.Merge(m, src)
}
func (m *HeadResult) XXX_Size() int {
	return xxx_messageInfo_HeadResult.Size(m)
}
func (m *HeadResult) XXX_DiscardUnknown() {
	xxx_messageInfo_HeadResult.DiscardUnknown(m)
}

var xxx_messageInfo_HeadResult proto.InternalMessageInfo

func (m *HeadResult) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

type GetResult struct {
	Head                 *Head    `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResult) Reset()         { *m = GetResult{} }
func (m *GetResult) String() string { return proto.CompactTextString(m) }
func (*GetResult) ProtoMessage()    {}
func (*GetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{15}
}

func (m *GetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResult.Unmarshal(m, b)
}
func (m *GetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResult.Marshal(b, m, deterministic)
}
func (m *GetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResult.Merge(m, src)
}
func (m *GetResult) XXX_Size() int {
	return xxx_messageInfo_GetResult.Size(m)
}
func (m *GetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetResult proto.InternalMessageInfo

func (m *GetResult) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *GetResult) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type TouchResult struct {
	Head                 *Head    `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchResult) Reset()         { *m = TouchResult{} }
func (m *TouchResult) String() string { return proto.CompactTextString(m) }
func (*TouchResult) ProtoMessage()    {}
func (*TouchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{16}
}

func (m *TouchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchResult.Unmarshal(m, b)
}
func (m *TouchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchResult.Marshal(b, m, deterministic)
}
func (m *TouchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchResult.Merge(m, src)
}
func (m *TouchResult) XXX_Size() int {
	return xxx_messageInfo_TouchResult.Size(m)
}
func (m *TouchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchResult.DiscardUnknown(m)
}

var xxx_messageInfo_TouchResult proto.InternalMessageInfo

func (m *TouchResult) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

type PutResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResult) Reset()         { *m = PutResult{} }
func (m *PutResult) String() string { return proto.CompactTextString(m) }
func (*PutResult) ProtoMessage()    {}
func (*PutResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{17}
}

func (m *PutResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResult.Unmarshal(m, b)
}
func (m *PutResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResult.Marshal(b, m, deterministic)
}
func (m *PutResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResult.Merge(m, src)
}
func (m *PutResult) XXX_Size() int {
	return xxx_messageInfo_PutResult.Size(m)
}
func (m *PutResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResult.DiscardUnknown(m)
}

var xxx_messageInfo_PutResult proto.InternalMessageInfo

type RemoveResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResult) Reset()         { *m = RemoveResult{} }
func (m *RemoveResult) String() string { return proto.CompactTextString(m) }
func (*RemoveResult) ProtoMessage()    {}
func (*RemoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{18}
}

func (m *RemoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResult.Unmarshal(m, b)
}
func (m *RemoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResult.Marshal(b, m, deterministic)
}
func (m *RemoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResult.Merge(m, src)
}
func (m *RemoveResult) XXX_Size() int {
	return xxx_messageInfo_RemoveResult.Size(m)
}
func (m *RemoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResult proto.InternalMessageInfo

type Transaction struct {
	Operations           []*RecordOperation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{19}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetOperations() []*RecordOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type TransactionContext struct {
	Results              []*RecordResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TransactionContext) Reset()         { *m = TransactionContext{} }
func (m *TransactionContext) String() string { return proto.CompactTextString(m) }
func (*TransactionContext) ProtoMessage()    {}
func (*TransactionContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{20}
}

func (m *TransactionContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionContext.Unmarshal(m, b)
}
func (m *TransactionContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionContext.Marshal(b, m, deterministic)
}
func (m *TransactionContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionContext.Merge(m, src)
}
func (m *TransactionContext) XXX_Size() int {
	return xxx_messageInfo_TransactionContext.Size(m)
}
func (m *TransactionContext) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionContext.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionContext proto.InternalMessageInfo

func (m *TransactionContext) GetResults() []*RecordResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterEnum("bb.DataDistribution", DataDistribution_name, DataDistribution_value)
	proto.RegisterEnum("bb.PointInTime", PointInTime_name, PointInTime_value)
	proto.RegisterEnum("bb.EncryptionAlgorithm", EncryptionAlgorithm_name, EncryptionAlgorithm_value)
	proto.RegisterEnum("bb.EncryptionMode", EncryptionMode_name, EncryptionMode_value)
	proto.RegisterEnum("bb.CompressionAlgorithm", CompressionAlgorithm_name, CompressionAlgorithm_value)
	proto.RegisterEnum("bb.CompressionLevel", CompressionLevel_name, CompressionLevel_value)
	proto.RegisterEnum("bb.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Partition)(nil), "bb.Partition")
	proto.RegisterType((*Encryption)(nil), "bb.Encryption")
	proto.RegisterType((*Compression)(nil), "bb.Compression")
	proto.RegisterType((*Dataset)(nil), "bb.Dataset")
	proto.RegisterType((*String)(nil), "bb.String")
	proto.RegisterType((*Key)(nil), "bb.Key")
	proto.RegisterType((*RecordOperation)(nil), "bb.RecordOperation")
	proto.RegisterType((*HeadOperation)(nil), "bb.HeadOperation")
	proto.RegisterType((*GetOperation)(nil), "bb.GetOperation")
	proto.RegisterType((*TouchOperation)(nil), "bb.TouchOperation")
	proto.RegisterType((*PutOperation)(nil), "bb.PutOperation")
	proto.RegisterType((*RemoveOperation)(nil), "bb.RemoveOperation")
	proto.RegisterType((*RecordResult)(nil), "bb.RecordResult")
	proto.RegisterType((*Head)(nil), "bb.Head")
	proto.RegisterType((*HeadResult)(nil), "bb.HeadResult")
	proto.RegisterType((*GetResult)(nil), "bb.GetResult")
	proto.RegisterType((*TouchResult)(nil), "bb.TouchResult")
	proto.RegisterType((*PutResult)(nil), "bb.PutResult")
	proto.RegisterType((*RemoveResult)(nil), "bb.RemoveResult")
	proto.RegisterType((*Transaction)(nil), "bb.Transaction")
	proto.RegisterType((*TransactionContext)(nil), "bb.TransactionContext")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatasetServiceClient is the client API for DatasetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatasetServiceClient interface {
	Create(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error)
	Update(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *String, opts ...grpc.CallOption) (*empty.Empty, error)
	Get(ctx context.Context, in *String, opts ...grpc.CallOption) (DatasetService_GetClient, error)
}

type datasetServiceClient struct {
	cc *grpc.ClientConn
}

func NewDatasetServiceClient(cc *grpc.ClientConn) DatasetServiceClient {
	return &datasetServiceClient{cc}
}

func (c *datasetServiceClient) Create(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bb.DatasetService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) Update(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bb.DatasetService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) Delete(ctx context.Context, in *String, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bb.DatasetService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) Get(ctx context.Context, in *String, opts ...grpc.CallOption) (DatasetService_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DatasetService_serviceDesc.Streams[0], "/bb.DatasetService/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &datasetServiceGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DatasetService_GetClient interface {
	Recv() (*Dataset, error)
	grpc.ClientStream
}

type datasetServiceGetClient struct {
	grpc.ClientStream
}

func (x *datasetServiceGetClient) Recv() (*Dataset, error) {
	m := new(Dataset)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DatasetServiceServer is the server API for DatasetService service.
type DatasetServiceServer interface {
	Create(context.Context, *Dataset) (*empty.Empty, error)
	Update(context.Context, *Dataset) (*empty.Empty, error)
	Delete(context.Context, *String) (*empty.Empty, error)
	Get(*String, DatasetService_GetServer) error
}

func RegisterDatasetServiceServer(s *grpc.Server, srv DatasetServiceServer) {
	s.RegisterService(&_DatasetService_serviceDesc, srv)
}

func _DatasetService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dataset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bb.DatasetService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).Create(ctx, req.(*Dataset))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dataset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bb.DatasetService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).Update(ctx, req.(*Dataset))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bb.DatasetService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).Delete(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(String)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatasetServiceServer).Get(m, &datasetServiceGetServer{stream})
}

type DatasetService_GetServer interface {
	Send(*Dataset) error
	grpc.ServerStream
}

type datasetServiceGetServer struct {
	grpc.ServerStream
}

func (x *datasetServiceGetServer) Send(m *Dataset) error {
	return x.ServerStream.SendMsg(m)
}

var _DatasetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bb.DatasetService",
	HandlerType: (*DatasetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DatasetService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DatasetService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DatasetService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _DatasetService_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bigbagger.proto",
}

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	Execute(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionContext, error)
}

type transactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionServiceClient(cc *grpc.ClientConn) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) Execute(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*TransactionContext, error) {
	out := new(TransactionContext)
	err := c.cc.Invoke(ctx, "/bb.TransactionService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	Execute(context.Context, *Transaction) (*TransactionContext, error)
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bb.TransactionService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Execute(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bb.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _TransactionService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bigbagger.proto",
}

func init() { proto.RegisterFile("bigbagger.proto", fileDescriptor_5a14183de89fcd5b) }

var fileDescriptor_5a14183de89fcd5b = []byte{
	// 1746 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xcf, 0x93, 0xdb, 0x48,
	0x15, 0x8e, 0xec, 0x19, 0xcf, 0xf8, 0xf9, 0xc7, 0xf4, 0xf4, 0x4c, 0x26, 0x5e, 0x6f, 0xd8, 0x4a,
	0x54, 0xa9, 0xec, 0xe2, 0xdd, 0xd8, 0x1b, 0x6f, 0xc1, 0x21, 0x55, 0x14, 0x2b, 0xd9, 0xf2, 0x44,
	0x35, 0x1a, 0xcb, 0xb4, 0xe4, 0x04, 0xe6, 0xe2, 0x92, 0xed, 0xc6, 0x23, 0xd6, 0xb6, 0x8c, 0xd4,
	0x36, 0x33, 0x50, 0x5b, 0x4b, 0xc1, 0x81, 0xe2, 0x08, 0x1c, 0xb9, 0x71, 0xe0, 0xca, 0x0d, 0xfe,
	0x10, 0xfe, 0x05, 0xfe, 0x10, 0xaa, 0x5b, 0xbf, 0x9d, 0xc0, 0xee, 0xc9, 0x7a, 0xdf, 0xfb, 0xfa,
	0xeb, 0xd7, 0xaf, 0xbf, 0x6e, 0x4b, 0x70, 0x32, 0x75, 0x17, 0x53, 0x67, 0xb1, 0xa0, 0x7e, 0x7b,
	0xe3, 0x7b, 0xcc, 0xc3, 0x85, 0xe9, 0xb4, 0xf9, 0x78, 0xe1, 0x79, 0x8b, 0x25, 0xed, 0x38, 0x1b,
	0xb7, 0xe3, 0xac, 0xd7, 0x1e, 0x73, 0x98, 0xeb, 0xad, 0x83, 0x90, 0xd1, 0xfc, 0x30, 0xca, 0x8a,
	0x68, 0xba, 0xfd, 0x79, 0x87, 0xae, 0x36, 0xec, 0x3e, 0x4a, 0x7e, 0x26, 0x7e, 0x66, 0x2f, 0x16,
	0x74, 0xfd, 0x22, 0xf8, 0x95, 0x10, 0xee, 0x78, 0x1b, 0x31, 0xfc, 0x5d, 0x29, 0xd9, 0x84, 0xf2,
	0xc8, 0xf1, 0x99, 0xcb, 0x31, 0x7c, 0x0e, 0x87, 0xcc, 0x63, 0xce, 0xb2, 0x21, 0x3d, 0x91, 0x3e,
	0xa9, 0x91, 0x30, 0xc0, 0x9f, 0xc1, 0xa9, 0x4f, 0x37, 0x4b, 0x77, 0x26, 0x06, 0x0e, 0x9c, 0x19,
	0xf3, 0xfc, 0x46, 0x41, 0x30, 0xde, 0x4d, 0xc8, 0x7f, 0x92, 0x00, 0xb4, 0xf5, 0xcc, 0xbf, 0x17,
	0x53, 0xe2, 0xef, 0x43, 0xd1, 0x59, 0x2e, 0x84, 0x60, 0xbd, 0xfb, 0xa8, 0x3d, 0x9d, 0xb6, 0xd3,
	0xa4, 0xb2, 0x5c, 0x78, 0xbe, 0xcb, 0x6e, 0x57, 0x84, 0x73, 0xf0, 0x73, 0x38, 0x58, 0x79, 0x73,
	0x2a, 0xa4, 0xeb, 0x5d, 0x9c, 0xe7, 0x5e, 0x7b, 0x73, 0x4a, 0x44, 0x1e, 0x37, 0xe0, 0x88, 0x79,
	0x1b, 0xef, 0x8a, 0xde, 0x37, 0x8a, 0x4f, 0xa4, 0x4f, 0xca, 0x24, 0x0e, 0xf1, 0x05, 0x94, 0xf8,
	0xa3, 0xbe, 0x6b, 0x1c, 0x88, 0x44, 0x14, 0xc9, 0xbf, 0x97, 0xa0, 0xd2, 0xf3, 0x56, 0x1b, 0x9f,
	0x06, 0x01, 0x2f, 0xaa, 0x95, 0x2d, 0xaa, 0xc1, 0x27, 0xca, 0x64, 0xf7, 0xaa, 0x6a, 0xc1, 0xe1,
	0x92, 0xee, 0xe8, 0x32, 0x2a, 0xeb, 0x7c, 0x8f, 0x6d, 0xf0, 0x1c, 0x09, 0x29, 0xf8, 0x31, 0x94,
	0xd9, 0xad, 0x4f, 0x83, 0x5b, 0x6f, 0x39, 0x17, 0xb5, 0xd5, 0x48, 0x0a, 0xc8, 0xff, 0x2c, 0xc0,
	0x51, 0xdf, 0x61, 0x4e, 0x40, 0x19, 0x5f, 0xc3, 0x8e, 0xfa, 0x5c, 0x40, 0x54, 0x51, 0x26, 0x71,
	0x88, 0x31, 0x1c, 0xac, 0x9d, 0x55, 0xd8, 0x85, 0x32, 0x11, 0xcf, 0xbc, 0x86, 0xb9, 0x1b, 0x30,
	0x5f, 0x68, 0x46, 0x35, 0x70, 0xa5, 0x3e, 0x07, 0xdd, 0xe9, 0x96, 0x37, 0x88, 0x84, 0x14, 0xfc,
	0x29, 0x94, 0x37, 0xf1, 0x86, 0x8a, 0x36, 0x54, 0xba, 0x35, 0xce, 0x4f, 0x76, 0x99, 0xa4, 0x79,
	0xfc, 0x12, 0x2a, 0xb3, 0x74, 0x2d, 0x8d, 0x43, 0x41, 0x3f, 0xd9, 0x5b, 0x22, 0xc9, 0x72, 0x70,
	0x1b, 0x80, 0x26, 0xbb, 0xd2, 0x28, 0x89, 0x11, 0xf5, 0xfc, 0x5e, 0x91, 0x0c, 0x03, 0x3f, 0x85,
	0xe2, 0xc6, 0x65, 0x8d, 0x23, 0x51, 0xb9, 0x90, 0x1e, 0x79, 0xee, 0x9a, 0xe9, 0x6b, 0xdb, 0x5d,
	0x51, 0xc2, 0x73, 0xf8, 0x23, 0x00, 0xc6, 0x96, 0x16, 0x9d, 0x79, 0xeb, 0x79, 0xd0, 0x38, 0x16,
	0x7d, 0xcb, 0x20, 0xf2, 0x47, 0x50, 0xb2, 0x98, 0xef, 0xae, 0x17, 0xdc, 0xa0, 0x3b, 0x67, 0xb9,
	0xa5, 0x51, 0xd3, 0xc2, 0x40, 0xfe, 0x06, 0x8a, 0x7c, 0xf7, 0x1b, 0x70, 0x14, 0x50, 0x36, 0xe4,
	0xcd, 0x8b, 0x7a, 0x1a, 0x85, 0x58, 0x86, 0x6a, 0xb2, 0x66, 0x6e, 0x1b, 0xde, 0xdb, 0x2a, 0xc9,
	0x61, 0x7c, 0xef, 0x7c, 0x3a, 0xf3, 0xfc, 0x79, 0xec, 0xab, 0x2a, 0x49, 0x01, 0xb1, 0xb3, 0xee,
	0x8a, 0x06, 0xcc, 0x59, 0x6d, 0x44, 0x57, 0x4b, 0x24, 0x05, 0xe4, 0x3f, 0x16, 0xe0, 0x84, 0x08,
	0xae, 0xb9, 0xa1, 0xbe, 0x38, 0x0d, 0xf8, 0x03, 0x28, 0x7e, 0x45, 0xef, 0x45, 0x25, 0x95, 0xee,
	0x11, 0x5f, 0xf7, 0x15, 0xbd, 0x27, 0x1c, 0xc3, 0x1f, 0xc3, 0xc1, 0x2d, 0x75, 0xe6, 0x0d, 0x10,
	0xb9, 0x53, 0x9e, 0x7b, 0x4d, 0x9d, 0x74, 0xec, 0xeb, 0x07, 0x44, 0x10, 0xf0, 0x33, 0x28, 0x2e,
	0x28, 0x6b, 0x54, 0x04, 0x0f, 0x71, 0xde, 0x25, 0x65, 0x59, 0x1a, 0x4f, 0x73, 0x77, 0x30, 0x6f,
	0x3b, 0xbb, 0x6d, 0x54, 0x05, 0x4f, 0x1c, 0x1c, 0x9b, 0x03, 0x59, 0x66, 0x48, 0xe1, 0x8a, 0x9b,
	0x2d, 0x6b, 0xd4, 0x52, 0xc5, 0xd1, 0x36, 0xaf, 0xb8, 0xd9, 0x32, 0xfc, 0x02, 0x4a, 0x3e, 0x5d,
	0x79, 0x3b, 0xda, 0xa8, 0x0b, 0xe2, 0x19, 0x27, 0x12, 0x81, 0x64, 0xb9, 0x11, 0x49, 0xad, 0x40,
	0xd9, 0x8b, 0x61, 0xf9, 0x04, 0x6a, 0xb9, 0xc5, 0xc8, 0x75, 0xa8, 0x66, 0xab, 0x96, 0x09, 0xd4,
	0xf3, 0xd5, 0xe1, 0x27, 0x50, 0xf1, 0x76, 0xd4, 0xf7, 0xdd, 0x39, 0xb5, 0x59, 0x78, 0xf9, 0x1c,
	0x93, 0x2c, 0xb4, 0xe7, 0x90, 0xc2, 0x3b, 0x0e, 0xf9, 0xbb, 0x04, 0xd5, 0xec, 0x42, 0xf2, 0x46,
	0xa9, 0x46, 0x46, 0xd9, 0x9f, 0xe8, 0xf0, 0xdb, 0x26, 0x2a, 0xed, 0x4f, 0x84, 0x9f, 0x41, 0x8d,
	0x1f, 0x06, 0xc7, 0xa7, 0xca, 0x7a, 0x6e, 0xd1, 0xd0, 0xd7, 0xc7, 0x24, 0x0f, 0x66, 0x4f, 0x37,
	0x77, 0xf3, 0x41, 0x72, 0xba, 0xe5, 0x53, 0x6e, 0x94, 0x5c, 0x1f, 0xe5, 0xbf, 0x16, 0xa0, 0x1a,
	0x9a, 0x87, 0xd0, 0x60, 0xbb, 0x64, 0xf8, 0x39, 0x94, 0x02, 0xe6, 0xb0, 0x6d, 0x10, 0x5d, 0x50,
	0xe2, 0x74, 0x59, 0x02, 0xe9, 0xf1, 0x5b, 0x30, 0xca, 0xf2, 0x59, 0x56, 0x34, 0x08, 0x9c, 0x45,
	0x7c, 0x59, 0xc4, 0x21, 0x7e, 0x96, 0x33, 0x58, 0x3d, 0x36, 0x58, 0xa8, 0x9f, 0xb8, 0xeb, 0x69,
	0xd6, 0x5d, 0xb5, 0xc8, 0x5d, 0x09, 0x47, 0x58, 0xeb, 0xe3, 0xbc, 0xb5, 0x4e, 0x12, 0x6b, 0x25,
	0xb4, 0xc8, 0x57, 0x4f, 0xb3, 0xbe, 0xaa, 0x45, 0xbe, 0x4a, 0xb5, 0xb8, 0xa9, 0x5a, 0x7b, 0xa6,
	0x42, 0xa9, 0xa9, 0x12, 0x62, 0xec, 0xa8, 0x63, 0xce, 0xe5, 0x98, 0x7c, 0x07, 0x07, 0xbc, 0xf4,
	0xfd, 0x0b, 0x33, 0x6d, 0x29, 0x3f, 0x9a, 0xf4, 0x6e, 0xe3, 0xfa, 0x34, 0x50, 0x98, 0x68, 0x44,
	0x89, 0xa4, 0x40, 0xfe, 0xe0, 0x16, 0xf7, 0x0e, 0x2e, 0x6e, 0xc2, 0xf1, 0xdc, 0x0d, 0xbe, 0xb2,
	0xdc, 0x5f, 0x53, 0x71, 0xaa, 0x8b, 0x24, 0x89, 0xe5, 0x16, 0x40, 0xda, 0x34, 0xfc, 0x38, 0x6a,
	0x69, 0x78, 0x9e, 0x8f, 0x93, 0x96, 0x0a, 0x54, 0xfe, 0x31, 0x94, 0x93, 0xde, 0xfd, 0x7f, 0x6a,
	0xea, 0xcc, 0x42, 0xc6, 0x99, 0xf2, 0xa7, 0x50, 0xc9, 0xf4, 0xf5, 0x5b, 0x66, 0xab, 0x40, 0x39,
	0xe9, 0x2e, 0x3f, 0x5e, 0xd9, 0x26, 0xca, 0x2a, 0x54, 0x6c, 0xdf, 0x59, 0x07, 0xce, 0x4c, 0x1c,
	0x84, 0x2f, 0x00, 0x92, 0xb3, 0xc9, 0x0d, 0x55, 0x4c, 0x8f, 0x73, 0xee, 0xbe, 0x22, 0x19, 0x9a,
	0xfc, 0x25, 0xe0, 0x8c, 0x46, 0xcf, 0x5b, 0x33, 0x7a, 0xc7, 0x37, 0xf0, 0x28, 0xdc, 0x94, 0x58,
	0x07, 0xa5, 0x3a, 0xe1, 0xe4, 0x24, 0x26, 0xb4, 0x0c, 0x40, 0xfb, 0x7f, 0x50, 0xb8, 0x0e, 0xd0,
	0x57, 0x6c, 0x65, 0x62, 0x98, 0x3d, 0xc5, 0x40, 0x0f, 0xf0, 0x39, 0x20, 0x11, 0x13, 0x6d, 0x64,
	0xe8, 0x3d, 0xc5, 0xd6, 0xcd, 0x21, 0x92, 0x30, 0x86, 0xba, 0x40, 0x47, 0x0a, 0xb1, 0x75, 0x81,
	0x15, 0x5a, 0xf7, 0x50, 0xc9, 0xfc, 0x69, 0x60, 0x80, 0xd2, 0x48, 0xb7, 0x27, 0x43, 0x13, 0x3d,
	0xc0, 0x08, 0xaa, 0xfc, 0xd9, 0x50, 0x2c, 0x7b, 0x62, 0x0e, 0x35, 0x24, 0xe1, 0x53, 0xa8, 0x25,
	0xc8, 0x40, 0x7f, 0xa3, 0xa1, 0xc3, 0x1c, 0xc9, 0xd6, 0x86, 0x08, 0x70, 0x13, 0x2e, 0x38, 0x32,
	0xd0, 0x49, 0x08, 0xa5, 0xb9, 0x73, 0x5c, 0x81, 0x23, 0x9e, 0x53, 0x0c, 0x03, 0xcd, 0x5b, 0x2f,
	0xe1, 0xec, 0x3d, 0x2f, 0x2c, 0xbc, 0x04, 0xc5, 0xb8, 0x0c, 0x4b, 0xa8, 0x03, 0xf0, 0x67, 0x45,
	0xb3, 0xba, 0x3f, 0xf8, 0x21, 0x92, 0x5a, 0xbf, 0x84, 0x7a, 0xfe, 0xbd, 0x85, 0x2b, 0x5e, 0x9b,
	0x7d, 0x2d, 0xa4, 0x57, 0xe1, 0x58, 0x04, 0x5a, 0x4f, 0x45, 0x52, 0x12, 0xf5, 0xd4, 0x1e, 0x2a,
	0x24, 0x91, 0x39, 0x50, 0x51, 0x31, 0xcd, 0x0d, 0x54, 0x74, 0x90, 0x46, 0x36, 0x41, 0x87, 0x49,
	0xf4, 0x53, 0xdb, 0x42, 0xa5, 0xd6, 0x1f, 0x24, 0x38, 0x7f, 0xdf, 0x2b, 0x0c, 0x3e, 0x81, 0x4a,
	0xcf, 0xbc, 0x1e, 0x11, 0xcd, 0xb2, 0xc2, 0xd9, 0x31, 0xd4, 0x13, 0x60, 0x60, 0x28, 0x76, 0xd4,
	0xb1, 0x04, 0xbb, 0xbc, 0xd1, 0x47, 0xa8, 0xc0, 0x3b, 0x96, 0x40, 0xc6, 0xcd, 0x5b, 0x54, 0xcc,
	0x91, 0x6e, 0x0c, 0x9d, 0x57, 0x94, 0xd5, 0x52, 0x6f, 0xf4, 0x51, 0x17, 0x1d, 0xb6, 0xae, 0x00,
	0xed, 0xbf, 0x1d, 0xf1, 0xa1, 0x7d, 0x6d, 0xa0, 0x8c, 0x0d, 0x7b, 0x62, 0x68, 0x6f, 0x34, 0x23,
	0xec, 0x99, 0xaa, 0x59, 0xf6, 0xc4, 0x1a, 0x69, 0x5a, 0x1f, 0x49, 0xdc, 0x0b, 0x22, 0x8e, 0xf5,
	0xc2, 0x7d, 0xff, 0x6d, 0x11, 0x20, 0xbd, 0xf8, 0x78, 0x1b, 0xad, 0x71, 0xaf, 0xa7, 0x59, 0x16,
	0x7a, 0x80, 0x1f, 0xc1, 0x59, 0x14, 0x4c, 0x86, 0xa6, 0x3d, 0x19, 0x8f, 0xfa, 0x8a, 0x1d, 0x4b,
	0x69, 0x84, 0x98, 0x64, 0x32, 0x34, 0x27, 0xdc, 0x49, 0x96, 0x66, 0x23, 0xc0, 0x0f, 0xe1, 0x34,
	0x44, 0x55, 0xa5, 0x3f, 0x21, 0xda, 0x4f, 0xc6, 0x9a, 0x65, 0xa3, 0x0a, 0x5f, 0x67, 0x08, 0x8f,
	0x4c, 0x43, 0xef, 0xfd, 0x0c, 0x55, 0xf1, 0x19, 0x9c, 0x84, 0xc8, 0xb5, 0x7e, 0x49, 0x42, 0x53,
	0xd6, 0xf8, 0x0a, 0x22, 0x4d, 0xcd, 0x7e, 0x6b, 0x92, 0x2b, 0x54, 0xe7, 0x2b, 0x08, 0x21, 0x65,
	0x6c, 0xbf, 0x46, 0x27, 0xe9, 0xb8, 0x81, 0x49, 0x54, 0xbd, 0xdf, 0xd7, 0x86, 0x08, 0xa5, 0xe3,
	0x6c, 0xfd, 0x5a, 0x33, 0xc7, 0x36, 0x3a, 0xe5, 0x4d, 0x0b, 0x21, 0xf3, 0x8d, 0x46, 0x0c, 0x53,
	0xe9, 0x23, 0x9c, 0xc7, 0x06, 0x86, 0xf9, 0x16, 0x9d, 0xa5, 0x95, 0x19, 0x66, 0xef, 0x4a, 0xeb,
	0xa3, 0xf3, 0x54, 0x4c, 0x51, 0x4d, 0xc2, 0xd7, 0xfa, 0x30, 0x5d, 0x95, 0x3e, 0xb4, 0x35, 0x42,
	0xc6, 0x23, 0x0e, 0x5f, 0xa4, 0xf0, 0x78, 0x68, 0x8d, 0x47, 0xa3, 0x90, 0xfd, 0x28, 0x95, 0xec,
	0x13, 0xfd, 0x8d, 0x46, 0x50, 0x83, 0xbb, 0x28, 0x1a, 0x6f, 0xa2, 0x0f, 0xd2, 0x32, 0x84, 0xda,
	0x50, 0x31, 0x50, 0xb3, 0xfb, 0x8f, 0x02, 0xd4, 0xa3, 0x97, 0x56, 0x8b, 0xfa, 0x3b, 0x77, 0x46,
	0xb1, 0x06, 0xa5, 0x9e, 0x4f, 0x1d, 0x46, 0x71, 0x25, 0x7e, 0x11, 0x0d, 0x28, 0x6b, 0x5e, 0xb4,
	0xc3, 0xaf, 0x92, 0x76, 0xfc, 0x55, 0xd2, 0xd6, 0xf8, 0x57, 0x89, 0x7c, 0xf1, 0xbb, 0x7f, 0xff,
	0xe7, 0x2f, 0x05, 0x24, 0x57, 0x3a, 0xbb, 0x97, 0x9d, 0x79, 0x48, 0x7e, 0x25, 0xb5, 0xb0, 0x01,
	0xa5, 0xf1, 0x66, 0xfe, 0x9d, 0x65, 0xbe, 0x27, 0x64, 0x1e, 0x35, 0x71, 0x46, 0xa6, 0xf3, 0x1b,
	0xfe, 0x7a, 0xfc, 0x35, 0x57, 0xd3, 0xa1, 0xd4, 0xa7, 0x4b, 0xca, 0x28, 0x86, 0xf0, 0xef, 0x92,
	0xbf, 0x2f, 0xfe, 0x4f, 0xb1, 0x0f, 0x85, 0xd8, 0xc3, 0xd6, 0x59, 0x4e, 0x4c, 0x5c, 0xc5, 0x5f,
	0xe3, 0x1f, 0x41, 0xf1, 0x92, 0xb2, 0x9c, 0x4e, 0xb6, 0xc2, 0x78, 0x30, 0x7e, 0xdf, 0xe0, 0xcf,
	0xa5, 0xee, 0x3c, 0x77, 0x79, 0xc6, 0x4d, 0x1b, 0xc2, 0x91, 0x76, 0x47, 0x67, 0x5b, 0x46, 0x71,
	0xf8, 0x2f, 0x9a, 0x52, 0x9a, 0x17, 0x7b, 0x40, 0x74, 0xe1, 0xca, 0x4d, 0x31, 0xd1, 0x79, 0xf3,
	0x84, 0x4f, 0xc4, 0xd2, 0xfc, 0x2b, 0xa9, 0xa5, 0xfe, 0x4b, 0xfa, 0xb3, 0xf2, 0x0d, 0x1e, 0x43,
	0x59, 0x75, 0x17, 0xaa, 0xf8, 0xc8, 0x93, 0x7b, 0x99, 0x00, 0x3f, 0xbf, 0x65, 0x6c, 0x13, 0xbc,
	0xea, 0x74, 0x16, 0x2e, 0xbb, 0xdd, 0x4e, 0xdb, 0x33, 0x6f, 0xd5, 0x49, 0xb2, 0x9d, 0xe4, 0x93,
	0xb3, 0x59, 0x77, 0x96, 0xf4, 0xee, 0xcb, 0xe0, 0x76, 0xe7, 0xce, 0x39, 0xa7, 0x5b, 0x7c, 0xd9,
	0xfe, 0xbc, 0x55, 0x90, 0x0a, 0x5d, 0xe4, 0x6c, 0x92, 0x4f, 0xbb, 0xce, 0x2f, 0x02, 0x6f, 0xfd,
	0xea, 0x1d, 0x04, 0xce, 0x5c, 0xaf, 0x1d, 0xe9, 0x27, 0x8a, 0xea, 0xb1, 0xaa, 0x8e, 0x78, 0xb7,
	0x83, 0x91, 0x74, 0x53, 0x13, 0x7d, 0xef, 0x4c, 0xa7, 0xe2, 0xf7, 0x6f, 0x85, 0x82, 0xaa, 0x4e,
	0x4b, 0xe2, 0xf9, 0x8b, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x3e, 0xec, 0x45, 0xf8, 0x0e,
	0x00, 0x00,
}
