// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bigbagger.proto

package bbproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataDistribution int32

const (
	DataDistribution_DD_LOCAL       DataDistribution = 0
	DataDistribution_DD_REPLICATION DataDistribution = 1
	DataDistribution_DD_PARTITION   DataDistribution = 2
)

var DataDistribution_name = map[int32]string{
	0: "DD_LOCAL",
	1: "DD_REPLICATION",
	2: "DD_PARTITION",
}

var DataDistribution_value = map[string]int32{
	"DD_LOCAL":       0,
	"DD_REPLICATION": 1,
	"DD_PARTITION":   2,
}

func (x DataDistribution) String() string {
	return proto.EnumName(DataDistribution_name, int32(x))
}

func (DataDistribution) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{0}
}

type PointInTime int32

const (
	PointInTime_PIT_NO                 PointInTime = 0
	PointInTime_PIT_LAST_ONE           PointInTime = 1
	PointInTime_PIT_LAST_FIVE          PointInTime = 5
	PointInTime_PIT_LAST_TEN           PointInTime = 10
	PointInTime_PIT_FIRST_TEN_LAST_TEN PointInTime = 20
	PointInTime_PIT_ALL                PointInTime = 100
)

var PointInTime_name = map[int32]string{
	0:   "PIT_NO",
	1:   "PIT_LAST_ONE",
	5:   "PIT_LAST_FIVE",
	10:  "PIT_LAST_TEN",
	20:  "PIT_FIRST_TEN_LAST_TEN",
	100: "PIT_ALL",
}

var PointInTime_value = map[string]int32{
	"PIT_NO":                 0,
	"PIT_LAST_ONE":           1,
	"PIT_LAST_FIVE":          5,
	"PIT_LAST_TEN":           10,
	"PIT_FIRST_TEN_LAST_TEN": 20,
	"PIT_ALL":                100,
}

func (x PointInTime) String() string {
	return proto.EnumName(PointInTime_name, int32(x))
}

func (PointInTime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{1}
}

type EncryptionAlgorithm int32

const (
	EncryptionAlgorithm_ALG_NO     EncryptionAlgorithm = 0
	EncryptionAlgorithm_ALG_AES256 EncryptionAlgorithm = 1
)

var EncryptionAlgorithm_name = map[int32]string{
	0: "ALG_NO",
	1: "ALG_AES256",
}

var EncryptionAlgorithm_value = map[string]int32{
	"ALG_NO":     0,
	"ALG_AES256": 1,
}

func (x EncryptionAlgorithm) String() string {
	return proto.EnumName(EncryptionAlgorithm_name, int32(x))
}

func (EncryptionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{2}
}

type EncryptionMode int32

const (
	EncryptionMode_MODE_NO  EncryptionMode = 0
	EncryptionMode_MODE_ECB EncryptionMode = 1
	EncryptionMode_MODE_CBC EncryptionMode = 2
	EncryptionMode_MODE_OFB EncryptionMode = 3
	EncryptionMode_MODE_CFB EncryptionMode = 4
	EncryptionMode_MODE_CTR EncryptionMode = 5
	EncryptionMode_MODE_XTS EncryptionMode = 6
)

var EncryptionMode_name = map[int32]string{
	0: "MODE_NO",
	1: "MODE_ECB",
	2: "MODE_CBC",
	3: "MODE_OFB",
	4: "MODE_CFB",
	5: "MODE_CTR",
	6: "MODE_XTS",
}

var EncryptionMode_value = map[string]int32{
	"MODE_NO":  0,
	"MODE_ECB": 1,
	"MODE_CBC": 2,
	"MODE_OFB": 3,
	"MODE_CFB": 4,
	"MODE_CTR": 5,
	"MODE_XTS": 6,
}

func (x EncryptionMode) String() string {
	return proto.EnumName(EncryptionMode_name, int32(x))
}

func (EncryptionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{3}
}

type DataCompression int32

const (
	DataCompression_DC_NO    DataCompression = 0
	DataCompression_DC_FLATE DataCompression = 1
	DataCompression_DC_GZIP  DataCompression = 2
	DataCompression_DC_LZW   DataCompression = 3
	DataCompression_DC_ZLIB  DataCompression = 4
	DataCompression_DC_BZIP2 DataCompression = 5
)

var DataCompression_name = map[int32]string{
	0: "DC_NO",
	1: "DC_FLATE",
	2: "DC_GZIP",
	3: "DC_LZW",
	4: "DC_ZLIB",
	5: "DC_BZIP2",
}

var DataCompression_value = map[string]int32{
	"DC_NO":    0,
	"DC_FLATE": 1,
	"DC_GZIP":  2,
	"DC_LZW":   3,
	"DC_ZLIB":  4,
	"DC_BZIP2": 5,
}

func (x DataCompression) String() string {
	return proto.EnumName(DataCompression_name, int32(x))
}

func (DataCompression) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{4}
}

type StatusCode int32

const (
	StatusCode_SUCCESS             StatusCode = 0
	StatusCode_SUCCESS_NOT_UPDATED StatusCode = 1
	StatusCode_ERROR_NO_DATASET    StatusCode = 10
	StatusCode_ERROR_BAD_REQUEST   StatusCode = 11
	StatusCode_ERROR_POLICY        StatusCode = 12
	StatusCode_ERROR_MIGRATION     StatusCode = 13
	StatusCode_ERROR_NETWORK       StatusCode = 14
	StatusCode_ERROR_AUTH          StatusCode = 15
	StatusCode_ERROR_FORBIDDEN     StatusCode = 16
	StatusCode_ERROR_TIMEOUT       StatusCode = 17
	StatusCode_ERROR_OVERLOAD      StatusCode = 18
	StatusCode_ERROR_OVERFLOW      StatusCode = 19
	StatusCode_ERROR_LOCKED        StatusCode = 20
	StatusCode_ERROR_ABORTED       StatusCode = 21
	StatusCode_ERROR_INTERRUPTED   StatusCode = 22
	StatusCode_ERROR_UNSUPPORTED   StatusCode = 23
	StatusCode_ERROR_DRIVER        StatusCode = 24
	StatusCode_ERROR_IO            StatusCode = 25
	StatusCode_ERROR_INTERNAL      StatusCode = 26
)

var StatusCode_name = map[int32]string{
	0:  "SUCCESS",
	1:  "SUCCESS_NOT_UPDATED",
	10: "ERROR_NO_DATASET",
	11: "ERROR_BAD_REQUEST",
	12: "ERROR_POLICY",
	13: "ERROR_MIGRATION",
	14: "ERROR_NETWORK",
	15: "ERROR_AUTH",
	16: "ERROR_FORBIDDEN",
	17: "ERROR_TIMEOUT",
	18: "ERROR_OVERLOAD",
	19: "ERROR_OVERFLOW",
	20: "ERROR_LOCKED",
	21: "ERROR_ABORTED",
	22: "ERROR_INTERRUPTED",
	23: "ERROR_UNSUPPORTED",
	24: "ERROR_DRIVER",
	25: "ERROR_IO",
	26: "ERROR_INTERNAL",
}

var StatusCode_value = map[string]int32{
	"SUCCESS":             0,
	"SUCCESS_NOT_UPDATED": 1,
	"ERROR_NO_DATASET":    10,
	"ERROR_BAD_REQUEST":   11,
	"ERROR_POLICY":        12,
	"ERROR_MIGRATION":     13,
	"ERROR_NETWORK":       14,
	"ERROR_AUTH":          15,
	"ERROR_FORBIDDEN":     16,
	"ERROR_TIMEOUT":       17,
	"ERROR_OVERLOAD":      18,
	"ERROR_OVERFLOW":      19,
	"ERROR_LOCKED":        20,
	"ERROR_ABORTED":       21,
	"ERROR_INTERRUPTED":   22,
	"ERROR_UNSUPPORTED":   23,
	"ERROR_DRIVER":        24,
	"ERROR_IO":            25,
	"ERROR_INTERNAL":      26,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{5}
}

type Partition struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	ReplicationFactor    int32    `protobuf:"varint,2,opt,name=replicationFactor,proto3" json:"replicationFactor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{0}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Partition) GetReplicationFactor() int32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

type Encryption struct {
	Algorithm            EncryptionAlgorithm `protobuf:"varint,1,opt,name=algorithm,proto3,enum=bb.EncryptionAlgorithm" json:"algorithm,omitempty"`
	Mode                 EncryptionMode      `protobuf:"varint,2,opt,name=mode,proto3,enum=bb.EncryptionMode" json:"mode,omitempty"`
	TopoKey              string              `protobuf:"bytes,3,opt,name=topoKey,proto3" json:"topoKey,omitempty"`
	TopoIv               string              `protobuf:"bytes,4,opt,name=topoIv,proto3" json:"topoIv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Encryption) Reset()         { *m = Encryption{} }
func (m *Encryption) String() string { return proto.CompactTextString(m) }
func (*Encryption) ProtoMessage()    {}
func (*Encryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{1}
}

func (m *Encryption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Encryption.Unmarshal(m, b)
}
func (m *Encryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Encryption.Marshal(b, m, deterministic)
}
func (m *Encryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Encryption.Merge(m, src)
}
func (m *Encryption) XXX_Size() int {
	return xxx_messageInfo_Encryption.Size(m)
}
func (m *Encryption) XXX_DiscardUnknown() {
	xxx_messageInfo_Encryption.DiscardUnknown(m)
}

var xxx_messageInfo_Encryption proto.InternalMessageInfo

func (m *Encryption) GetAlgorithm() EncryptionAlgorithm {
	if m != nil {
		return m.Algorithm
	}
	return EncryptionAlgorithm_ALG_NO
}

func (m *Encryption) GetMode() EncryptionMode {
	if m != nil {
		return m.Mode
	}
	return EncryptionMode_MODE_NO
}

func (m *Encryption) GetTopoKey() string {
	if m != nil {
		return m.TopoKey
	}
	return ""
}

func (m *Encryption) GetTopoIv() string {
	if m != nil {
		return m.TopoIv
	}
	return ""
}

type Compression struct {
	Comp                 DataCompression `protobuf:"varint,1,opt,name=comp,proto3,enum=bb.DataCompression" json:"comp,omitempty"`
	Threshold            int32           `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Compression) Reset()         { *m = Compression{} }
func (m *Compression) String() string { return proto.CompactTextString(m) }
func (*Compression) ProtoMessage()    {}
func (*Compression) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{2}
}

func (m *Compression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Compression.Unmarshal(m, b)
}
func (m *Compression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Compression.Marshal(b, m, deterministic)
}
func (m *Compression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Compression.Merge(m, src)
}
func (m *Compression) XXX_Size() int {
	return xxx_messageInfo_Compression.Size(m)
}
func (m *Compression) XXX_DiscardUnknown() {
	xxx_messageInfo_Compression.DiscardUnknown(m)
}

var xxx_messageInfo_Compression proto.InternalMessageInfo

func (m *Compression) GetComp() DataCompression {
	if m != nil {
		return m.Comp
	}
	return DataCompression_DC_NO
}

func (m *Compression) GetThreshold() int32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

type Dataset struct {
	Version              string           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Distr                DataDistribution `protobuf:"varint,3,opt,name=distr,proto3,enum=bb.DataDistribution" json:"distr,omitempty"`
	Partition            *Partition       `protobuf:"bytes,4,opt,name=partition,proto3" json:"partition,omitempty"`
	Compression          *Compression     `protobuf:"bytes,5,opt,name=compression,proto3" json:"compression,omitempty"`
	Encryption           *Encryption      `protobuf:"bytes,6,opt,name=encryption,proto3" json:"encryption,omitempty"`
	Pit                  PointInTime      `protobuf:"varint,7,opt,name=pit,proto3,enum=bb.PointInTime" json:"pit,omitempty"`
	TtlSeconds           int32            `protobuf:"varint,8,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Dataset) Reset()         { *m = Dataset{} }
func (m *Dataset) String() string { return proto.CompactTextString(m) }
func (*Dataset) ProtoMessage()    {}
func (*Dataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{3}
}

func (m *Dataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dataset.Unmarshal(m, b)
}
func (m *Dataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dataset.Marshal(b, m, deterministic)
}
func (m *Dataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dataset.Merge(m, src)
}
func (m *Dataset) XXX_Size() int {
	return xxx_messageInfo_Dataset.Size(m)
}
func (m *Dataset) XXX_DiscardUnknown() {
	xxx_messageInfo_Dataset.DiscardUnknown(m)
}

var xxx_messageInfo_Dataset proto.InternalMessageInfo

func (m *Dataset) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Dataset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dataset) GetDistr() DataDistribution {
	if m != nil {
		return m.Distr
	}
	return DataDistribution_DD_LOCAL
}

func (m *Dataset) GetPartition() *Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *Dataset) GetCompression() *Compression {
	if m != nil {
		return m.Compression
	}
	return nil
}

func (m *Dataset) GetEncryption() *Encryption {
	if m != nil {
		return m.Encryption
	}
	return nil
}

func (m *Dataset) GetPit() PointInTime {
	if m != nil {
		return m.Pit
	}
	return PointInTime_PIT_NO
}

func (m *Dataset) GetTtlSeconds() int32 {
	if m != nil {
		return m.TtlSeconds
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{5}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NameList struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameList) Reset()         { *m = NameList{} }
func (m *NameList) String() string { return proto.CompactTextString(m) }
func (*NameList) ProtoMessage()    {}
func (*NameList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{6}
}

func (m *NameList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameList.Unmarshal(m, b)
}
func (m *NameList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameList.Marshal(b, m, deterministic)
}
func (m *NameList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameList.Merge(m, src)
}
func (m *NameList) XXX_Size() int {
	return xxx_messageInfo_NameList.Size(m)
}
func (m *NameList) XXX_DiscardUnknown() {
	xxx_messageInfo_NameList.DiscardUnknown(m)
}

var xxx_messageInfo_NameList proto.InternalMessageInfo

func (m *NameList) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type Key struct {
	SetName              string   `protobuf:"bytes,1,opt,name=setName,proto3" json:"setName,omitempty"`
	PartitionKey         []byte   `protobuf:"bytes,2,opt,name=partitionKey,proto3" json:"partitionKey,omitempty"`
	RecordKey            []byte   `protobuf:"bytes,3,opt,name=recordKey,proto3" json:"recordKey,omitempty"`
	Timestamp            uint64   `protobuf:"fixed64,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{7}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetSetName() string {
	if m != nil {
		return m.SetName
	}
	return ""
}

func (m *Key) GetPartitionKey() []byte {
	if m != nil {
		return m.PartitionKey
	}
	return nil
}

func (m *Key) GetRecordKey() []byte {
	if m != nil {
		return m.RecordKey
	}
	return nil
}

func (m *Key) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Record struct {
	Version int64  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Value   []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// optional
	Compression          *Compression `protobuf:"bytes,5,opt,name=compression,proto3" json:"compression,omitempty"`
	Encryption           *Encryption  `protobuf:"bytes,6,opt,name=encryption,proto3" json:"encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{8}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Record) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Record) GetCompression() *Compression {
	if m != nil {
		return m.Compression
	}
	return nil
}

func (m *Record) GetEncryption() *Encryption {
	if m != nil {
		return m.Encryption
	}
	return nil
}

type RecordOperation struct {
	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Operation:
	//	*RecordOperation_Exists
	//	*RecordOperation_Get
	//	*RecordOperation_Touch
	//	*RecordOperation_Put
	//	*RecordOperation_Remove
	Operation            isRecordOperation_Operation `protobuf_oneof:"operation"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *RecordOperation) Reset()         { *m = RecordOperation{} }
func (m *RecordOperation) String() string { return proto.CompactTextString(m) }
func (*RecordOperation) ProtoMessage()    {}
func (*RecordOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{9}
}

func (m *RecordOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordOperation.Unmarshal(m, b)
}
func (m *RecordOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordOperation.Marshal(b, m, deterministic)
}
func (m *RecordOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordOperation.Merge(m, src)
}
func (m *RecordOperation) XXX_Size() int {
	return xxx_messageInfo_RecordOperation.Size(m)
}
func (m *RecordOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordOperation.DiscardUnknown(m)
}

var xxx_messageInfo_RecordOperation proto.InternalMessageInfo

func (m *RecordOperation) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type isRecordOperation_Operation interface {
	isRecordOperation_Operation()
}

type RecordOperation_Exists struct {
	Exists *ExistsOperation `protobuf:"bytes,10,opt,name=exists,proto3,oneof"`
}

type RecordOperation_Get struct {
	Get *GetOperation `protobuf:"bytes,11,opt,name=get,proto3,oneof"`
}

type RecordOperation_Touch struct {
	Touch *TouchOperation `protobuf:"bytes,12,opt,name=touch,proto3,oneof"`
}

type RecordOperation_Put struct {
	Put *PutOperation `protobuf:"bytes,13,opt,name=put,proto3,oneof"`
}

type RecordOperation_Remove struct {
	Remove *RemoveOperation `protobuf:"bytes,14,opt,name=remove,proto3,oneof"`
}

func (*RecordOperation_Exists) isRecordOperation_Operation() {}

func (*RecordOperation_Get) isRecordOperation_Operation() {}

func (*RecordOperation_Touch) isRecordOperation_Operation() {}

func (*RecordOperation_Put) isRecordOperation_Operation() {}

func (*RecordOperation_Remove) isRecordOperation_Operation() {}

func (m *RecordOperation) GetOperation() isRecordOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *RecordOperation) GetExists() *ExistsOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Exists); ok {
		return x.Exists
	}
	return nil
}

func (m *RecordOperation) GetGet() *GetOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Get); ok {
		return x.Get
	}
	return nil
}

func (m *RecordOperation) GetTouch() *TouchOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Touch); ok {
		return x.Touch
	}
	return nil
}

func (m *RecordOperation) GetPut() *PutOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Put); ok {
		return x.Put
	}
	return nil
}

func (m *RecordOperation) GetRemove() *RemoveOperation {
	if x, ok := m.GetOperation().(*RecordOperation_Remove); ok {
		return x.Remove
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RecordOperation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RecordOperation_OneofMarshaler, _RecordOperation_OneofUnmarshaler, _RecordOperation_OneofSizer, []interface{}{
		(*RecordOperation_Exists)(nil),
		(*RecordOperation_Get)(nil),
		(*RecordOperation_Touch)(nil),
		(*RecordOperation_Put)(nil),
		(*RecordOperation_Remove)(nil),
	}
}

func _RecordOperation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RecordOperation)
	// operation
	switch x := m.Operation.(type) {
	case *RecordOperation_Exists:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Exists); err != nil {
			return err
		}
	case *RecordOperation_Get:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *RecordOperation_Touch:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Touch); err != nil {
			return err
		}
	case *RecordOperation_Put:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case *RecordOperation_Remove:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Remove); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RecordOperation.Operation has unexpected type %T", x)
	}
	return nil
}

func _RecordOperation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RecordOperation)
	switch tag {
	case 10: // operation.exists
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExistsOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Exists{msg}
		return true, err
	case 11: // operation.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Get{msg}
		return true, err
	case 12: // operation.touch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TouchOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Touch{msg}
		return true, err
	case 13: // operation.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Put{msg}
		return true, err
	case 14: // operation.remove
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveOperation)
		err := b.DecodeMessage(msg)
		m.Operation = &RecordOperation_Remove{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RecordOperation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RecordOperation)
	// operation
	switch x := m.Operation.(type) {
	case *RecordOperation_Exists:
		s := proto.Size(x.Exists)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordOperation_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordOperation_Touch:
		s := proto.Size(x.Touch)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordOperation_Put:
		s := proto.Size(x.Put)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordOperation_Remove:
		s := proto.Size(x.Remove)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ExistsOperation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistsOperation) Reset()         { *m = ExistsOperation{} }
func (m *ExistsOperation) String() string { return proto.CompactTextString(m) }
func (*ExistsOperation) ProtoMessage()    {}
func (*ExistsOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{10}
}

func (m *ExistsOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistsOperation.Unmarshal(m, b)
}
func (m *ExistsOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistsOperation.Marshal(b, m, deterministic)
}
func (m *ExistsOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistsOperation.Merge(m, src)
}
func (m *ExistsOperation) XXX_Size() int {
	return xxx_messageInfo_ExistsOperation.Size(m)
}
func (m *ExistsOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistsOperation.DiscardUnknown(m)
}

var xxx_messageInfo_ExistsOperation proto.InternalMessageInfo

type GetOperation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOperation) Reset()         { *m = GetOperation{} }
func (m *GetOperation) String() string { return proto.CompactTextString(m) }
func (*GetOperation) ProtoMessage()    {}
func (*GetOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{11}
}

func (m *GetOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOperation.Unmarshal(m, b)
}
func (m *GetOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOperation.Marshal(b, m, deterministic)
}
func (m *GetOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOperation.Merge(m, src)
}
func (m *GetOperation) XXX_Size() int {
	return xxx_messageInfo_GetOperation.Size(m)
}
func (m *GetOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOperation.DiscardUnknown(m)
}

var xxx_messageInfo_GetOperation proto.InternalMessageInfo

type TouchOperation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchOperation) Reset()         { *m = TouchOperation{} }
func (m *TouchOperation) String() string { return proto.CompactTextString(m) }
func (*TouchOperation) ProtoMessage()    {}
func (*TouchOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{12}
}

func (m *TouchOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchOperation.Unmarshal(m, b)
}
func (m *TouchOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchOperation.Marshal(b, m, deterministic)
}
func (m *TouchOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchOperation.Merge(m, src)
}
func (m *TouchOperation) XXX_Size() int {
	return xxx_messageInfo_TouchOperation.Size(m)
}
func (m *TouchOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TouchOperation proto.InternalMessageInfo

type PutOperation struct {
	CompareAndSet        bool     `protobuf:"varint,1,opt,name=compareAndSet,proto3" json:"compareAndSet,omitempty"`
	Version              int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds           int32    `protobuf:"varint,4,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutOperation) Reset()         { *m = PutOperation{} }
func (m *PutOperation) String() string { return proto.CompactTextString(m) }
func (*PutOperation) ProtoMessage()    {}
func (*PutOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{13}
}

func (m *PutOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutOperation.Unmarshal(m, b)
}
func (m *PutOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutOperation.Marshal(b, m, deterministic)
}
func (m *PutOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutOperation.Merge(m, src)
}
func (m *PutOperation) XXX_Size() int {
	return xxx_messageInfo_PutOperation.Size(m)
}
func (m *PutOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_PutOperation.DiscardUnknown(m)
}

var xxx_messageInfo_PutOperation proto.InternalMessageInfo

func (m *PutOperation) GetCompareAndSet() bool {
	if m != nil {
		return m.CompareAndSet
	}
	return false
}

func (m *PutOperation) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PutOperation) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutOperation) GetTtlSeconds() int32 {
	if m != nil {
		return m.TtlSeconds
	}
	return 0
}

type RemoveOperation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOperation) Reset()         { *m = RemoveOperation{} }
func (m *RemoveOperation) String() string { return proto.CompactTextString(m) }
func (*RemoveOperation) ProtoMessage()    {}
func (*RemoveOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{14}
}

func (m *RemoveOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOperation.Unmarshal(m, b)
}
func (m *RemoveOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOperation.Marshal(b, m, deterministic)
}
func (m *RemoveOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOperation.Merge(m, src)
}
func (m *RemoveOperation) XXX_Size() int {
	return xxx_messageInfo_RemoveOperation.Size(m)
}
func (m *RemoveOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOperation.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOperation proto.InternalMessageInfo

type RecordResult struct {
	Status       StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=bb.StatusCode" json:"status,omitempty"`
	ErrorMessage string     `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*RecordResult_Exists
	//	*RecordResult_Get
	//	*RecordResult_Touch
	//	*RecordResult_Put
	//	*RecordResult_Remove
	Result               isRecordResult_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RecordResult) Reset()         { *m = RecordResult{} }
func (m *RecordResult) String() string { return proto.CompactTextString(m) }
func (*RecordResult) ProtoMessage()    {}
func (*RecordResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{15}
}

func (m *RecordResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordResult.Unmarshal(m, b)
}
func (m *RecordResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordResult.Marshal(b, m, deterministic)
}
func (m *RecordResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordResult.Merge(m, src)
}
func (m *RecordResult) XXX_Size() int {
	return xxx_messageInfo_RecordResult.Size(m)
}
func (m *RecordResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordResult.DiscardUnknown(m)
}

var xxx_messageInfo_RecordResult proto.InternalMessageInfo

func (m *RecordResult) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

func (m *RecordResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type isRecordResult_Result interface {
	isRecordResult_Result()
}

type RecordResult_Exists struct {
	Exists *ExistsResult `protobuf:"bytes,10,opt,name=exists,proto3,oneof"`
}

type RecordResult_Get struct {
	Get *GetResult `protobuf:"bytes,11,opt,name=get,proto3,oneof"`
}

type RecordResult_Touch struct {
	Touch *TouchResult `protobuf:"bytes,12,opt,name=touch,proto3,oneof"`
}

type RecordResult_Put struct {
	Put *PutResult `protobuf:"bytes,13,opt,name=put,proto3,oneof"`
}

type RecordResult_Remove struct {
	Remove *RemoveResult `protobuf:"bytes,14,opt,name=remove,proto3,oneof"`
}

func (*RecordResult_Exists) isRecordResult_Result() {}

func (*RecordResult_Get) isRecordResult_Result() {}

func (*RecordResult_Touch) isRecordResult_Result() {}

func (*RecordResult_Put) isRecordResult_Result() {}

func (*RecordResult_Remove) isRecordResult_Result() {}

func (m *RecordResult) GetResult() isRecordResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RecordResult) GetExists() *ExistsResult {
	if x, ok := m.GetResult().(*RecordResult_Exists); ok {
		return x.Exists
	}
	return nil
}

func (m *RecordResult) GetGet() *GetResult {
	if x, ok := m.GetResult().(*RecordResult_Get); ok {
		return x.Get
	}
	return nil
}

func (m *RecordResult) GetTouch() *TouchResult {
	if x, ok := m.GetResult().(*RecordResult_Touch); ok {
		return x.Touch
	}
	return nil
}

func (m *RecordResult) GetPut() *PutResult {
	if x, ok := m.GetResult().(*RecordResult_Put); ok {
		return x.Put
	}
	return nil
}

func (m *RecordResult) GetRemove() *RemoveResult {
	if x, ok := m.GetResult().(*RecordResult_Remove); ok {
		return x.Remove
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RecordResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RecordResult_OneofMarshaler, _RecordResult_OneofUnmarshaler, _RecordResult_OneofSizer, []interface{}{
		(*RecordResult_Exists)(nil),
		(*RecordResult_Get)(nil),
		(*RecordResult_Touch)(nil),
		(*RecordResult_Put)(nil),
		(*RecordResult_Remove)(nil),
	}
}

func _RecordResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RecordResult)
	// result
	switch x := m.Result.(type) {
	case *RecordResult_Exists:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Exists); err != nil {
			return err
		}
	case *RecordResult_Get:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *RecordResult_Touch:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Touch); err != nil {
			return err
		}
	case *RecordResult_Put:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case *RecordResult_Remove:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Remove); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RecordResult.Result has unexpected type %T", x)
	}
	return nil
}

func _RecordResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RecordResult)
	switch tag {
	case 10: // result.exists
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExistsResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Exists{msg}
		return true, err
	case 11: // result.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Get{msg}
		return true, err
	case 12: // result.touch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TouchResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Touch{msg}
		return true, err
	case 13: // result.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Put{msg}
		return true, err
	case 14: // result.remove
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveResult)
		err := b.DecodeMessage(msg)
		m.Result = &RecordResult_Remove{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RecordResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RecordResult)
	// result
	switch x := m.Result.(type) {
	case *RecordResult_Exists:
		s := proto.Size(x.Exists)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordResult_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordResult_Touch:
		s := proto.Size(x.Touch)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordResult_Put:
		s := proto.Size(x.Put)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RecordResult_Remove:
		s := proto.Size(x.Remove)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ExistsResult struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Timestamp            uint64   `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistsResult) Reset()         { *m = ExistsResult{} }
func (m *ExistsResult) String() string { return proto.CompactTextString(m) }
func (*ExistsResult) ProtoMessage()    {}
func (*ExistsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{16}
}

func (m *ExistsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistsResult.Unmarshal(m, b)
}
func (m *ExistsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistsResult.Marshal(b, m, deterministic)
}
func (m *ExistsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistsResult.Merge(m, src)
}
func (m *ExistsResult) XXX_Size() int {
	return xxx_messageInfo_ExistsResult.Size(m)
}
func (m *ExistsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistsResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExistsResult proto.InternalMessageInfo

func (m *ExistsResult) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *ExistsResult) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetResult struct {
	Version              int64    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp            uint64   `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResult) Reset()         { *m = GetResult{} }
func (m *GetResult) String() string { return proto.CompactTextString(m) }
func (*GetResult) ProtoMessage()    {}
func (*GetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{17}
}

func (m *GetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResult.Unmarshal(m, b)
}
func (m *GetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResult.Marshal(b, m, deterministic)
}
func (m *GetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResult.Merge(m, src)
}
func (m *GetResult) XXX_Size() int {
	return xxx_messageInfo_GetResult.Size(m)
}
func (m *GetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetResult proto.InternalMessageInfo

func (m *GetResult) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetResult) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetResult) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type TouchResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchResult) Reset()         { *m = TouchResult{} }
func (m *TouchResult) String() string { return proto.CompactTextString(m) }
func (*TouchResult) ProtoMessage()    {}
func (*TouchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{18}
}

func (m *TouchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchResult.Unmarshal(m, b)
}
func (m *TouchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchResult.Marshal(b, m, deterministic)
}
func (m *TouchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchResult.Merge(m, src)
}
func (m *TouchResult) XXX_Size() int {
	return xxx_messageInfo_TouchResult.Size(m)
}
func (m *TouchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchResult.DiscardUnknown(m)
}

var xxx_messageInfo_TouchResult proto.InternalMessageInfo

type PutResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResult) Reset()         { *m = PutResult{} }
func (m *PutResult) String() string { return proto.CompactTextString(m) }
func (*PutResult) ProtoMessage()    {}
func (*PutResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{19}
}

func (m *PutResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResult.Unmarshal(m, b)
}
func (m *PutResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResult.Marshal(b, m, deterministic)
}
func (m *PutResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResult.Merge(m, src)
}
func (m *PutResult) XXX_Size() int {
	return xxx_messageInfo_PutResult.Size(m)
}
func (m *PutResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResult.DiscardUnknown(m)
}

var xxx_messageInfo_PutResult proto.InternalMessageInfo

type RemoveResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResult) Reset()         { *m = RemoveResult{} }
func (m *RemoveResult) String() string { return proto.CompactTextString(m) }
func (*RemoveResult) ProtoMessage()    {}
func (*RemoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{20}
}

func (m *RemoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResult.Unmarshal(m, b)
}
func (m *RemoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResult.Marshal(b, m, deterministic)
}
func (m *RemoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResult.Merge(m, src)
}
func (m *RemoveResult) XXX_Size() int {
	return xxx_messageInfo_RemoveResult.Size(m)
}
func (m *RemoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResult proto.InternalMessageInfo

type RecordRequest struct {
	List                 []*RecordOperation `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RecordRequest) Reset()         { *m = RecordRequest{} }
func (m *RecordRequest) String() string { return proto.CompactTextString(m) }
func (*RecordRequest) ProtoMessage()    {}
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{21}
}

func (m *RecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordRequest.Unmarshal(m, b)
}
func (m *RecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordRequest.Marshal(b, m, deterministic)
}
func (m *RecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRequest.Merge(m, src)
}
func (m *RecordRequest) XXX_Size() int {
	return xxx_messageInfo_RecordRequest.Size(m)
}
func (m *RecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRequest proto.InternalMessageInfo

func (m *RecordRequest) GetList() []*RecordOperation {
	if m != nil {
		return m.List
	}
	return nil
}

type RecordResponse struct {
	List                 []*RecordResult `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecordResponse) Reset()         { *m = RecordResponse{} }
func (m *RecordResponse) String() string { return proto.CompactTextString(m) }
func (*RecordResponse) ProtoMessage()    {}
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a14183de89fcd5b, []int{22}
}

func (m *RecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordResponse.Unmarshal(m, b)
}
func (m *RecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordResponse.Marshal(b, m, deterministic)
}
func (m *RecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordResponse.Merge(m, src)
}
func (m *RecordResponse) XXX_Size() int {
	return xxx_messageInfo_RecordResponse.Size(m)
}
func (m *RecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecordResponse proto.InternalMessageInfo

func (m *RecordResponse) GetList() []*RecordResult {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("bb.DataDistribution", DataDistribution_name, DataDistribution_value)
	proto.RegisterEnum("bb.PointInTime", PointInTime_name, PointInTime_value)
	proto.RegisterEnum("bb.EncryptionAlgorithm", EncryptionAlgorithm_name, EncryptionAlgorithm_value)
	proto.RegisterEnum("bb.EncryptionMode", EncryptionMode_name, EncryptionMode_value)
	proto.RegisterEnum("bb.DataCompression", DataCompression_name, DataCompression_value)
	proto.RegisterEnum("bb.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Partition)(nil), "bb.Partition")
	proto.RegisterType((*Encryption)(nil), "bb.Encryption")
	proto.RegisterType((*Compression)(nil), "bb.Compression")
	proto.RegisterType((*Dataset)(nil), "bb.Dataset")
	proto.RegisterType((*Empty)(nil), "bb.Empty")
	proto.RegisterType((*Name)(nil), "bb.Name")
	proto.RegisterType((*NameList)(nil), "bb.NameList")
	proto.RegisterType((*Key)(nil), "bb.Key")
	proto.RegisterType((*Record)(nil), "bb.Record")
	proto.RegisterType((*RecordOperation)(nil), "bb.RecordOperation")
	proto.RegisterType((*ExistsOperation)(nil), "bb.ExistsOperation")
	proto.RegisterType((*GetOperation)(nil), "bb.GetOperation")
	proto.RegisterType((*TouchOperation)(nil), "bb.TouchOperation")
	proto.RegisterType((*PutOperation)(nil), "bb.PutOperation")
	proto.RegisterType((*RemoveOperation)(nil), "bb.RemoveOperation")
	proto.RegisterType((*RecordResult)(nil), "bb.RecordResult")
	proto.RegisterType((*ExistsResult)(nil), "bb.ExistsResult")
	proto.RegisterType((*GetResult)(nil), "bb.GetResult")
	proto.RegisterType((*TouchResult)(nil), "bb.TouchResult")
	proto.RegisterType((*PutResult)(nil), "bb.PutResult")
	proto.RegisterType((*RemoveResult)(nil), "bb.RemoveResult")
	proto.RegisterType((*RecordRequest)(nil), "bb.RecordRequest")
	proto.RegisterType((*RecordResponse)(nil), "bb.RecordResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatasetServiceClient is the client API for DatasetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatasetServiceClient interface {
	Create(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error)
	Update(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *Name, opts ...grpc.CallOption) (*empty.Empty, error)
	Get(ctx context.Context, in *Name, opts ...grpc.CallOption) (DatasetService_GetClient, error)
}

type datasetServiceClient struct {
	cc *grpc.ClientConn
}

func NewDatasetServiceClient(cc *grpc.ClientConn) DatasetServiceClient {
	return &datasetServiceClient{cc}
}

func (c *datasetServiceClient) Create(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bb.DatasetService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) Update(ctx context.Context, in *Dataset, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bb.DatasetService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) Delete(ctx context.Context, in *Name, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bb.DatasetService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasetServiceClient) Get(ctx context.Context, in *Name, opts ...grpc.CallOption) (DatasetService_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DatasetService_serviceDesc.Streams[0], "/bb.DatasetService/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &datasetServiceGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DatasetService_GetClient interface {
	Recv() (*Dataset, error)
	grpc.ClientStream
}

type datasetServiceGetClient struct {
	grpc.ClientStream
}

func (x *datasetServiceGetClient) Recv() (*Dataset, error) {
	m := new(Dataset)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DatasetServiceServer is the server API for DatasetService service.
type DatasetServiceServer interface {
	Create(context.Context, *Dataset) (*empty.Empty, error)
	Update(context.Context, *Dataset) (*empty.Empty, error)
	Delete(context.Context, *Name) (*empty.Empty, error)
	Get(*Name, DatasetService_GetServer) error
}

func RegisterDatasetServiceServer(s *grpc.Server, srv DatasetServiceServer) {
	s.RegisterService(&_DatasetService_serviceDesc, srv)
}

func _DatasetService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dataset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bb.DatasetService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).Create(ctx, req.(*Dataset))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dataset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bb.DatasetService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).Update(ctx, req.(*Dataset))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasetServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bb.DatasetService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasetServiceServer).Delete(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasetService_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Name)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatasetServiceServer).Get(m, &datasetServiceGetServer{stream})
}

type DatasetService_GetServer interface {
	Send(*Dataset) error
	grpc.ServerStream
}

type datasetServiceGetServer struct {
	grpc.ServerStream
}

func (x *datasetServiceGetServer) Send(m *Dataset) error {
	return x.ServerStream.SendMsg(m)
}

var _DatasetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bb.DatasetService",
	HandlerType: (*DatasetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DatasetService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DatasetService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DatasetService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _DatasetService_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bigbagger.proto",
}

// RecordServiceClient is the client API for RecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordServiceClient interface {
	Execute(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
}

type recordServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecordServiceClient(cc *grpc.ClientConn) RecordServiceClient {
	return &recordServiceClient{cc}
}

func (c *recordServiceClient) Execute(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, "/bb.RecordService/execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordServiceServer is the server API for RecordService service.
type RecordServiceServer interface {
	Execute(context.Context, *RecordRequest) (*RecordResponse, error)
}

func RegisterRecordServiceServer(s *grpc.Server, srv RecordServiceServer) {
	s.RegisterService(&_RecordService_serviceDesc, srv)
}

func _RecordService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bb.RecordService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).Execute(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecordService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bb.RecordService",
	HandlerType: (*RecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "execute",
			Handler:    _RecordService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bigbagger.proto",
}

func init() { proto.RegisterFile("bigbagger.proto", fileDescriptor_5a14183de89fcd5b) }

var fileDescriptor_5a14183de89fcd5b = []byte{
	// 1653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4d, 0x6f, 0xe3, 0xc6,
	0x19, 0x5e, 0x4a, 0x96, 0x64, 0xbd, 0xfa, 0x1a, 0x8f, 0xbd, 0x5e, 0x45, 0x4d, 0x83, 0x2c, 0xb1,
	0xd8, 0x04, 0x6a, 0x56, 0xca, 0xaa, 0x48, 0x50, 0xf8, 0x54, 0x8a, 0xa4, 0x1c, 0x61, 0x69, 0x51,
	0x1d, 0x51, 0xbb, 0x89, 0x0f, 0x15, 0x28, 0x69, 0x2a, 0xb3, 0x95, 0x44, 0x86, 0x1c, 0xb9, 0x6b,
	0x14, 0x45, 0x8a, 0xa2, 0xf7, 0x02, 0xed, 0xb1, 0xe8, 0xa5, 0xb7, 0xa2, 0xf7, 0xf6, 0x87, 0xf4,
	0x2f, 0xf4, 0x87, 0x14, 0x33, 0xfc, 0xb6, 0x77, 0x81, 0xf6, 0x92, 0x93, 0x39, 0xcf, 0xfb, 0xbc,
	0xcf, 0xbc, 0x5f, 0x33, 0x1e, 0x41, 0x6b, 0xe9, 0x6c, 0x96, 0xf6, 0x66, 0x43, 0xfd, 0x9e, 0xe7,
	0xbb, 0xcc, 0xc5, 0x85, 0xe5, 0xb2, 0xf3, 0xe1, 0xc6, 0x75, 0x37, 0x5b, 0xda, 0xb7, 0x3d, 0xa7,
	0x6f, 0xef, 0xf7, 0x2e, 0xb3, 0x99, 0xe3, 0xee, 0x83, 0x90, 0xd1, 0xf9, 0x41, 0x64, 0x15, 0xab,
	0xe5, 0xe1, 0x17, 0x7d, 0xba, 0xf3, 0xd8, 0x5d, 0x64, 0xfc, 0x4c, 0xfc, 0x59, 0xbd, 0xd8, 0xd0,
	0xfd, 0x8b, 0xe0, 0xd7, 0x42, 0xb8, 0xef, 0x7a, 0xc2, 0xfd, 0xa1, 0x94, 0x6c, 0x42, 0x75, 0x6a,
	0xfb, 0xcc, 0xe1, 0x18, 0x3e, 0x83, 0x12, 0x73, 0x99, 0xbd, 0x6d, 0x4b, 0x1f, 0x4b, 0x9f, 0x96,
	0x48, 0xb8, 0xc0, 0x9f, 0xc1, 0x89, 0x4f, 0xbd, 0xad, 0xb3, 0x12, 0x8e, 0x23, 0x7b, 0xc5, 0x5c,
	0xbf, 0x5d, 0x10, 0x8c, 0x87, 0x06, 0xf9, 0xaf, 0x12, 0x80, 0xbe, 0x5f, 0xf9, 0x77, 0x62, 0x4b,
	0xfc, 0x05, 0x54, 0xed, 0xed, 0xc6, 0xf5, 0x1d, 0x76, 0xb3, 0x13, 0xb2, 0xcd, 0xc1, 0x93, 0xde,
	0x72, 0xd9, 0x4b, 0x29, 0x4a, 0x6c, 0x26, 0x29, 0x13, 0x3f, 0x87, 0xa3, 0x9d, 0xbb, 0xa6, 0x62,
	0x9b, 0xe6, 0x00, 0xe7, 0x3d, 0xae, 0xdc, 0x35, 0x25, 0xc2, 0x8e, 0xdb, 0x50, 0x61, 0xae, 0xe7,
	0xbe, 0xa2, 0x77, 0xed, 0xe2, 0xc7, 0xd2, 0xa7, 0x55, 0x12, 0x2f, 0xf1, 0x39, 0x94, 0xf9, 0xe7,
	0xf8, 0xb6, 0x7d, 0x24, 0x0c, 0xd1, 0x4a, 0xb6, 0xa0, 0xa6, 0xba, 0x3b, 0xcf, 0xa7, 0x41, 0xc0,
	0xe3, 0xfb, 0x04, 0x8e, 0x56, 0xee, 0xce, 0x8b, 0x42, 0x3b, 0xe5, 0x1b, 0x69, 0x36, 0xb3, 0x33,
	0x14, 0x22, 0x08, 0xf8, 0x43, 0xa8, 0xb2, 0x1b, 0x9f, 0x06, 0x37, 0xee, 0x76, 0x1d, 0x65, 0x9f,
	0x02, 0xf2, 0x3f, 0x0b, 0x50, 0xe1, 0x7e, 0x01, 0x65, 0x3c, 0xa6, 0x5b, 0xea, 0x73, 0x57, 0xa1,
	0x5a, 0x25, 0xf1, 0x12, 0x63, 0x38, 0xda, 0xdb, 0xbb, 0x30, 0xab, 0x2a, 0x11, 0xdf, 0xb8, 0x0b,
	0xa5, 0xb5, 0x13, 0x30, 0x5f, 0xc4, 0xdf, 0x1c, 0x9c, 0xc5, 0x11, 0x68, 0x1c, 0x74, 0x96, 0x07,
	0x9e, 0x30, 0x09, 0x29, 0xf8, 0x47, 0x50, 0xf5, 0xe2, 0x66, 0x89, 0xb4, 0x6a, 0x83, 0x06, 0xe7,
	0x27, 0x1d, 0x24, 0xa9, 0x1d, 0xbf, 0x84, 0xda, 0x2a, 0xcd, 0xa2, 0x5d, 0x12, 0xf4, 0x16, 0xa7,
	0x67, 0x93, 0xcb, 0x72, 0x70, 0x0f, 0x80, 0x26, 0x55, 0x6e, 0x97, 0x85, 0x47, 0x33, 0x5f, 0x7b,
	0x92, 0x61, 0xe0, 0xa7, 0x50, 0xf4, 0x1c, 0xd6, 0xae, 0x88, 0xc8, 0x85, 0xf4, 0xd4, 0x75, 0xf6,
	0x6c, 0xbc, 0xb7, 0x9c, 0x1d, 0x25, 0xdc, 0x86, 0x3f, 0x02, 0x60, 0x6c, 0x3b, 0xa3, 0x2b, 0x77,
	0xbf, 0x0e, 0xda, 0xc7, 0xa2, 0x6e, 0x19, 0x44, 0xae, 0x40, 0x49, 0xe7, 0xc3, 0x2b, 0x77, 0xe0,
	0x68, 0xc2, 0xeb, 0x11, 0xd7, 0x48, 0x4a, 0x6b, 0x24, 0x7f, 0x04, 0xc7, 0xdc, 0x66, 0x38, 0x01,
	0xcb, 0xd8, 0x8b, 0x89, 0xfd, 0x3b, 0x28, 0xf2, 0x96, 0xb7, 0xa1, 0x12, 0x50, 0x36, 0x49, 0xbd,
	0xe3, 0x25, 0x96, 0xa1, 0x9e, 0x14, 0x86, 0xcf, 0x0a, 0x6f, 0x40, 0x9d, 0xe4, 0x30, 0xde, 0x60,
	0x9f, 0xae, 0x5c, 0x7f, 0x1d, 0x0f, 0x53, 0x9d, 0xa4, 0x80, 0x68, 0xbf, 0xb3, 0xa3, 0x01, 0xb3,
	0x77, 0x9e, 0x28, 0x7d, 0x99, 0xa4, 0x80, 0xfc, 0x17, 0x09, 0xca, 0x44, 0x70, 0xef, 0x77, 0xbf,
	0x98, 0x76, 0xff, 0x0c, 0x4a, 0xb7, 0xf6, 0xf6, 0x40, 0xa3, 0xdd, 0xc3, 0xc5, 0xf7, 0xd0, 0x26,
	0xf9, 0x8f, 0x05, 0x68, 0x85, 0xd1, 0x99, 0x1e, 0xf5, 0xc5, 0x61, 0xc5, 0x1f, 0x40, 0xf1, 0x57,
	0xf4, 0x4e, 0x84, 0x58, 0x1b, 0x54, 0xb8, 0xf3, 0x2b, 0x7a, 0x47, 0x38, 0x86, 0x5f, 0x40, 0x99,
	0xbe, 0x75, 0x02, 0x16, 0xb4, 0x41, 0x58, 0xc5, 0xa1, 0xd0, 0x05, 0x92, 0xf8, 0x7f, 0xf5, 0x88,
	0x44, 0x24, 0xfc, 0x0c, 0x8a, 0x1b, 0xca, 0xda, 0x35, 0xc1, 0x45, 0x9c, 0x7b, 0x49, 0x59, 0x96,
	0xc8, 0xcd, 0x7c, 0xcc, 0x99, 0x7b, 0x58, 0xdd, 0xb4, 0xeb, 0x82, 0x27, 0x4e, 0xb4, 0xc5, 0x81,
	0x2c, 0x33, 0xa4, 0x70, 0x45, 0xef, 0xc0, 0xda, 0x8d, 0x54, 0x71, 0x7a, 0xc8, 0x2b, 0x7a, 0x07,
	0xc6, 0xc3, 0xf4, 0xe9, 0xce, 0xbd, 0xa5, 0xed, 0x66, 0x1a, 0x26, 0x11, 0x48, 0x2e, 0xcc, 0x90,
	0x34, 0xac, 0x41, 0xd5, 0x8d, 0x61, 0xf9, 0x04, 0x5a, 0xf7, 0x12, 0x92, 0x9b, 0x50, 0xcf, 0xc6,
	0x2d, 0x23, 0x68, 0xe6, 0xe3, 0x93, 0xff, 0x20, 0x41, 0x3d, 0x1b, 0x08, 0x7e, 0x06, 0x0d, 0xde,
	0x16, 0xdb, 0xa7, 0xca, 0x7e, 0x3d, 0xa3, 0x4c, 0x54, 0xf3, 0x98, 0xe4, 0xc1, 0xec, 0x40, 0x14,
	0xde, 0x33, 0x10, 0xc5, 0xec, 0x40, 0xe4, 0x4f, 0xcc, 0xd1, 0x83, 0x13, 0x73, 0xc2, 0x9b, 0x99,
	0xcb, 0x52, 0xfe, 0x47, 0x01, 0xea, 0x61, 0x83, 0x09, 0x0d, 0x0e, 0x5b, 0x86, 0x9f, 0x43, 0x39,
	0x60, 0x36, 0x3b, 0x04, 0xd1, 0xbd, 0x26, 0xa6, 0x63, 0x26, 0x10, 0x95, 0x5f, 0x9e, 0x91, 0x95,
	0x9f, 0x0b, 0xea, 0xfb, 0xae, 0x7f, 0x45, 0x83, 0xc0, 0xde, 0xc4, 0x17, 0x53, 0x0e, 0xc3, 0xdd,
	0x7b, 0xe3, 0x80, 0xd2, 0x71, 0x08, 0x77, 0xcb, 0xcc, 0xc2, 0xd3, 0xec, 0x2c, 0x34, 0xa2, 0x59,
	0x48, 0x58, 0x62, 0x10, 0x3e, 0xc9, 0x0f, 0x42, 0x2b, 0x19, 0x84, 0x84, 0x16, 0x4d, 0xc1, 0xd3,
	0xec, 0x14, 0x34, 0xa2, 0x29, 0x48, 0xb5, 0xf8, 0x08, 0x74, 0xef, 0x8d, 0x00, 0x4a, 0x47, 0x20,
	0x0d, 0x2d, 0xea, 0xff, 0x31, 0xe7, 0x72, 0x4c, 0xd6, 0xa0, 0x9e, 0x0d, 0x9f, 0xff, 0xa7, 0x88,
	0x12, 0x0c, 0xfb, 0x17, 0x27, 0x93, 0x3b, 0xf2, 0x85, 0xfb, 0x47, 0xfe, 0x1b, 0xa8, 0x26, 0xb9,
	0xfd, 0xdf, 0x87, 0x3e, 0x27, 0x5d, 0xbc, 0x2f, 0xdd, 0x80, 0x5a, 0xa6, 0x22, 0x72, 0x0d, 0xaa,
	0x49, 0xe6, 0x7c, 0x4c, 0xb3, 0x09, 0xca, 0x3f, 0x81, 0x46, 0xdc, 0xf9, 0x6f, 0x0f, 0x34, 0xe0,
	0xf5, 0x3d, 0xda, 0x3a, 0x01, 0x13, 0xf7, 0x63, 0x72, 0x28, 0x72, 0x67, 0x9f, 0x08, 0x82, 0xfc,
	0x25, 0x34, 0x93, 0x99, 0xf1, 0xdc, 0x7d, 0x40, 0xf1, 0xb3, 0x9c, 0x2b, 0x4a, 0x5d, 0xc3, 0xbd,
	0x42, 0xbf, 0xee, 0x08, 0xd0, 0xfd, 0xff, 0x4f, 0xb8, 0x0e, 0xc7, 0x9a, 0xb6, 0x30, 0x4c, 0x55,
	0x31, 0xd0, 0x23, 0x8c, 0xa1, 0xa9, 0x69, 0x0b, 0xa2, 0x4f, 0x8d, 0xb1, 0xaa, 0x58, 0x63, 0x73,
	0x82, 0x24, 0x8c, 0xa0, 0xae, 0x69, 0x8b, 0xa9, 0x42, 0xac, 0xb1, 0x40, 0x0a, 0xdd, 0x3b, 0xa8,
	0x65, 0xfe, 0x5b, 0x60, 0x80, 0xf2, 0x74, 0x6c, 0x2d, 0x26, 0x26, 0x7a, 0xc4, 0xc9, 0xfc, 0xdb,
	0x50, 0x66, 0xd6, 0xc2, 0x9c, 0xe8, 0x48, 0xc2, 0x27, 0xd0, 0x48, 0x90, 0xd1, 0xf8, 0xb5, 0x8e,
	0x4a, 0x39, 0x92, 0xa5, 0x4f, 0x10, 0xe0, 0x0e, 0x9c, 0x73, 0x64, 0x34, 0x26, 0x21, 0x94, 0xda,
	0xce, 0x70, 0x0d, 0x2a, 0xdc, 0xa6, 0x18, 0x06, 0x5a, 0x77, 0x5f, 0xc2, 0xe9, 0x3b, 0xde, 0x1f,
	0x3c, 0x04, 0xc5, 0xb8, 0x0c, 0x43, 0x68, 0x02, 0xf0, 0x6f, 0x45, 0x9f, 0x0d, 0xbe, 0xf8, 0x12,
	0x49, 0xdd, 0x6f, 0xa1, 0x99, 0x7f, 0x80, 0x70, 0xc5, 0x2b, 0x53, 0xd3, 0x43, 0x7a, 0x1d, 0x8e,
	0xc5, 0x42, 0x57, 0x87, 0x48, 0x4a, 0x56, 0xea, 0x50, 0x45, 0x85, 0x64, 0x65, 0x8e, 0x86, 0xa8,
	0x98, 0xda, 0x46, 0x43, 0x74, 0x94, 0xae, 0x2c, 0x82, 0x4a, 0xc9, 0xea, 0x6b, 0x6b, 0x86, 0xca,
	0xdd, 0x9f, 0x43, 0xeb, 0xde, 0x53, 0x04, 0x57, 0xa1, 0xa4, 0xa9, 0xc9, 0x8e, 0x9a, 0xba, 0x18,
	0x19, 0x8a, 0xc5, 0xeb, 0x53, 0x83, 0x8a, 0xa6, 0x2e, 0x2e, 0xaf, 0xc7, 0x53, 0x54, 0xe0, 0x79,
	0x68, 0xea, 0xc2, 0xb8, 0x7e, 0x83, 0x8a, 0x91, 0xe1, 0xda, 0x18, 0x47, 0xbb, 0x69, 0xea, 0x62,
	0x78, 0x3d, 0x9e, 0x0e, 0x50, 0xa9, 0xfb, 0xbb, 0x22, 0x40, 0x7a, 0x27, 0x70, 0xe6, 0x6c, 0xae,
	0xaa, 0xfa, 0x6c, 0x86, 0x1e, 0xe1, 0x27, 0x70, 0x1a, 0x2d, 0x16, 0x13, 0xd3, 0x5a, 0xcc, 0xa7,
	0x9a, 0x62, 0xe9, 0x1a, 0x92, 0xf0, 0x19, 0x20, 0x9d, 0x10, 0x93, 0x2c, 0x26, 0xe6, 0x42, 0x53,
	0x2c, 0x65, 0xa6, 0x5b, 0x08, 0xf0, 0x63, 0x38, 0x09, 0xd1, 0xa1, 0xc2, 0x1b, 0xff, 0xb3, 0xb9,
	0x3e, 0xb3, 0x50, 0x8d, 0xb7, 0x28, 0x84, 0xa7, 0xa6, 0x31, 0x56, 0xbf, 0x41, 0x75, 0x7c, 0x0a,
	0xad, 0x10, 0xb9, 0x1a, 0x5f, 0x92, 0x70, 0x36, 0x1a, 0xbc, 0xb9, 0x91, 0xa6, 0x6e, 0xbd, 0x31,
	0xc9, 0x2b, 0xd4, 0xe4, 0xe5, 0x0f, 0x21, 0x65, 0x6e, 0x7d, 0x85, 0x5a, 0xa9, 0xdf, 0xc8, 0x24,
	0xc3, 0xb1, 0xa6, 0xe9, 0x13, 0x84, 0x52, 0x3f, 0x6b, 0x7c, 0xa5, 0x9b, 0x73, 0x0b, 0x9d, 0xf0,
	0xd1, 0x0b, 0x21, 0xf3, 0xb5, 0x4e, 0x0c, 0x53, 0xd1, 0x10, 0xce, 0x63, 0x23, 0xc3, 0x7c, 0x83,
	0x4e, 0xd3, 0xc8, 0x0c, 0x53, 0x7d, 0xa5, 0x6b, 0xe8, 0x2c, 0x15, 0x53, 0x86, 0x26, 0xe1, 0xb9,
	0x3e, 0x4e, 0xb3, 0x1a, 0x4f, 0x2c, 0x9d, 0x90, 0xf9, 0x94, 0xc3, 0xe7, 0x29, 0x3c, 0x9f, 0xcc,
	0xe6, 0xd3, 0x69, 0xc8, 0x7e, 0x92, 0x4a, 0x6a, 0x64, 0xfc, 0x5a, 0x27, 0xa8, 0xcd, 0xcb, 0x1d,
	0xf9, 0x9b, 0xe8, 0x83, 0x34, 0x0c, 0xa1, 0x36, 0x51, 0x0c, 0xd4, 0x19, 0xfc, 0xbd, 0x00, 0xcd,
	0xe8, 0xd9, 0x38, 0xa3, 0xfe, 0xad, 0xb3, 0xa2, 0x58, 0x87, 0xb2, 0xea, 0x53, 0x9b, 0x51, 0x5c,
	0x8b, 0x9f, 0x82, 0x01, 0x65, 0x9d, 0xf3, 0x5e, 0xf8, 0xe6, 0xef, 0xc5, 0x6f, 0xfe, 0x5e, 0xf8,
	0x6c, 0x3a, 0xff, 0xfd, 0xbf, 0xff, 0xf3, 0xe7, 0x02, 0x92, 0x6b, 0xfd, 0xdb, 0x97, 0xfd, 0x75,
	0x48, 0xbe, 0x90, 0xba, 0xd8, 0x80, 0xf2, 0xdc, 0x5b, 0xff, 0xcf, 0x32, 0x3f, 0x14, 0x32, 0x4f,
	0x3a, 0x38, 0x23, 0xd3, 0xff, 0x0d, 0x7f, 0x5c, 0xfd, 0x96, 0xab, 0x8d, 0xa0, 0xac, 0xd1, 0x2d,
	0x65, 0x14, 0x1f, 0x73, 0x35, 0xfe, 0xa6, 0x7a, 0xaf, 0x54, 0x47, 0x48, 0x9d, 0x75, 0xdf, 0x21,
	0x85, 0x2f, 0xa0, 0x78, 0x49, 0x59, 0x46, 0x24, 0x1b, 0x5c, 0xec, 0x89, 0xdf, 0xe1, 0xf9, 0xb9,
	0x34, 0xf8, 0x3a, 0xbe, 0xe9, 0xe2, 0x4a, 0x5d, 0x42, 0x85, 0xbe, 0xa5, 0xab, 0x03, 0xa3, 0xf8,
	0x24, 0x7b, 0x57, 0x89, 0x7b, 0xb0, 0x83, 0x73, 0xd7, 0x97, 0xb8, 0xe0, 0xe4, 0xc7, 0x62, 0x83,
	0x56, 0x07, 0xf8, 0x06, 0xe1, 0xdb, 0xee, 0x42, 0xea, 0x0e, 0xff, 0x25, 0xfd, 0x49, 0xf9, 0x0e,
	0xcf, 0xa1, 0x3a, 0x74, 0x36, 0x43, 0xf1, 0x83, 0x49, 0x56, 0x33, 0x0b, 0xfc, 0xfc, 0x86, 0x31,
	0x2f, 0xb8, 0xe8, 0xf7, 0x37, 0x0e, 0xbb, 0x39, 0x2c, 0x7b, 0x2b, 0x77, 0xd7, 0x4f, 0xac, 0xfd,
	0xe4, 0xe7, 0x5b, 0xa7, 0x69, 0x6f, 0xe9, 0xdb, 0x9f, 0x06, 0x37, 0xb7, 0xce, 0x9a, 0x73, 0x06,
	0xc5, 0x97, 0xbd, 0xcf, 0xbb, 0x05, 0xa9, 0x30, 0x40, 0xb6, 0x97, 0xfc, 0x4c, 0xea, 0xff, 0x32,
	0x70, 0xf7, 0x17, 0x0f, 0x10, 0x38, 0x75, 0xdc, 0x5e, 0xa4, 0x9f, 0x28, 0x0e, 0x8f, 0x87, 0xcb,
	0x29, 0xaf, 0x6e, 0x30, 0x95, 0xae, 0x1b, 0xa2, 0xce, 0xfd, 0xe5, 0x52, 0xfc, 0xfd, 0x5b, 0xa1,
	0x30, 0x5c, 0x2e, 0xcb, 0xe2, 0xfb, 0xc7, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x62, 0x5d,
	0x93, 0x44, 0x0e, 0x00, 0x00,
}
